package br.com.locadora.view;

import br.com.locadora.conexao.InterfacePool;
import br.com.locadora.conexao.Pool;
import br.com.locadora.model.bean.AcessoUsuario;
import br.com.locadora.model.bean.Copia;
import br.com.locadora.model.bean.Objeto;
import br.com.locadora.model.bean.Diaria;
import br.com.locadora.model.bean.Genero;
import br.com.locadora.model.dao.CopiaDAO;
import br.com.locadora.model.dao.ObjetoDAO;
import br.com.locadora.model.dao.UsuarioDAO;
import br.com.locadora.util.ArquivoConfiguracao;
import br.com.locadora.util.Data;
import br.com.locadora.util.ItemDbGrid;
import br.com.locadora.util.LimitadorTexto;
import br.com.locadora.util.Moeda;
import br.com.locadora.util.TemaInterface;
import br.com.locadora.util.UnaccentedDocument;
import static br.com.locadora.view.AtualizaCliente.jtbl_telefone;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ALENCAR
 */
public final class AtualizaObjeto extends javax.swing.JFrame {

    public MenuObjeto janelapai;
//    private Objeto objetoObjeto;
    private InterfacePool pool;
    public List<Copia> copias;
    public MaskFormatter formatoData, formatoNumero;
//    public SiscomController controller;
    public static Genero genero;
    public static Diaria diaria;
    public static Objeto objeto;
    public AcessoUsuario acesso;
    public Copia copia;
    public ConsultaDiariaObjeto consultaDiaria;
    public ConsultaGeneroObjeto consultaGenero;

    /**
     * Creates new form ProdutoCadastroGUI
     */
    public AtualizaObjeto() {
        initComponents();
        janelapai = null;
        TemaInterface.getInterface(this);
    }

    public AtualizaObjeto(Objeto objeto) {
        initComponents();
        if (objeto != null) {
            TemaInterface.getInterface(this);
            janelapai = null;

            jtf_codigo_objeto.setText(String.valueOf(objeto.getCodigo_objeto()));
            jtf_titulo.setText(objeto.getTitulo());
            jcb_tipo.setSelectedItem(objeto.getTipo_movimento());
            jtf_titulo_original.setText(objeto.getTitulo_original());
            jcb_producao.setSelectedItem(objeto.getProducao());
            jtf_duracao.setText(objeto.getDuracao());
            jcb_midia.setSelectedItem(objeto.getMidia());
            jcb_tipo_midia.setSelectedItem(objeto.getTipo_midia());
            jtf_censura.setText(String.valueOf(objeto.getCensura()));
            jta_elenco.setText(objeto.getElenco());
            jta_sinopse.setText(objeto.getSinopse());

            System.out.println("3 - Diária alterar código: " + objeto.getDiaria().getCodigo_diaria());
            System.out.println("3 - Diária alterar descrição: " + objeto.getDiaria().getNome_diaria());
            carregaDiaria(objeto.getDiaria());
            carregaGenero(objeto.getGenero());
            carregaCopia(objeto.getCodigo_objeto());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tfa_similar = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jb_cancelar = new javax.swing.JButton();
        jb_salvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtp_menu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jtf_codigo_objeto = new javax.swing.JTextField();
        jtf_titulo_original = new javax.swing.JTextField(new LimitadorTexto(45), "",10);
        jtf_titulo = new javax.swing.JTextField(new LimitadorTexto(45), "",10);
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtf_duracao = new javax.swing.JTextField(new LimitadorTexto(45), "",10);
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jb_genero = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jcb_producao = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jtf_diaria_dias = new javax.swing.JTextField();
        jtf_descricao_diaria = new javax.swing.JTextField();
        jb_diaria = new javax.swing.JButton();
        jtf_valor = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jrb_ativo = new javax.swing.JRadioButton();
        jrb_inativo = new javax.swing.JRadioButton();
        jcb_midia = new javax.swing.JComboBox();
        jcb_tipo_midia = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jcb_tipo = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        jtf_descricao_genero = new javax.swing.JTextField();
        jtf_censura = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_elenco = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_sinopse = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jb_adicionar_copia = new javax.swing.JButton();
        jb_eliminar1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtbl_copia = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jcb_idioma = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jcb_legenda = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jtf_preco_custo = new javax.swing.JTextField(new LimitadorTexto(10), "",10);
        jLabel31 = new javax.swing.JLabel();
        try  {
            formatoData = new MaskFormatter("##/##/####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null,"Não foi possivel setar");
        }
        jtf_data_aquisicao = new JFormattedTextField(formatoData);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tfa_similar.setColumns(20);
        tfa_similar.setRows(5);
        tfa_similar.setName("tfa_similar"); // NOI18N
        jScrollPane1.setViewportView(tfa_similar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterando Objeto");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jb_cancelar.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/exit.png"))); // NOI18N
        jb_cancelar.setText("Sair");
        jb_cancelar.setMaximumSize(new java.awt.Dimension(101, 33));
        jb_cancelar.setName("jb_cancelar"); // NOI18N
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });

        jb_salvar.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jb_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/gravar_registro.gif"))); // NOI18N
        jb_salvar.setText("Salvar");
        jb_salvar.setName("jb_salvar"); // NOI18N
        jb_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarActionPerformed(evt);
            }
        });
        jb_salvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_salvarKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel2.setText("Observação: Os campos com asteristico na frente são obrigatórios ");
        jLabel2.setName("jLabel2"); // NOI18N

        jtp_menu.setName("jtp_menu"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel1.setName("jPanel1"); // NOI18N

        jtf_codigo_objeto.setEditable(false);
        jtf_codigo_objeto.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_codigo_objeto.setName("jtf_codigo_objeto"); // NOI18N

        jtf_titulo_original.setDocument(new UnaccentedDocument());
        jtf_titulo_original.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_titulo_original.setName("jtf_titulo_original"); // NOI18N
        jtf_titulo_original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_titulo_originalActionPerformed(evt);
            }
        });
        jtf_titulo_original.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_titulo_originalFocusGained(evt);
            }
        });
        jtf_titulo_original.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_titulo_originalKeyPressed(evt);
            }
        });

        jtf_titulo.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_titulo.setName("jtf_titulo"); // NOI18N
        jtf_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_tituloActionPerformed(evt);
            }
        });
        jtf_titulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_tituloFocusGained(evt);
            }
        });
        jtf_titulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_tituloKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_tituloKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel1.setText("Código Objeto");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel3.setText("Título*");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel10.setText("Título Original *");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel14.setText("Duração*");
        jLabel14.setName("jLabel14"); // NOI18N

        jtf_duracao.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_duracao.setName("jtf_duracao"); // NOI18N
        jtf_duracao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_duracaoKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel15.setText("Censura*");
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel23.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel23.setText("Gênero");
        jLabel23.setName("jLabel23"); // NOI18N

        jb_genero.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jb_genero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/pesquisar.png"))); // NOI18N
        jb_genero.setName("jb_genero"); // NOI18N
        jb_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_generoActionPerformed(evt);
            }
        });
        jb_genero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_generoKeyPressed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel24.setText("Produção");
        jLabel24.setName("jLabel24"); // NOI18N

        jLabel34.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel34.setText("Mídia");
        jLabel34.setName("jLabel34"); // NOI18N

        jcb_producao.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jcb_producao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Americana", "Espanhola", "Francesa", "Italiana", "Japonesa", "Nacional" }));
        jcb_producao.setName("jcb_producao"); // NOI18N
        jcb_producao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcb_producaoKeyPressed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel35.setText("Diária");
        jLabel35.setName("jLabel35"); // NOI18N

        jtf_diaria_dias.setEditable(false);
        jtf_diaria_dias.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_diaria_dias.setName("jtf_diaria_dias"); // NOI18N
        jtf_diaria_dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_diaria_diasActionPerformed(evt);
            }
        });

        jtf_descricao_diaria.setEditable(false);
        jtf_descricao_diaria.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_descricao_diaria.setName("jtf_descricao_diaria"); // NOI18N

        jb_diaria.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jb_diaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/pesquisar.png"))); // NOI18N
        jb_diaria.setName("jb_diaria"); // NOI18N
        jb_diaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_diariaActionPerformed(evt);
            }
        });
        jb_diaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_diariaKeyPressed(evt);
            }
        });

        jtf_valor.setEditable(false);
        jtf_valor.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_valor.setText("R$ 0,00");
        jtf_valor.setName("jtf_valor"); // NOI18N
        jtf_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_valorActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel37.setText("Dias");
        jLabel37.setName("jLabel37"); // NOI18N

        buttonGroup1.add(jrb_ativo);
        jrb_ativo.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jrb_ativo.setSelected(true);
        jrb_ativo.setText("Ativo");
        jrb_ativo.setName("jrb_ativo"); // NOI18N
        jrb_ativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_ativoActionPerformed(evt);
            }
        });
        jrb_ativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrb_ativoKeyPressed(evt);
            }
        });

        buttonGroup1.add(jrb_inativo);
        jrb_inativo.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jrb_inativo.setText("Inativo");
        jrb_inativo.setName("jrb_inativo"); // NOI18N
        jrb_inativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrb_inativoKeyPressed(evt);
            }
        });

        jcb_midia.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jcb_midia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blu-Ray", "CD", "DVD", "Playstation", "VHs", "Xbox" }));
        jcb_midia.setName("jcb_midia"); // NOI18N
        jcb_midia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcb_midiaKeyPressed(evt);
            }
        });

        jcb_tipo_midia.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jcb_tipo_midia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Filme", "Seriado", "Game", "Livro" }));
        jcb_tipo_midia.setName("jcb_tipo_midia"); // NOI18N
        jcb_tipo_midia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcb_tipo_midiaKeyPressed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel38.setText("Tipo de Mídia");
        jLabel38.setName("jLabel38"); // NOI18N

        jLabel39.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel39.setText("Tipo*");
        jLabel39.setName("jLabel39"); // NOI18N

        jcb_tipo.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jcb_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Locação", "Venda", " " }));
        jcb_tipo.setName("jcb_tipo"); // NOI18N
        jcb_tipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcb_tipoKeyPressed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel40.setText("Valor");
        jLabel40.setName("jLabel40"); // NOI18N

        jtf_descricao_genero.setEditable(false);
        jtf_descricao_genero.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_descricao_genero.setName("jtf_descricao_genero"); // NOI18N
        jtf_descricao_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_descricao_generoActionPerformed(evt);
            }
        });

        jtf_censura.addKeyListener(new java.awt.event.KeyAdapter() {     // cria um listener ouvinte de digitação do fieldNumero

            public void keyReleased(java.awt.event.KeyEvent evt) {  // cria um ouvinte para cada tecla pressionada

                jtf_censura.setText(jtf_censura.getText().replaceAll("[^0-9]", "")); // faz com que pegue o texto a cada tecla digitada, e substituir tudo que não(^) seja numero  por ""

            }
        });
        jtf_censura.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_censura.setName("jtf_censura"); // NOI18N
        jtf_censura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_censuraKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(267, 267, 267)
                        .addComponent(jLabel37)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtf_descricao_diaria, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jb_diaria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jtf_diaria_dias, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jtf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_duracao, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jtf_censura, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jcb_producao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcb_midia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jcb_tipo_midia, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jrb_ativo)
                            .addGap(10, 10, 10)
                            .addComponent(jrb_inativo))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(16, 16, 16)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jtf_codigo_objeto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jtf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jtf_titulo_original, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtf_descricao_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jcb_midia, jcb_producao, jcb_tipo});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_ativo)
                    .addComponent(jrb_inativo))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_codigo_objeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, 0)
                        .addComponent(jtf_titulo_original, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcb_midia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcb_tipo_midia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(0, 0, 0)
                                .addComponent(jcb_producao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(0, 0, 0)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtf_duracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtf_censura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(29, 29, 29))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel37)
                    .addComponent(jLabel40))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_descricao_diaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_diaria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_diaria_dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel23)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_descricao_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jcb_midia, jcb_producao, jcb_tipo, jcb_tipo_midia, jtf_censura, jtf_duracao});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtf_codigo_objeto, jtf_titulo, jtf_titulo_original});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jb_diaria, jtf_descricao_diaria, jtf_diaria_dias, jtf_valor});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jb_genero, jtf_descricao_genero});

        jtp_menu.addTab("Cadastro", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel3.setName("jPanel3"); // NOI18N

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel17.setText("Sinopse");
        jLabel17.setName("jLabel17"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jta_elenco.setColumns(20);
        jta_elenco.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jta_elenco.setLineWrap(true);
        jta_elenco.setRows(5);
        jta_elenco.setWrapStyleWord(true);
        jta_elenco.setName("jta_elenco"); // NOI18N
        jta_elenco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jta_elencoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jta_elenco);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel4.setText("Elenco");
        jLabel4.setName("jLabel4"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jta_sinopse.setColumns(20);
        jta_sinopse.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jta_sinopse.setLineWrap(true);
        jta_sinopse.setRows(5);
        jta_sinopse.setWrapStyleWord(true);
        jta_sinopse.setName("jta_sinopse"); // NOI18N
        jta_sinopse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jta_sinopseKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jta_sinopse);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jtp_menu.addTab("Cinema", jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel2.setToolTipText("");
        jPanel2.setName("jPanel2"); // NOI18N

        jb_adicionar_copia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/edit_add.png"))); // NOI18N
        jb_adicionar_copia.setToolTipText("Incluir");
        jb_adicionar_copia.setName("jb_adicionar_copia"); // NOI18N
        jb_adicionar_copia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_adicionar_copiaMouseClicked(evt);
            }
        });
        jb_adicionar_copia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_adicionar_copiaKeyPressed(evt);
            }
        });

        jb_eliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/edit_remove.png"))); // NOI18N
        jb_eliminar1.setToolTipText("Excluir");
        jb_eliminar1.setName("jb_eliminar1"); // NOI18N
        jb_eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminar1ActionPerformed(evt);
            }
        });

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        jtbl_copia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cópia", "Código de Barras", "Idioma", "Legenda", "Preço Custo", "Data Aquisição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_copia.setName("jtbl_copia"); // NOI18N
        jtbl_copia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbl_copiaKeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(jtbl_copia);
        if (jtbl_copia.getColumnModel().getColumnCount() > 0) {
            jtbl_copia.getColumnModel().getColumn(0).setPreferredWidth(10);
            jtbl_copia.getColumnModel().getColumn(1).setPreferredWidth(10);
            jtbl_copia.getColumnModel().getColumn(2).setPreferredWidth(30);
            jtbl_copia.getColumnModel().getColumn(3).setPreferredWidth(50);
            jtbl_copia.getColumnModel().getColumn(4).setPreferredWidth(50);
            jtbl_copia.getColumnModel().getColumn(5).setPreferredWidth(20);
            jtbl_copia.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        jLabel27.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel27.setText("Idioma");
        jLabel27.setName("jLabel27"); // NOI18N

        jcb_idioma.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jcb_idioma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chinês", "Espanhol", "Francês", "Inglês", "Italiano", "Japonês", "Polonês", "Português" }));
        jcb_idioma.setName("jcb_idioma"); // NOI18N
        jcb_idioma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcb_idiomaKeyPressed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel28.setText("Legenda");
        jLabel28.setName("jLabel28"); // NOI18N

        jcb_legenda.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jcb_legenda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chinês", "Espanhol", "Francês", "Inglês", "Italiano", "Japonês", "Polonês", "Português", "Não Legendado" }));
        jcb_legenda.setName("jcb_legenda"); // NOI18N
        jcb_legenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcb_legendaKeyPressed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel29.setText("Preço custo");
        jLabel29.setName("jLabel29"); // NOI18N

        jtf_preco_custo.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_preco_custo.setText("R$ 0,00");
        jtf_preco_custo.setName("jtf_preco_custo"); // NOI18N
        jtf_preco_custo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_preco_custoActionPerformed(evt);
            }
        });
        jtf_preco_custo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_preco_custoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_preco_custoFocusLost(evt);
            }
        });
        jtf_preco_custo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_preco_custoKeyPressed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel31.setText("Data Aquisição");
        jLabel31.setName("jLabel31"); // NOI18N

        jtf_data_aquisicao.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_data_aquisicao.setName("jtf_data_aquisicao"); // NOI18N
        jtf_data_aquisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_data_aquisicaoActionPerformed(evt);
            }
        });
        jtf_data_aquisicao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_data_aquisicaoFocusLost(evt);
            }
        });
        jtf_data_aquisicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_data_aquisicaoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jcb_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jcb_legenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jtf_data_aquisicao))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtf_preco_custo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jb_adicionar_copia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jb_eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(0, 0, 0)
                        .addComponent(jcb_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(0, 0, 0)
                        .addComponent(jcb_legenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(0, 0, 0)
                        .addComponent(jtf_data_aquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(0, 0, 0)
                        .addComponent(jtf_preco_custo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jb_adicionar_copia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_eliminar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jb_adicionar_copia, jb_eliminar1, jcb_idioma, jcb_legenda, jtf_data_aquisicao, jtf_preco_custo});

        jtp_menu.addTab("Cópias", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_salvar)
                        .addGap(10, 10, 10)
                        .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtp_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jb_cancelar, jb_salvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jtp_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jb_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jb_cancelar, jb_salvar});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        retornaJanelaPai();
}//GEN-LAST:event_jb_cancelarActionPerformed


    private void jb_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarActionPerformed
        atualizarObjeto();
}//GEN-LAST:event_jb_salvarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jtp_menu.setSelectedIndex(0);
        jtf_titulo.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        retornaJanelaPai();
    }//GEN-LAST:event_formWindowClosed

    private void jtf_titulo_originalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_titulo_originalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_titulo_originalActionPerformed

    private void jtf_titulo_originalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_titulo_originalFocusGained

    }//GEN-LAST:event_jtf_titulo_originalFocusGained

    private void jtf_titulo_originalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_titulo_originalKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtf_duracao.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_titulo_originalKeyPressed

    private void jtf_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_tituloActionPerformed

    private void jtf_tituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_tituloFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_tituloFocusGained

    private void jtf_tituloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_tituloKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtf_titulo_original.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_tituloKeyPressed

    private void jtf_tituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_tituloKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_tituloKeyReleased

    private void jtf_descricao_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_descricao_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descricao_generoActionPerformed

    private void jb_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_generoActionPerformed
        if (consultaGenero == null) {
            consultaGenero = new ConsultaGeneroObjeto();
            consultaGenero.janelapai2 = this;
            consultaGenero.listaTodasGeneros();
            consultaGenero.setVisible(true);
            setStatusTela(false);
        } else {
            consultaGenero.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_generoActionPerformed

    private void jtf_diaria_diasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_diaria_diasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_diaria_diasActionPerformed

    private void jb_diariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_diariaActionPerformed
        if (consultaDiaria == null) {
            consultaDiaria = new ConsultaDiariaObjeto();
            consultaDiaria.janelapai2 = this;
            consultaDiaria.listaTodasDiarias();
            consultaDiaria.setVisible(true);
            setStatusTela(false);
        } else {
            consultaDiaria.setVisible(true);
        }
    }//GEN-LAST:event_jb_diariaActionPerformed

    private void jtf_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valorActionPerformed

    private void jrb_ativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_ativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_ativoActionPerformed

    private void jb_eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminar1ActionPerformed
        excluirCopia();
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_eliminar1ActionPerformed

    private void jtf_preco_custoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_preco_custoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_preco_custoActionPerformed

    private void jcb_tipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcb_tipoKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcb_producao.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_tipoKeyPressed

    private void jcb_producaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcb_producaoKeyPressed

        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcb_midia.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jcb_producaoKeyPressed

    private void jtf_duracaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_duracaoKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtf_censura.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_duracaoKeyPressed

    private void jcb_midiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcb_midiaKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcb_tipo_midia.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_midiaKeyPressed

    private void jcb_tipo_midiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcb_tipo_midiaKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jb_diaria.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_tipo_midiaKeyPressed

    private void jb_diariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_diariaKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (consultaDiaria == null) {
                consultaDiaria = new ConsultaDiariaObjeto();
                consultaDiaria.janelapai2 = this;
                consultaDiaria.listaTodasDiarias();
                consultaDiaria.setVisible(true);
                setStatusTela(false);
            } else {
                consultaDiaria.setVisible(true);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_diariaKeyPressed

    private void jb_generoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_generoKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (consultaGenero == null) {
                consultaGenero = new ConsultaGeneroObjeto();
                consultaGenero.janelapai2 = this;
                consultaGenero.listaTodasGeneros();
                consultaGenero.setVisible(true);
                setStatusTela(false);
            } else {
                consultaGenero.setVisible(true);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_generoKeyPressed

    private void jta_elencoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jta_elencoKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jta_sinopse.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jta_elencoKeyPressed

    private void jta_sinopseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jta_sinopseKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jb_salvar.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jta_sinopseKeyPressed

    private void jb_salvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_salvarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            atualizarObjeto();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarKeyPressed

    private void jcb_idiomaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcb_idiomaKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcb_legenda.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_idiomaKeyPressed

    private void jcb_legendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcb_legendaKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtf_data_aquisicao.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_legendaKeyPressed

    private void jtf_data_aquisicaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_data_aquisicaoFocusLost
        try {
            Data data = new Data();
            int idade;

            if (jtf_data_aquisicao.getText().trim().length() < 10) {
                jtf_data_aquisicao.setForeground(Color.red);
//                jtf_data_aquisicao.requestFocus();
            } else if (jtf_data_aquisicao.getText().equals("  /  /    ")) {
                jtf_data_aquisicao.setForeground(Color.red);
//                jtf_data_aquisicao.requestFocus();
            } else {
                if (validaData(jtf_data_aquisicao.getText())) {

                    jtf_data_aquisicao.setForeground(Color.black);

                } else {
                    jtf_data_aquisicao.setForeground(Color.red);
//                    jtf_data_aquisicao.requestFocus();
                }

            }
        } catch (ParseException ex) {
            jtf_data_aquisicao.setForeground(Color.red);
//            jtf_data_aquisicao.requestFocus();
        } catch (NumberFormatException ex) {
            jtf_data_aquisicao.setText("  /  /    ");
            jtf_data_aquisicao.setForeground(Color.red);
//            jtf_data_aquisicao.requestFocus();
        }
    }//GEN-LAST:event_jtf_data_aquisicaoFocusLost

    private void jtf_data_aquisicaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_data_aquisicaoKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtf_preco_custo.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_data_aquisicaoKeyPressed

    private void jtf_preco_custoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_preco_custoKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jb_adicionar_copia.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_preco_custoKeyPressed

    private void jb_adicionar_copiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_adicionar_copiaKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrarCopia();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_adicionar_copiaKeyPressed

    private void jtbl_copiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbl_copiaKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            excluirCopia();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbl_copiaKeyPressed

    private void jtf_preco_custoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_preco_custoFocusLost
        Moeda moeda = new Moeda();
        if (jtf_preco_custo.getText().equals("")) {
            jtf_preco_custo.setText("R$ 0,00");
        } else {
            jtf_preco_custo.setText(moeda.setPrecoFormat(String.valueOf(moeda.getPrecoFormato(jtf_preco_custo.getText()))));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_preco_custoFocusLost

    private void jtf_data_aquisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_data_aquisicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_data_aquisicaoActionPerformed

    private void jtf_preco_custoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_preco_custoFocusGained
        jtf_preco_custo.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_preco_custoFocusGained

    private void jtf_censuraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_censuraKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcb_tipo.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_censuraKeyPressed

    private void jb_adicionar_copiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_adicionar_copiaMouseClicked
        if (evt.getClickCount() == 1) {
            cadastrarCopia();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_adicionar_copiaMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jrb_ativoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrb_ativoKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_ativoKeyPressed

    private void jrb_inativoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrb_inativoKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_inativoKeyPressed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AtualizaObjeto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jb_adicionar_copia;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_diaria;
    private javax.swing.JButton jb_eliminar1;
    private javax.swing.JButton jb_genero;
    private javax.swing.JButton jb_salvar;
    public static javax.swing.JComboBox jcb_idioma;
    public static javax.swing.JComboBox jcb_legenda;
    public static javax.swing.JComboBox jcb_midia;
    public static javax.swing.JComboBox jcb_producao;
    public static javax.swing.JComboBox jcb_tipo;
    public static javax.swing.JComboBox jcb_tipo_midia;
    public static javax.swing.JRadioButton jrb_ativo;
    public static javax.swing.JRadioButton jrb_inativo;
    public static javax.swing.JTextArea jta_elenco;
    public static javax.swing.JTextArea jta_sinopse;
    public static javax.swing.JTable jtbl_copia;
    private javax.swing.JFormattedTextField jtf_censura;
    public static javax.swing.JTextField jtf_codigo_objeto;
    public static javax.swing.JFormattedTextField jtf_data_aquisicao;
    private javax.swing.JTextField jtf_descricao_diaria;
    public static javax.swing.JTextField jtf_descricao_genero;
    public static javax.swing.JTextField jtf_diaria_dias;
    public static javax.swing.JTextField jtf_duracao;
    public static javax.swing.JTextField jtf_preco_custo;
    public static javax.swing.JTextField jtf_titulo;
    public static javax.swing.JTextField jtf_titulo_original;
    public static javax.swing.JTextField jtf_valor;
    private javax.swing.JTabbedPane jtp_menu;
    private javax.swing.JTextArea tfa_similar;
    // End of variables declaration//GEN-END:variables

    public void setTela(String permissao) {
        if (permissao.equals("usuario")) {
        } else {
        }
    }

    public boolean verificaCadastro(String descricao_objeto) {
        if (descricao_objeto.equals("")) {
        } else {
            pool = new Pool();
            ObjetoDAO objetoDAO = new ObjetoDAO(pool);
            objeto = null;
//            objeto = objetoDAO.getObjeto_cpf(descricao_objeto, Integer.parseInt(jtf_codigo_objeto.getText()));
            if (null != objeto) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "CPF já existente");
                return false;
            }
        }
        return false;
    }

    public boolean verificarCampos() {
        String msgERRO = "Preencha os campos obrigatórios:\n";

        if (jtf_titulo.getText().trim().equals("")) {
            msgERRO = msgERRO + " *Descrição\n";
        }

        if (jtf_titulo_original.getText().trim().equals("")) {
            msgERRO = msgERRO + " *Título Original\n";
        }

        if (jtf_duracao.getText().trim().equals("")) {
            msgERRO = msgERRO + " *Duração\n";
        }

        if (jtf_diaria_dias.getText().trim().equals("")) {
            msgERRO = msgERRO + " *Diária\n";
        }

        if (jtf_descricao_genero.getText().trim().equals("")) {
            msgERRO = msgERRO + " *Gênero\n";
        }

        if (jtf_censura.getText().trim().equals("")) {
            msgERRO = msgERRO + " *Censura\n";
        }

        if (!msgERRO.equals("Preencha os campos obrigatórios:\n")) {
            JOptionPane.showMessageDialog(this, msgERRO);
            jtf_titulo.requestFocus();
            return false;
        } else {
            return true;
        }

    }

    public void setStatusTela(boolean status) {
        if (status) {
            this.setVisible(status);
        }
        this.setEnabled(status);
    }

    public void removeObjeto(JTable tb) {
        if (tb != null) {
            DefaultTableModel row = (DefaultTableModel) jtbl_telefone.getModel();
            if (tb.getSelectedRow() != -1) {
                int selectedOption = JOptionPane.showConfirmDialog(this, "Deseja excluir ?", "Atenção", JOptionPane.YES_NO_OPTION);
                if (selectedOption == JOptionPane.YES_NO_OPTION) {
                    row.removeRow(tb.getSelectedRow());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione um produto");
            }
        }
    }

    public void carregaCopia(Integer codigo_objeto) {
        try {
            if (codigo_objeto != null) {
                pool = new Pool();
                CopiaDAO copiaDAO = new CopiaDAO(pool);
                copias = null;
                copias = copiaDAO.getCopia_codigo_objeto(codigo_objeto, 1, "");
                if (copias != null && copias.size() > 0) {
                    DefaultTableModel tableModel = (DefaultTableModel) jtbl_copia.getModel();
                    tableModel.setNumRows(0);
                    for (int i = 0; i < copias.size(); i++) {
                        String preco_custo;

                        preco_custo = String.valueOf(copias.get(i).getPreco_custo());
                        Moeda moeda = new Moeda();
                        preco_custo = moeda.setPrecoFormat(preco_custo);

                        SimpleDateFormat in = new SimpleDateFormat("yyyy-MM-dd");
                        SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
                        String data_aquisicao = out.format(in.parse(copias.get(i).getData_aquisicao().toString()));

                        DefaultTableModel row = (DefaultTableModel) jtbl_copia.getModel();
                        ItemDbGrid hashDbGrid = new ItemDbGrid(copias.get(i), copias.get(i).getCodigo_barras());
                        row.addRow(new Object[]{copias.get(i).getCodigo_copia(), copias.get(i).getNumero_copia(),
                            hashDbGrid, copias.get(i).getIdioma(), copias.get(i).getLegenda(), preco_custo, data_aquisicao});

                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(AtualizaObjeto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(AtualizaObjeto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void carregaDiaria(Diaria objdiaria) {
        if (objdiaria != null) {

            diaria = new Diaria();
            AtualizaObjeto.diaria = objdiaria;

            System.out.println("4 - Diária alterar código: " + diaria.getCodigo_diaria());
            System.out.println("4 - Diária alterar descrição: " + diaria.getNome_diaria());

            jtf_diaria_dias.setText(String.valueOf(diaria.getDias()));
            jtf_descricao_diaria.setText(diaria.getNome_diaria());
            String valor;

            Moeda moeda = new Moeda();
            valor = moeda.setPrecoFormat(String.valueOf(diaria.getValor()));

            jtf_valor.setText(valor);

            jb_genero.requestFocus();

        } else {
            JOptionPane.showMessageDialog(null, "Objeto diária nulo");
        }
    }

    public void carregaGenero(Genero genero) {
        if (genero != null) {
            AtualizaObjeto.genero = new Genero();
            AtualizaObjeto.genero = genero;
            jtf_descricao_genero.setText(genero.getNome_genero());

            jtp_menu.setSelectedIndex(1);
            jta_elenco.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Objeto gênero nulo");
        }

    }

    public boolean verificarCamposCopia() {
        String msgERRO = "Preencha os campos obrigatórios:\n";

        try {
            Data data = new Data();
            int idade;

            if (jtf_data_aquisicao.getText().trim().length() != 10) {
                jtf_data_aquisicao.setForeground(Color.red);
                msgERRO = msgERRO + " *Data de Aquisição inválida\n";
            } else if (jtf_data_aquisicao.getText().equals("  /  /    ")) {
                jtf_data_aquisicao.setForeground(Color.red);
                msgERRO = msgERRO + " *Data de Aquisição inválida\n";
            } else {
                if (validaData(jtf_data_aquisicao.getText())) {
                    jtf_data_aquisicao.setForeground(Color.black);
                } else {
                    jtf_data_aquisicao.setForeground(Color.red);
                    msgERRO = msgERRO + " *Data de Aquisição inválida\n";
                }

            }
        } catch (ParseException ex) {
            jtf_data_aquisicao.setForeground(Color.red);
            msgERRO = msgERRO + " *Data de Aquisição inválida\n";
        } catch (NumberFormatException ex) {
            jtf_data_aquisicao.setText("  /  /    ");
            jtf_data_aquisicao.setForeground(Color.red);
            msgERRO = msgERRO + " *Data de Aquisição inválida\n";
        }

//        if (jtf_data_aquisicao.getForeground().equals(Color.RED) || jtf_data_aquisicao.getText().trim().length() != 10) {
//            System.out.println("Tamanho data_aquisicao: "+jtf_data_aquisicao.getText().trim().length());
//            msgERRO = msgERRO + " *Data de Aquisição inválida\n";
//        }
        if (!msgERRO.equals("Preencha os campos obrigatórios:\n")) {
            JOptionPane.showMessageDialog(this, msgERRO);

            jtf_data_aquisicao.requestFocus();

            return false;
        } else {
            return true;
        }

    }

    public static Diaria getObjetoDiaria() {
        return diaria;
    }

    public static Genero getObjetoGenero() {
        return genero;
    }

    private void excluirCopia() {
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.MenuObjeto");

        try {
            if (acesso.getDeletar() == 0) {
                DefaultTableModel row = (DefaultTableModel) jtbl_copia.getModel();
                if (jtbl_copia.getSelectedRow() != -1) {
                    int selectedOption = JOptionPane.showConfirmDialog(this, "Deseja excluir ?", "Atenção", JOptionPane.YES_NO_OPTION);
                    if (selectedOption == JOptionPane.YES_NO_OPTION) {
                        pool = new Pool();
                        CopiaDAO copiaDAO = new CopiaDAO(pool);
                        copia = new Copia();
                        copia.setCodigo_copia((Integer) jtbl_copia.getValueAt(jtbl_copia.getSelectedRow(), 0));

                        try {
                            copiaDAO.excluir(copia.getCodigo_copia());
                            row.removeRow(jtbl_copia.getSelectedRow());
                            jtbl_copia.requestFocus();
                            jtbl_copia.setSelectionMode(1);
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(null, "Este registro não pode ser excluído pois está referenciado em outra tabela");
                        }

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Selecione uma cópia");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
        }
    }

    public void acionarAtalho(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            atualizarObjeto();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            retornaJanelaPai();
        }
    }

    public static boolean validaData(String dataString) throws java.text.ParseException {

        if (!dataString.equals("")) {

            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            Calendar cal = new GregorianCalendar();
            Date dataDigitada = new Date(df.parse(dataString).getTime());
            Date dataAtual = new Date(System.currentTimeMillis());

            // gerando o calendar
            cal.setTime(df.parse(dataString));

            // separando os dados da string para comparacao e validacao
            String[] data = dataString.split("/");
            String dia = data[0];
            String mes = data[1];
            String ano = data[2];

            // testando se hah discrepancia entre a data que foi
            // inserida no caledar e a data que foi passada como
            // string. se houver diferenca, a data passada era
            // invalida
            if ((new Integer(dia)).intValue() != (new Integer(cal.get(Calendar.DAY_OF_MONTH))).intValue()) {
                // dia nao casou
                return (false);
            }
            if ((new Integer(mes)).intValue() != (new Integer(cal.get(Calendar.MONTH) + 1)).intValue()) {
                // mes nao casou

                return (false);
            }
            if ((new Integer(ano)).intValue() != (new Integer(cal.get(Calendar.YEAR))).intValue()) {
                // ano nao casou

                return (false);
            }
            if (dataDigitada.after(dataAtual)) {
                // data maior que atual
                return (false);
            }
            return (true);
        }
        return false;
    }

    private void retornaJanelaPai() {
        setVisible(false);
        if (janelapai != null) {
            janelapai.setStatusTela(true);
            janelapai.jtf_consulta.requestFocus();
            janelapai.atualizaObjeto = null;
            janelapai.buscarDados();
        }
    }

    public void atualizarObjeto() {

        try {

            if (verificarCampos()) {

                pool = new Pool();
                ObjetoDAO objetoDAO = new ObjetoDAO(pool);
                Objeto objeto = new Objeto();
                if (!jtf_codigo_objeto.getText().isEmpty()) {

                    objeto.setTitulo(jtf_titulo.getText().trim());
                    objeto.setTitulo_original(jtf_titulo_original.getText().trim());
                    objeto.setTipo_movimento((String) jcb_tipo.getSelectedItem());
                    objeto.setProducao((String) jcb_producao.getSelectedItem());
                    objeto.setDuracao(jtf_duracao.getText().trim());
                    objeto.setMidia((String) jcb_midia.getSelectedItem());
                    objeto.setTipo_midia((String) jcb_tipo_midia.getSelectedItem());
                    objeto.setGenero(getObjetoGenero());
                    objeto.setDiaria(getObjetoDiaria());
                    if (jta_elenco.getText().length() > 1000) {
                        objeto.setElenco(jta_elenco.getText().substring(0, 1000));
                    } else {
                        objeto.setElenco(jta_elenco.getText().trim());
                    }
                    if (jta_sinopse.getText().length() > 1000) {
                        objeto.setSinopse(jta_sinopse.getText().substring(0, 1000));
                    } else {
                        objeto.setSinopse(jta_sinopse.getText().trim());
                    }
                    objeto.setCensura(Integer.parseInt(jtf_censura.getText()));
                    if (jrb_ativo.isSelected() == true) {
                        objeto.setStatus("0");
                    } else {
                        objeto.setStatus("1");
                    }

                    objeto.setCodigo_objeto(Integer.parseInt(jtf_codigo_objeto.getText()));
                    objetoDAO.atualizar(objeto);
                    JOptionPane.showMessageDialog(null, "Atualizado com Sucesso!");

                }
                jtp_menu.setSelectedIndex(2);
                jcb_idioma.requestFocus();
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage() + "Problemas com a gravação: ");

            e.printStackTrace();
        } catch (NumberFormatException e) {
            System.out.println("Valor inválido: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Valor inválido: " + e.getMessage());
            e.printStackTrace();
        }
    }

    public void cadastrarCopia() {
        try {
            if (jtf_codigo_objeto.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Salvar primeiro o Objeto");
            } else {
                if (verificarCamposCopia() == true) {

                    Moeda moeda = new Moeda();
                    Copia copia = new Copia();
                    Objeto objeto = new Objeto();

                    objeto.setCodigo_objeto(Integer.parseInt(jtf_codigo_objeto.getText()));
                    System.out.println("Código do Objeto: " + Integer.parseInt(jtf_codigo_objeto.getText()));
                    copia.setObjeto(objeto);

                    copia.setIdioma((String) jcb_idioma.getSelectedItem());
                    copia.setLegenda((String) jcb_legenda.getSelectedItem());
                    copia.setPreco_custo(moeda.getPrecoFormato((String) jtf_preco_custo.getText()));
                    pool = new Pool();
                    CopiaDAO copiaDAO = new CopiaDAO(pool);

                    copia.setData_aquisicao(new SimpleDateFormat("dd/MM/yyyy").parse((String) jtf_data_aquisicao.getText()));
                    copiaDAO.salvar(copia);
                    carregaCopia(objeto.getCodigo_objeto());

                    jtf_data_aquisicao.setText("");
                    jtf_preco_custo.setText("R$ 0,00");
                    jcb_idioma.requestFocus();
                }
            }

        } catch (NumberFormatException e) {
            System.out.println("Valor inválido: " + e.getMessage());

            e.printStackTrace();
        } catch (Exception ex) {

        }

    }
}
