package br.com.locadora.view;

import br.com.locadora.conexao.InterfacePool;
import br.com.locadora.conexao.Pool;
import br.com.locadora.model.bean.AcessoUsuario;
import br.com.locadora.model.bean.Diaria;
import br.com.locadora.model.bean.ItemPacotePromocional;
import br.com.locadora.model.bean.PacotePromocional;
import br.com.locadora.model.dao.PacotePromocionalDAO;
import br.com.locadora.util.LimitadorTexto;
import br.com.locadora.util.Moeda;
import br.com.locadora.util.TemaInterface;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALENCAR
 */
public final class CadastraAlteraPacotePromocional extends javax.swing.JFrame {

    private PacotePromocional pacotePromocional;
    private List<ItemPacotePromocional> itensPacotePromocional;
    private ItemPacotePromocional itemPacotePromocional;
    public MenuPacotePromocional janelapai;
    public ConsultaDiaria janelapai2;    
    private InterfacePool pool;     
    public String action;
    public AcessoUsuario acesso;
    public Moeda moeda;
    public Diaria diaria;
    public PacotePromocionalDAO pacotePromocionalDAO;
    public ConsultaDiaria consultaDiaria;

    /**
     * Creates new form ProdutoCadastroGUI
     */
    public CadastraAlteraPacotePromocional() {
        initComponents();
        TemaInterface.getInterface(this);
        janelapai = null;
        janelapai2 = null;        
        consultaDiaria = null;    
        this.setTitle("Cadastrando Pacote Promocional");
    }

    public CadastraAlteraPacotePromocional(PacotePromocional pacotePromocional) {
        initComponents();
        this.setTitle("Alterando Pacote Promocional");
        if (pacotePromocional != null) {
            TemaInterface.getInterface(this);
            janelapai = null;
            janelapai2 = null;
            consultaDiaria = null;
            this.pacotePromocional = pacotePromocional;
            moeda = new Moeda();
            jtf_codigo_pacote_promocional.setText(pacotePromocional.getCodigo_pacote_promocioanl().toString());
            jtf_descricao_pacote.setText(pacotePromocional.getDescricao());
            jtf_quantidade_vez.setText(pacotePromocional.getQuantidade_vez().toString());
            
            if(pacotePromocional.getQuantidade_mes().equals(1)){
                jcb_quantidade_mes.setSelectedIndex(0);                
            } else if(pacotePromocional.getQuantidade_mes().equals(2)){
                jcb_quantidade_mes.setSelectedIndex(1);                
            } else if(pacotePromocional.getQuantidade_mes().equals(3)){
                jcb_quantidade_mes.setSelectedIndex(2);                
            } else if(pacotePromocional.getQuantidade_mes().equals(6)){
                jcb_quantidade_mes.setSelectedIndex(3);                
            } else if(pacotePromocional.getQuantidade_mes().equals(12)){
                jcb_quantidade_mes.setSelectedIndex(4);                
            }
            jtf_valor.setText(moeda.setPrecoFormat(pacotePromocional.getValor().toString()));
            
            System.out.println("Status: " + pacotePromocional.getStatus());
            if (pacotePromocional.getStatus() == true) {
                jrb_ativo.setSelected(true);
            } else {
                jrb_inativo.setSelected(true);
            }
            carregarItensPacotePromocional(pacotePromocional.getCodigo_pacote_promocioanl());            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tfa_similar = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jb_cancelar = new javax.swing.JButton();
        jb_salvar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jtf_codigo_pacote_promocional = new javax.swing.JTextField();
        jtf_descricao_pacote = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jrb_ativo = new javax.swing.JRadioButton();
        jrb_inativo = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jb_adicionar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtbl_diarias_pacote = new javax.swing.JTable();
        jLabel41 = new javax.swing.JLabel();
        jtf_descricao_diaria = new javax.swing.JTextField();
        jb_pesquisa_diaria = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtf_valor = new javax.swing.JTextField(new LimitadorTexto(10), "",10);
        jcb_quantidade_mes = new javax.swing.JComboBox();
        jtf_quantidade_vez = new javax.swing.JFormattedTextField();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tfa_similar.setColumns(20);
        tfa_similar.setRows(5);
        tfa_similar.setName("tfa_similar"); // NOI18N
        jScrollPane1.setViewportView(tfa_similar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterando Cliente");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jb_cancelar.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/sair.png"))); // NOI18N
        jb_cancelar.setText("Sair");
        jb_cancelar.setMaximumSize(new java.awt.Dimension(101, 33));
        jb_cancelar.setName("jb_cancelar"); // NOI18N
        jb_cancelar.setPreferredSize(new java.awt.Dimension(100, 40));
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });

        jb_salvar.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jb_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/save.png"))); // NOI18N
        jb_salvar.setText("Salvar");
        jb_salvar.setName("jb_salvar"); // NOI18N
        jb_salvar.setPreferredSize(new java.awt.Dimension(100, 40));
        jb_salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salvarMouseClicked(evt);
            }
        });
        jb_salvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_salvarKeyPressed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pacote Promocional "));
        jPanel3.setName("jPanel3"); // NOI18N

        jtf_codigo_pacote_promocional.setEditable(false);
        jtf_codigo_pacote_promocional.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_codigo_pacote_promocional.setName("jtf_codigo_pacote_promocional"); // NOI18N

        jtf_descricao_pacote.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_descricao_pacote.setName("jtf_descricao_pacote"); // NOI18N
        jtf_descricao_pacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_descricao_pacoteActionPerformed(evt);
            }
        });
        jtf_descricao_pacote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_descricao_pacoteKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel1.setText("Código Pacote");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel3.setText("Descrição* ");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel12.setText("Qtd/Mês*");
        jLabel12.setName("jLabel12"); // NOI18N

        buttonGroup1.add(jrb_ativo);
        jrb_ativo.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jrb_ativo.setSelected(true);
        jrb_ativo.setText("Ativo");
        jrb_ativo.setName("jrb_ativo"); // NOI18N
        jrb_ativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_ativoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrb_inativo);
        jrb_inativo.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jrb_inativo.setText("Inativo");
        jrb_inativo.setName("jrb_inativo"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel18.setText("Tempo*");
        jLabel18.setName("jLabel18"); // NOI18N

        jb_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/adicionar_item.png"))); // NOI18N
        jb_adicionar.setToolTipText("Incluir");
        jb_adicionar.setName("jb_adicionar"); // NOI18N
        jb_adicionar.setPreferredSize(new java.awt.Dimension(28, 28));
        jb_adicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_adicionarMouseClicked(evt);
            }
        });
        jb_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_adicionarActionPerformed(evt);
            }
        });
        jb_adicionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_adicionarKeyPressed(evt);
            }
        });

        jb_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/remove_item.png"))); // NOI18N
        jb_eliminar.setToolTipText("Excluir");
        jb_eliminar.setName("jb_eliminar"); // NOI18N
        jb_eliminar.setPreferredSize(new java.awt.Dimension(28, 28));
        jb_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarActionPerformed(evt);
            }
        });

        jScrollPane6.setName("jScrollPane6"); // NOI18N

        jtbl_diarias_pacote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição Diária"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_diarias_pacote.setName("jtbl_diarias_pacote"); // NOI18N
        jtbl_diarias_pacote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_diarias_pacoteMouseClicked(evt);
            }
        });
        jtbl_diarias_pacote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbl_diarias_pacoteKeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(jtbl_diarias_pacote);
        if (jtbl_diarias_pacote.getColumnModel().getColumnCount() > 0) {
            jtbl_diarias_pacote.getColumnModel().getColumn(0).setPreferredWidth(300);
        }

        jLabel41.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel41.setText("Diária");
        jLabel41.setName("jLabel41"); // NOI18N

        jtf_descricao_diaria.setEditable(false);
        jtf_descricao_diaria.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_descricao_diaria.setName("jtf_descricao_diaria"); // NOI18N
        jtf_descricao_diaria.setPreferredSize(new java.awt.Dimension(300, 29));
        jtf_descricao_diaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_descricao_diariaActionPerformed(evt);
            }
        });

        jb_pesquisa_diaria.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jb_pesquisa_diaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/pesquisar.png"))); // NOI18N
        jb_pesquisa_diaria.setName("jb_pesquisa_diaria"); // NOI18N
        jb_pesquisa_diaria.setPreferredSize(new java.awt.Dimension(28, 28));
        jb_pesquisa_diaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_pesquisa_diariaActionPerformed(evt);
            }
        });
        jb_pesquisa_diaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_pesquisa_diariaKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel4.setText("Valor*");
        jLabel4.setName("jLabel4"); // NOI18N

        jtf_valor.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_valor.setText("R$ 0,00");
        jtf_valor.setName("jtf_valor"); // NOI18N
        jtf_valor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_valorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_valorFocusLost(evt);
            }
        });
        jtf_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_valorKeyPressed(evt);
            }
        });

        jcb_quantidade_mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 Mês", "2 Meses", "3 Meses", "6 Meses", "1 Ano" }));
        jcb_quantidade_mes.setName("jcb_quantidade_mes"); // NOI18N
        jcb_quantidade_mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcb_quantidade_mesKeyPressed(evt);
            }
        });

        jtf_quantidade_vez.addKeyListener(new java.awt.event.KeyAdapter() {     // cria um listener ouvinte de digitação do fieldNumero

            public void keyReleased(java.awt.event.KeyEvent evt) {  // cria um ouvinte para cada tecla pressionada

                jtf_quantidade_vez.setText(jtf_quantidade_vez.getText().replaceAll("[^0-9]", "")); // faz com que pegue o texto a cada tecla digitada, e substituir tudo que não(^) seja numero  por ""

            }
        });
        jtf_quantidade_vez.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_quantidade_vez.setName("jtf_quantidade_vez"); // NOI18N
        jtf_quantidade_vez.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_quantidade_vezKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(0, 0, 0))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_quantidade_vez, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jcb_quantidade_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(188, 188, 188)
                                .addComponent(jrb_ativo)
                                .addGap(0, 0, 0)
                                .addComponent(jrb_inativo))
                            .addComponent(jtf_descricao_pacote, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_codigo_pacote_promocional, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jtf_descricao_diaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_pesquisa_diaria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_ativo)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jLabel1)
                                .addGap(0, 0, 0)
                                .addComponent(jtf_codigo_pacote_promocional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel3)
                                .addGap(0, 0, 0)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jtf_descricao_pacote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel18))
                                        .addGap(0, 0, 0)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jtf_quantidade_vez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcb_quantidade_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, 0)
                                        .addComponent(jtf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, 0)
                                .addComponent(jLabel41))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jrb_inativo)
                                .addGap(0, 0, 0)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_descricao_diaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_pesquisa_diaria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jb_cancelar, jb_salvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        retornaJanelaPai();
}//GEN-LAST:event_jb_cancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jtf_descricao_pacote.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        retornaJanelaPai();
    }//GEN-LAST:event_formWindowClosed

    private void jtf_descricao_pacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_descricao_pacoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descricao_pacoteActionPerformed

    private void jtf_descricao_pacoteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_descricao_pacoteKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtf_quantidade_vez.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descricao_pacoteKeyPressed

    private void jrb_ativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_ativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_ativoActionPerformed

    private void jb_salvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_salvarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrarAlterarPacotePromocional();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarKeyPressed

    private void jb_salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salvarMouseClicked
        if (evt.getClickCount() == 1) {
            cadastrarAlterarPacotePromocional();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jtf_quantidade_vezKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_quantidade_vezKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcb_quantidade_mes.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_quantidade_vezKeyPressed

    private void jb_adicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_adicionarMouseClicked
        if (evt.getClickCount() == 1) {
            carregarItensPacotePromocional(HIDE_ON_CLOSE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_adicionarMouseClicked

    private void jb_adicionarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_adicionarKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            adicionarItemPacotePromocional();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_adicionarKeyPressed

    private void jb_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarActionPerformed
        removeItemPacotePromocional(jtbl_diarias_pacote);
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_eliminarActionPerformed

    private void jtbl_diarias_pacoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_diarias_pacoteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbl_diarias_pacoteMouseClicked

    private void jtbl_diarias_pacoteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbl_diarias_pacoteKeyPressed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbl_diarias_pacoteKeyPressed

    private void jb_pesquisa_diariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_pesquisa_diariaActionPerformed
        if (consultaDiaria == null) {
            consultaDiaria = new ConsultaDiaria();
            consultaDiaria.janelapai2 = this;
            consultaDiaria.listaTodasDiarias();
            consultaDiaria.setVisible(true);
            setStatusTela(false);
        } else {
            consultaDiaria.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_pesquisa_diariaActionPerformed

    private void jb_pesquisa_diariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_pesquisa_diariaKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (consultaDiaria == null) {
                consultaDiaria = new ConsultaDiaria();
                consultaDiaria.janelapai2 = this;
                consultaDiaria.listaTodasDiarias();
                consultaDiaria.setVisible(true);
                setStatusTela(false);
            } else {
                consultaDiaria.setVisible(true);
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_pesquisa_diariaKeyPressed

    private void jtf_valorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_valorFocusGained
        jtf_valor.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valorFocusGained

    private void jtf_valorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_valorFocusLost
        if (jtf_valor.getText().equals("")) {
            jtf_valor.setText("R$ 0,00");
        } else {
            moeda = new Moeda();
            jtf_valor.setText(moeda.setPrecoFormat(jtf_valor.getText()));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valorFocusLost

    private void jtf_valorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_valorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jb_salvar.requestFocus();
        }
        acionarAtalho(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valorKeyPressed

    private void jcb_quantidade_mesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcb_quantidade_mesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtf_valor.requestFocus();
        }
        acionarAtalho(evt);           
// TODO add your handling code here:
    }//GEN-LAST:event_jcb_quantidade_mesKeyPressed

    private void jb_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_adicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_adicionarActionPerformed

    private void jtf_descricao_diariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_descricao_diariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descricao_diariaActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadastraAlteraPacotePromocional().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jb_adicionar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_pesquisa_diaria;
    private javax.swing.JButton jb_salvar;
    private javax.swing.JComboBox jcb_quantidade_mes;
    public static javax.swing.JRadioButton jrb_ativo;
    public static javax.swing.JRadioButton jrb_inativo;
    public static javax.swing.JTable jtbl_diarias_pacote;
    public static javax.swing.JTextField jtf_codigo_pacote_promocional;
    private javax.swing.JTextField jtf_descricao_diaria;
    public static javax.swing.JTextField jtf_descricao_pacote;
    private javax.swing.JFormattedTextField jtf_quantidade_vez;
    public static javax.swing.JTextField jtf_valor;
    private javax.swing.JTextArea tfa_similar;
    // End of variables declaration//GEN-END:variables
    
    public boolean verificarCampos() {
        String msgERRO = "Preencha os campos obrigatórios:\n";

        if (jtf_descricao_pacote.getText().trim().equals("")) {
            msgERRO = msgERRO + " *Descrição\n";
        }
        if (jtf_quantidade_vez.getText().length() == 0) {
            msgERRO = msgERRO + " *Quantidade por Mês\n";
        } 

        if (jtf_valor.getText().length() < 1) {
            msgERRO = msgERRO + " *Valor do Pacote Promocional\n";
        }         

        if (!msgERRO.equals("Preencha os campos obrigatórios:\n")) {
            JOptionPane.showMessageDialog(this, msgERRO);
            jtf_descricao_pacote.requestFocus();
            return false;
        } else {
            return true;
        }

    }

    public void setStatusTela(boolean status) {
        if (status) {
            this.setVisible(status);
        }
        this.setEnabled(status);
    }

    public boolean verificarCampoDiaria() {
        String msgERRO = "Preencha os campos obrigatórios:\n";

        if (jtf_descricao_diaria.getText().equals("")) {
            msgERRO = msgERRO + " *Diária\n";
        }

        if (!msgERRO.equals("Preencha os campos obrigatórios:\n")) {
            JOptionPane.showMessageDialog(this, msgERRO);
            jb_pesquisa_diaria.requestFocus();
            return false;
        } else {
            return true;
        }
    }
    
    public void carregaDiaria(Diaria diaria) {
        if (diaria != null) {
            this.diaria = diaria;
            jtf_descricao_diaria.setText(diaria.getNome_diaria());
            moeda = new Moeda();
            jb_adicionar.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Objeto diária nulo");
        }
    }

    public void carregarItensPacotePromocional(Integer codigo_pacote_promocional) {
        try {
            if (codigo_pacote_promocional != null) {
                pool = new Pool();
                itensPacotePromocional = null;
                pacotePromocionalDAO = new PacotePromocionalDAO(pool);
                itensPacotePromocional = pacotePromocionalDAO.getItensPacotePromocional(codigo_pacote_promocional);

                mostrarItensPacotePromocional(itensPacotePromocional);
            }
        } catch (ParseException ex) {
            Logger.getLogger(CadastraAlteraPacotePromocional.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CadastraAlteraPacotePromocional.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    

    public void mostrarItensPacotePromocional(List<ItemPacotePromocional> itensPacotePromocional) throws ParseException {
        DefaultTableModel tableModel = (DefaultTableModel) jtbl_diarias_pacote.getModel();
        tableModel.setNumRows(0);

        if (itensPacotePromocional != null) {
            moeda = new Moeda();
            for (int i = 0; i < itensPacotePromocional.size(); i++) {
                DefaultTableModel row = (DefaultTableModel) jtbl_diarias_pacote.getModel();                
                row.addRow(new Object[]{itensPacotePromocional.get(i).getDiaria().getNome_diaria()});
            }

        }
    }

    public void acionarAtalho(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            cadastrarAlterarPacotePromocional();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            retornaJanelaPai();
        }
    }

    private void adicionarItemPacotePromocional() {
        try {            
            if (!jtf_codigo_pacote_promocional.getText().equals("")) {
                if (verificarCampoDiaria() == true) {
                    pacotePromocional = new PacotePromocional();
                    pacotePromocional.setCodigo_pacote_promocioanl(Integer.parseInt(jtf_codigo_pacote_promocional.getText()));
                    
                    itemPacotePromocional = new ItemPacotePromocional();
                    itemPacotePromocional.setPacotePromocional(pacotePromocional);
                    itemPacotePromocional.setDiaria(diaria);
                    
                    pool = new Pool();
                    pacotePromocionalDAO = new PacotePromocionalDAO(pool);
                    pacotePromocionalDAO.salvarItem(itemPacotePromocional);                    

                    carregarItensPacotePromocional(pacotePromocional.getCodigo_pacote_promocioanl());
                    
                    jtf_descricao_diaria.setText("");                    
                    jb_pesquisa_diaria.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Salvar primeiro o Pacote Promocional");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }
    }   
    
    public void removeItemPacotePromocional(JTable tb) {
        if (tb != null) {
            DefaultTableModel row = (DefaultTableModel) tb.getModel();

            if (tb.getSelectedRow() != -1) {
                int selectedOption = JOptionPane.showConfirmDialog(this, "Deseja excluir ?", "Atenção", JOptionPane.YES_NO_OPTION);
                if (selectedOption == JOptionPane.YES_NO_OPTION) {
                    pool = new Pool();
                    pacotePromocionalDAO = new PacotePromocionalDAO(pool);
                    
                    if (pacotePromocionalDAO.excluirItem(itensPacotePromocional.get(tb.getSelectedRow()).getCodigo_item_pacote_promocional())) {
                        row.removeRow(tb.getSelectedRow());
                        carregarItensPacotePromocional(Integer.parseInt(jtf_codigo_pacote_promocional.getText()));
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione um Dependente");
            }
        }
    }    
    
    public void cadastrarAlterarPacotePromocional() {
        if (verificarCampos()) {
            try {
                pacotePromocional = new PacotePromocional();
                pacotePromocional.setDescricao(jtf_descricao_pacote.getText());
                pacotePromocional.setQuantidade_vez(Integer.parseInt(jtf_quantidade_vez.getText()));
                if(jcb_quantidade_mes.getSelectedIndex() == 0){
                    pacotePromocional.setQuantidade_mes(1);
                } else if(jcb_quantidade_mes.getSelectedIndex() == 1){
                    pacotePromocional.setQuantidade_mes(2);
                } else if(jcb_quantidade_mes.getSelectedIndex() == 2){
                    pacotePromocional.setQuantidade_mes(3);
                } else if(jcb_quantidade_mes.getSelectedIndex() == 3){
                    pacotePromocional.setQuantidade_mes(6);
                } else if(jcb_quantidade_mes.getSelectedIndex() == 4){
                    pacotePromocional.setQuantidade_mes(12);
                }
                moeda = new Moeda();
                pacotePromocional.setValor(moeda.getPrecoFormato(jtf_valor.getText()));
                if (jrb_ativo.isSelected() == true) {
                    pacotePromocional.setStatus(true);
                } else {
                    pacotePromocional.setStatus(false);
                }                
                pool = new Pool();
                pacotePromocionalDAO = new PacotePromocionalDAO(pool);
                if (jtf_codigo_pacote_promocional.getText().equals("")) {
                    pacotePromocional = pacotePromocionalDAO.salvar(pacotePromocional);
                    jtf_codigo_pacote_promocional.setText(pacotePromocional.getCodigo_pacote_promocioanl().toString());
                    JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso!");                    
                } else {                    
                    pacotePromocional.setCodigo_pacote_promocioanl(Integer.parseInt(jtf_codigo_pacote_promocional.getText()));
                    pacotePromocionalDAO.atualizar(pacotePromocional);
                    JOptionPane.showMessageDialog(null, "Atualizado com sucesso.");                    
                }                
                    jb_pesquisa_diaria.requestFocus();

            } catch (SQLException e) {
                System.out.println(e.getMessage() + "Problemas com a gravação: ");

                e.printStackTrace();
            } catch (NumberFormatException e) {
                System.out.println("Valor inválido: " + e.getMessage());

                e.printStackTrace();
            }

        }
    }

    private void retornaJanelaPai() {
        setVisible(false);
        if (janelapai != null) {
            janelapai.setStatusTela(true);
            janelapai.cadastraAlteraPacotePromocional = null;
            janelapai.consultarPacotePromocional();
        } else if (janelapai2 != null) {
            janelapai2.setStatusTela(true);            
        }
    }    
    
}
