package br.com.locadora.view;

import br.com.locadora.conexao.InterfacePool;
import br.com.locadora.controller.SiscomController;
import br.com.locadora.model.dao.ProdutoDAO;
import br.com.locadora.model.bean.Cliente;
import br.com.locadora.model.bean.Dependente;
import br.com.locadora.model.bean.Produto;
import br.com.locadora.model.bean.Telefone;
import br.com.locadora.util.ItemDbGrid;
import br.com.locadora.util.LimitadorTexto;
import br.com.locadora.util.UnaccentedDocument;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALENCAR
 */
public final class CadastroCliente extends javax.swing.JFrame {

    private TelaPrincipal janela;
    public List<Produto> produtos;
    public MenuCliente janelaPaim;

    /**
     * Creates new form ProdutoCadastroGUI
     */
    public CadastroCliente() throws SQLException {
        initComponents();
        janelapai = null;
        janelapai2 = null;

    }

    public MenuCliente janelapai;
    public ProdutoConsultarGUI janelapai2;

    //public ProdutoConsultarGUI janelapaim;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tfa_similar = new javax.swing.JTextArea();
        jb_cancelar = new javax.swing.JButton();
        jb_salvar = new javax.swing.JButton();
        jtf_codigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtf_empresa = new javax.swing.JTextField(new LimitadorTexto(45), "",10);
        jtf_nome_cliente = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_cpf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtf_profissao = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtf_data_nascimento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtf_endereco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtf_bairro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtf_complemento = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtf_email = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jrb_ativo = new javax.swing.JRadioButton();
        jrb_inativo = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_observacao = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jtf_telefone = new javax.swing.JTextField();
        jb_adicionar_telefone = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbl_telefone = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jtf_dependente = new javax.swing.JTextField();
        jb_adicionar_dependente = new javax.swing.JButton();
        jb_eliminar1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtbl_dependente = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jtf_estado = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jtf_cidade = new javax.swing.JTextField();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tfa_similar.setColumns(20);
        tfa_similar.setRows(5);
        tfa_similar.setName("tfa_similar"); // NOI18N
        jScrollPane1.setViewportView(tfa_similar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastrando Cliente");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/exit.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.setMaximumSize(new java.awt.Dimension(101, 33));
        jb_cancelar.setName("jb_cancelar"); // NOI18N
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, 35));

        jb_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/gravar_registro.gif"))); // NOI18N
        jb_salvar.setText("Salvar");
        jb_salvar.setName("jb_salvar"); // NOI18N
        jb_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, 35));

        jtf_codigo.setEditable(false);
        jtf_codigo.setName("jtf_codigo"); // NOI18N
        getContentPane().add(jtf_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 94, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("CPF");
        jLabel6.setName("jLabel6"); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jtf_empresa.setText("Hospital São Francisco de Assis");
        jtf_empresa.setName("jtf_empresa"); // NOI18N
        jtf_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_empresaActionPerformed(evt);
            }
        });
        jtf_empresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_empresaFocusGained(evt);
            }
        });
        jtf_empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_empresaKeyPressed(evt);
            }
        });
        getContentPane().add(jtf_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, -1));

        jtf_nome_cliente.setText("Alencar Buriti");
        jtf_nome_cliente.setName("jtf_nome_cliente");
        getContentPane().add(jtf_nome_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 280, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Código Cliente");
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Nome");
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setText("Observação: Os campos com asteristico na frente são obrigatórios ");
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, -1, -1));

        jtf_cpf.setText("018.823.491.80");
        jtf_cpf.setName("jtf_cpf"); // NOI18N
        jtf_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_cpfActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 120, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("Empresa");
        jLabel10.setName("jLabel10"); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("Profissão*");
        jLabel11.setName("jLabel11"); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jtf_profissao.setText("Analista de Sistemas Senior");
        jtf_profissao.setName("jtf_profissao"); // NOI18N
        jtf_profissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_profissaoActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_profissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 230, -1));

        jLabel12.setText("Nascimento");
        jLabel12.setName("jLabel12"); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jtf_data_nascimento.setText("19/03/1990");
        jtf_data_nascimento.setName("jtf_data_nascimento"); // NOI18N
        getContentPane().add(jtf_data_nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 110, -1));

        jLabel13.setText("Endereço");
        jLabel13.setName("jLabel13"); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jtf_endereco.setText("Rua Buriti N 10");
        jtf_endereco.setName("jtf_endereco"); // NOI18N
        jtf_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_enderecoActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 220, -1));

        jLabel14.setText("Bairro");
        jLabel14.setName("jLabel14"); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 60, -1));

        jtf_bairro.setText("José Carrilho");
        jtf_bairro.setName("jtf_bairro"); // NOI18N
        getContentPane().add(jtf_bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 180, -1));

        jLabel15.setText("Complemento");
        jLabel15.setName("jLabel15"); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jtf_complemento.setText("QD 55 LT 2/3");
        jtf_complemento.setName("jtf_complemento"); // NOI18N
        getContentPane().add(jtf_complemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 110, -1));

        jLabel16.setText("Email");
        jLabel16.setName("jLabel16"); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jtf_email.setText("alencarburiti@gmail.com");
        jtf_email.setName("jtf_email"); // NOI18N
        getContentPane().add(jtf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 270, -1));

        jLabel17.setText("Observação");
        jLabel17.setName("jLabel17"); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jrb_ativo.setSelected(true);
        jrb_ativo.setText("Ativo");
        jrb_ativo.setName("jrb_ativo"); // NOI18N
        jrb_ativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_ativoActionPerformed(evt);
            }
        });
        getContentPane().add(jrb_ativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jrb_inativo.setText("Inativo");
        jrb_inativo.setName("jrb_inativo"); // NOI18N
        getContentPane().add(jrb_inativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jta_observacao.setColumns(20);
        jta_observacao.setRows(5);
        jta_observacao.setName("jta_observacao"); // NOI18N
        jScrollPane2.setViewportView(jta_observacao);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 230, 160));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel21.setText("Telefone");
        jLabel21.setName("jLabel21"); // NOI18N

        jtf_telefone.setText("(62)8100-0456");
        jtf_telefone.setName("jtf_telefone"); // NOI18N

        jb_adicionar_telefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/edit_add.png"))); // NOI18N
        jb_adicionar_telefone.setToolTipText("Incluir");
        jb_adicionar_telefone.setName("jb_adicionar_telefone"); // NOI18N
        jb_adicionar_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_adicionar_telefoneActionPerformed(evt);
            }
        });

        jb_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/edit_remove.png"))); // NOI18N
        jb_eliminar.setToolTipText("Excluir");
        jb_eliminar.setName("jb_eliminar"); // NOI18N
        jb_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarActionPerformed(evt);
            }
        });

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        jtbl_telefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtbl_telefone.setName("jtbl_telefone"); // NOI18N
        jScrollPane4.setViewportView(jtbl_telefone);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(5, 5, 5)
                        .addComponent(jtf_telefone, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_adicionar_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jtf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jb_adicionar_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, 180));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel22.setText("Dependente");
        jLabel22.setName("jLabel22"); // NOI18N

        jtf_dependente.setText("Erica Pereira Buriti de Barros");
        jtf_dependente.setName("jtf_dependente"); // NOI18N
        jtf_dependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_dependenteActionPerformed(evt);
            }
        });

        jb_adicionar_dependente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/edit_add.png"))); // NOI18N
        jb_adicionar_dependente.setToolTipText("Incluir");
        jb_adicionar_dependente.setName("jb_adicionar_dependente"); // NOI18N
        jb_adicionar_dependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_adicionar_dependenteActionPerformed(evt);
            }
        });

        jb_eliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/edit_remove.png"))); // NOI18N
        jb_eliminar1.setToolTipText("Excluir");
        jb_eliminar1.setName("jb_eliminar1"); // NOI18N
        jb_eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminar1ActionPerformed(evt);
            }
        });

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        jtbl_dependente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtbl_dependente.setName("jtbl_dependente"); // NOI18N
        jScrollPane5.setViewportView(jtbl_dependente);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(5, 5, 5)
                        .addComponent(jtf_dependente))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_adicionar_dependente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jtf_dependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jb_adicionar_dependente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 510, 170));

        jLabel20.setText("Estado");
        jLabel20.setName("jLabel20"); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jtf_estado.setText("GO");
        jtf_estado.setName("jtf_estado"); // NOI18N
        getContentPane().add(jtf_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 60, -1));

        jLabel23.setText("Cidade");
        jLabel23.setName("jLabel23"); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jtf_cidade.setText("Goianésia");
        jtf_cidade.setName("jtf_cidade"); // NOI18N
        jtf_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_cidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, -1));

        setSize(new java.awt.Dimension(562, 687));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        retornaJanelaPai();

}//GEN-LAST:event_jb_cancelarActionPerformed
    private void retornaJanelaPai() {
        setVisible(false);

        if (janelapai != null) {
//            janelapai.listaProduto();
            janelapai.setEnabled(true);
            janelapai.setVisible(true);
//            janelapai.request();
        }
        if (janelapai2 != null) {
            janelapai2.listaProduto("");
            janelapai2.setEnabled(true);
            janelapai2.setVisible(true);

        }

    }
    private void jb_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarActionPerformed
        enviaDados();
}//GEN-LAST:event_jb_salvarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jtf_nome_cliente.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        retornaJanelaPai();
    }//GEN-LAST:event_formWindowClosed

    private void jtf_empresaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_empresaFocusGained

    }//GEN-LAST:event_jtf_empresaFocusGained

private void jtf_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_empresaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jtf_empresaActionPerformed

private void jtf_empresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_empresaKeyPressed

    // TODO add your handling code here:
}//GEN-LAST:event_jtf_empresaKeyPressed

    private void jtf_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_cpfActionPerformed

    private void jtf_profissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_profissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_profissaoActionPerformed

    private void jrb_ativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_ativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_ativoActionPerformed

    private void jtf_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_enderecoActionPerformed

    private void jb_adicionar_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_adicionar_telefoneActionPerformed
        try {
            alimentarTelefone();
        } catch (ParseException ex) {
            Logger.getLogger(Atendimento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_adicionar_telefoneActionPerformed

    private void jb_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarActionPerformed
        excluirProduto();
    }//GEN-LAST:event_jb_eliminarActionPerformed

    private void jb_adicionar_dependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_adicionar_dependenteActionPerformed
        try {
            alimentarDependente();
        } catch (ParseException ex) {
            Logger.getLogger(Atendimento.class.getName()).log(Level.SEVERE, null, ex);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jb_adicionar_dependenteActionPerformed

    private void jb_eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_eliminar1ActionPerformed

    private void jtf_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_cidadeActionPerformed

    private void jtf_dependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_dependenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_dependenteActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new CadastroCliente().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jb_adicionar_dependente;
    private javax.swing.JButton jb_adicionar_telefone;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_eliminar1;
    private javax.swing.JButton jb_salvar;
    public static javax.swing.JRadioButton jrb_ativo;
    public static javax.swing.JRadioButton jrb_inativo;
    public static javax.swing.JTextArea jta_observacao;
    public static javax.swing.JTable jtbl_dependente;
    public static javax.swing.JTable jtbl_telefone;
    public static javax.swing.JTextField jtf_bairro;
    public static javax.swing.JTextField jtf_cidade;
    public javax.swing.JTextField jtf_codigo;
    public static javax.swing.JTextField jtf_complemento;
    public static javax.swing.JTextField jtf_cpf;
    public static javax.swing.JTextField jtf_data_nascimento;
    public static javax.swing.JTextField jtf_dependente;
    public static javax.swing.JTextField jtf_email;
    public static javax.swing.JTextField jtf_empresa;
    public static javax.swing.JTextField jtf_endereco;
    public static javax.swing.JTextField jtf_estado;
    public static javax.swing.JTextField jtf_nome_cliente;
    public static javax.swing.JTextField jtf_profissao;
    public static javax.swing.JTextField jtf_telefone;
    private javax.swing.JTextArea tfa_similar;
    // End of variables declaration//GEN-END:variables
    Produto produto = new Produto();
    private TelaPrincipal_Interface telaPrincipal;

    public void setTelaPrincipal(TelaPrincipal_Interface telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
    }

    public InterfacePool pool;
    public SiscomController controller;

    private void enviaDados() {
        if (verificarCampos()) {
            controller = new SiscomController();
            controller.processarRequisicao("cadastrarCliente");
            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
            retornaJanelaPai();
        }
    }

    public boolean verificarCampos() {
        String msgERRO = "Preencha os campos obrigatórios:\n";

        if (jtf_nome_cliente.getText().trim().equals("")) {
            msgERRO = msgERRO + " *Descrição\n";
        }

        if (!msgERRO.equals("Preencha os campos obrigatórios:\n")) {
            JOptionPane.showMessageDialog(this, msgERRO);
            jtf_nome_cliente.requestFocus();
            return false;
        } else {
            return true;
        }

    }

    public void setStatusTela(boolean status) {
        if (status) {
            this.setVisible(status);
        }
        this.setEnabled(status);
    }

    public void verificaCadastro() {
        ProdutoDAO prod = new ProdutoDAO();
        produtos = prod.listarProduto(jtf_nome_cliente.getText().trim());
        validaCadastro(produtos);
    }

    public void validaCadastro(List<Produto> produto) {//verifica cadastro existente que retornou de uma lista

        if (produto.size() == 0) {
            //cadastraProduto();
        } else {
            JOptionPane.showMessageDialog(null, "Produto existente");
            jtf_nome_cliente.requestFocus();
        }
    }

    Telefone telefone = new Telefone();
    Cliente cliente;

    public void alimentarDependente() throws ParseException {
        Dependente dependente = new Dependente();
        if (verificar_campo_dependente() == true) { //&& (verificaTabela()
            dependente.setCliente(cliente);
            dependente.setNome_dependente(jtf_dependente.getText());

            DefaultTableModel row = (DefaultTableModel) jtbl_dependente.getModel();
            ItemDbGrid hashDbGrid = new ItemDbGrid(dependente, dependente.getNome_dependente());
            row.addRow(new Object[]{dependente.getNome_dependente()});
            jtf_dependente.setText("");
            jtf_dependente.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possivel adicionar ");
        }
    }

    public void alimentarTelefone() throws ParseException {
        if (verificar_campo_telefone() == true) { //&& (verificaTabela()
            telefone.setCliente(cliente);
            telefone.setTelefone(jtf_telefone.getText());

            DefaultTableModel row = (DefaultTableModel) jtbl_telefone.getModel();
            ItemDbGrid hashDbGrid = new ItemDbGrid(telefone, telefone.getTelefone());
            row.addRow(new Object[]{telefone.getTelefone()});
            jtf_telefone.setText("");
            jtf_telefone.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possivel adicionar ");
        }
    }

    public boolean verificar_campo_telefone() {
        String msgERRO = "Preencha os campos obrigatórios:\n";

        if (jtf_telefone.getText().equals("")) {
            msgERRO = msgERRO + " *Telefone\n";
        }

        if (!msgERRO.equals("Preencha os campos obrigatórios:\n")) {
            JOptionPane.showMessageDialog(this, msgERRO);
            jtf_telefone.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    public boolean verificar_campo_dependente() {
        String msgERRO = "Preencha os campos obrigatórios:\n";

        if (jtf_dependente.getText().equals("")) {
            msgERRO = msgERRO + " *Telefone\n";
        }

        if (!msgERRO.equals("Preencha os campos obrigatórios:\n")) {
            JOptionPane.showMessageDialog(this, msgERRO);
            jtf_dependente.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    public boolean verificaTabela() {

        boolean tabela = true;
        if (jtbl_telefone.getRowCount() == 0) {
            return true;

        } else if (jtbl_telefone.getRowCount() > 0) {
            int linhas = jtbl_telefone.getRowCount();

            for (int i = 0; i < linhas; i++) {
                Cliente cliente = new Cliente();
                cliente.setTelefone(new Telefone((Integer) jtbl_telefone.getValueAt(i, 0)));

                String telefone = null;
                telefone = jtf_telefone.getText();

            }

            return tabela;
        }
        return tabela;
    }

    private void excluirProduto() {
        removeProduto(jtbl_telefone);
    }

    public void removeProduto(JTable tb) {
        DefaultTableModel row = (DefaultTableModel) jtbl_telefone.getModel();
        if (tb.getSelectedRow() != -1) {
            int selectedOption = JOptionPane.showConfirmDialog(this, "Deseja excluir ?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (selectedOption == JOptionPane.YES_NO_OPTION) {
                row.removeRow(tb.getSelectedRow());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto");
        }
    }
}
