package br.com.locadora.view;

import br.com.locadora.conexao.InterfacePool;
import br.com.locadora.controller.SiscomController;
import br.com.locadora.model.bean.Cliente;
import br.com.locadora.model.bean.Diaria;
import br.com.locadora.model.bean.Genero;
import br.com.locadora.model.bean.Produto;
import br.com.locadora.model.bean.Telefone;
import br.com.locadora.model.dao.ProdutoDAO;
import br.com.locadora.util.LimitadorTexto;
import br.com.locadora.util.UnaccentedDocument;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALENCAR
 */
public final class CadastroObjeto extends javax.swing.JFrame implements CadastroObjeto_InterFace {

    private TelaPrincipal janela;
    public List<Produto> produtos;
    public MenuObjeto janelaPaim;
    public static Diaria diaria;
    public static Genero genero;

    /**
     * Creates new form ProdutoCadastroGUI
     */
    public CadastroObjeto() throws SQLException {
        initComponents();
        janelapai = null;
        janelapai2 = null;

       
    }

    public CadastroObjeto janelapai;
    public ProdutoConsultarGUI janelapai2;

    //public ProdutoConsultarGUI janelapaim;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tfa_similar = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jb_cancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jtf_codigo_objeto = new javax.swing.JTextField();
        jtf_titulo_original = new javax.swing.JTextField(new LimitadorTexto(45), "",10);
        jtf_descricao_objeto = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtf_descricao_resumida = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtf_duracao = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtf_censura = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jtf_descricao_genero = new javax.swing.JTextField();
        jb_genero = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtf_saldo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jtf_disponivel = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jcb_producao = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jtf_codigo_diaria = new javax.swing.JTextField();
        jtf_descricao_diaria = new javax.swing.JTextField();
        jb_diaria = new javax.swing.JButton();
        jtf_valor = new javax.swing.JTextField();
        jtf_valor_promocao = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jcb_midia = new javax.swing.JComboBox();
        jcb_tipo_midia = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jcb_tipo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_elenco = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_sinopse = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jb_adicionar_dependente = new javax.swing.JButton();
        jb_eliminar1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtbl_copia = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jtf_codigo_interno = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jcb_idioma = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jcb_legenda = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jtf_preco_custo = new javax.swing.JTextField();
        jtf_localizacao = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jtf_data_aquisicao = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jtf_codigo_barras = new javax.swing.JTextField();
        jb_salvar1 = new javax.swing.JButton();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tfa_similar.setColumns(20);
        tfa_similar.setRows(5);
        tfa_similar.setName("tfa_similar"); // NOI18N
        jScrollPane1.setViewportView(tfa_similar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastrando Objetos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/exit.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.setMaximumSize(new java.awt.Dimension(101, 33));
        jb_cancelar.setName("jb_cancelar"); // NOI18N
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, 35));

        jLabel2.setText("Observação: Os campos com asteristico na frente são obrigatórios ");
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtf_codigo_objeto.setEditable(false);
        jtf_codigo_objeto.setName("jtf_codigo_objeto"); // NOI18N
        jPanel1.add(jtf_codigo_objeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 94, -1));

        jtf_titulo_original.setDocument(new UnaccentedDocument());
        jtf_titulo_original.setText("Evil Woman");
        jtf_titulo_original.setName("jtf_titulo_original"); // NOI18N
        jtf_titulo_original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_titulo_originalActionPerformed(evt);
            }
        });
        jtf_titulo_original.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_titulo_originalFocusGained(evt);
            }
        });
        jtf_titulo_original.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_titulo_originalKeyPressed(evt);
            }
        });
        jPanel1.add(jtf_titulo_original, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 340, -1));

        jtf_descricao_objeto.setDocument(new UnaccentedDocument());
        jtf_descricao_objeto.setText("Mulher Infernal");
        jtf_descricao_objeto.setName("jtf_descricao_objeto");
        jtf_descricao_objeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_descricao_objetoActionPerformed(evt);
            }
        });
        jtf_descricao_objeto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_descricao_objetoFocusGained(evt);
            }
        });
        jtf_descricao_objeto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_descricao_objetoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_descricao_objetoKeyReleased(evt);
            }
        });
        jPanel1.add(jtf_descricao_objeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 340, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Código Objeto");
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Descrição*");
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("Título Original *");
        jLabel10.setName("jLabel10"); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel13.setText("Descrição resumida");
        jLabel13.setName("jLabel13"); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jtf_descricao_resumida.setText("Mulher Infernal");
        jtf_descricao_resumida.setName("jtf_descricao_resumida"); // NOI18N
        jtf_descricao_resumida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_descricao_resumidaActionPerformed(evt);
            }
        });
        jPanel1.add(jtf_descricao_resumida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 340, -1));

        jLabel14.setText("Duração");
        jLabel14.setName("jLabel14"); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 60, -1));

        jtf_duracao.setText("90min");
        jtf_duracao.setName("jtf_duracao"); // NOI18N
        jPanel1.add(jtf_duracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 90, -1));

        jLabel15.setText("Censura");
        jLabel15.setName("jLabel15"); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        jtf_censura.setText("14");
        jtf_censura.setName("jtf_censura"); // NOI18N
        jPanel1.add(jtf_censura, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 70, -1));

        jLabel23.setText("Gênero");
        jLabel23.setName("jLabel23"); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jtf_descricao_genero.setName("jtf_descricao_genero"); // NOI18N
        jtf_descricao_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_descricao_generoActionPerformed(evt);
            }
        });
        jPanel1.add(jtf_descricao_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, -1));

        jb_genero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/pesquisar.png"))); // NOI18N
        jb_genero.setName("jb_genero"); // NOI18N
        jb_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_generoActionPerformed(evt);
            }
        });
        jPanel1.add(jb_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 30, 30));

        jLabel24.setText("Produção");
        jLabel24.setName("jLabel24"); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel21.setText("Saldo");
        jLabel21.setName("jLabel21"); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        jtf_saldo.setEditable(false);
        jtf_saldo.setText("0");
        jtf_saldo.setName("jtf_saldo"); // NOI18N
        jtf_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_saldoActionPerformed(evt);
            }
        });
        jPanel1.add(jtf_saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, -1));

        jLabel25.setText("Disponivel");
        jLabel25.setName("jLabel25"); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        jtf_disponivel.setEditable(false);
        jtf_disponivel.setText("0");
        jtf_disponivel.setName("jtf_disponivel"); // NOI18N
        jtf_disponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_disponivelActionPerformed(evt);
            }
        });
        jPanel1.add(jtf_disponivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 80, -1));

        jLabel34.setText("Mídia");
        jLabel34.setName("jLabel34"); // NOI18N
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, 20));

        jcb_producao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Americana", "Espanhola", "Francesa", "Italiana", "Japonesa", "Nacional" }));
        jcb_producao.setName("jcb_producao"); // NOI18N
        jPanel1.add(jcb_producao, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 120, 30));

        jLabel35.setText("Diária");
        jLabel35.setName("jLabel35"); // NOI18N
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jtf_codigo_diaria.setEditable(false);
        jtf_codigo_diaria.setName("jtf_codigo_diaria"); // NOI18N
        jtf_codigo_diaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_codigo_diariaActionPerformed(evt);
            }
        });
        jPanel1.add(jtf_codigo_diaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 90, -1));

        jtf_descricao_diaria.setEditable(false);
        jtf_descricao_diaria.setName("jtf_descricao_diaria"); // NOI18N
        jPanel1.add(jtf_descricao_diaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 130, -1));

        jb_diaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/pesquisar.png"))); // NOI18N
        jb_diaria.setName("jb_diaria"); // NOI18N
        jb_diaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_diariaActionPerformed(evt);
            }
        });
        jPanel1.add(jb_diaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 30, 30));

        jtf_valor.setEditable(false);
        jtf_valor.setText("R$ 0,00");
        jtf_valor.setName("jtf_valor"); // NOI18N
        jtf_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_valorActionPerformed(evt);
            }
        });
        jPanel1.add(jtf_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 100, -1));

        jtf_valor_promocao.setEditable(false);
        jtf_valor_promocao.setText("R$ 0,00");
        jtf_valor_promocao.setName("jtf_valor_promocao"); // NOI18N
        jtf_valor_promocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_valor_promocaoActionPerformed(evt);
            }
        });
        jPanel1.add(jtf_valor_promocao, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 100, -1));

        jLabel36.setText("Valor Promocional");
        jLabel36.setName("jLabel36"); // NOI18N
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jLabel37.setText("Valor");
        jLabel37.setName("jLabel37"); // NOI18N
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Ativo");
        jRadioButton1.setName("jRadioButton1"); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Inativo");
        jRadioButton2.setName("jRadioButton2"); // NOI18N
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        jcb_midia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blu Ray", "CD", "DVD", "Playstation", "VHs", "Xbox", " " }));
        jcb_midia.setName("jcb_midia"); // NOI18N
        jPanel1.add(jcb_midia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 30));

        jcb_tipo_midia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Filme", "Seriado", "Game", "Livro" }));
        jcb_tipo_midia.setName("jcb_tipo_midia"); // NOI18N
        jPanel1.add(jcb_tipo_midia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 100, 30));

        jLabel38.setText("Tipo de Mídia");
        jLabel38.setName("jLabel38"); // NOI18N
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, 20));

        jLabel39.setText("Tipo ");
        jLabel39.setName("jLabel39"); // NOI18N
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, 20));

        jcb_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Locação", "Venda", " " }));
        jcb_tipo.setName("jcb_tipo"); // NOI18N
        jPanel1.add(jcb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 120, 30));

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Sinopse");
        jLabel17.setName("jLabel17"); // NOI18N
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jta_elenco.setColumns(20);
        jta_elenco.setRows(5);
        jta_elenco.setName("jta_elenco"); // NOI18N
        jScrollPane2.setViewportView(jta_elenco);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 550, 90));

        jLabel4.setText("Elenco");
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jta_sinopse.setColumns(20);
        jta_sinopse.setRows(5);
        jta_sinopse.setName("jta_sinopse"); // NOI18N
        jScrollPane3.setViewportView(jta_sinopse);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 550, 100));

        jTabbedPane1.addTab("Cinema", jPanel3);

        jPanel2.setToolTipText("");
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_adicionar_dependente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/edit_add.png"))); // NOI18N
        jb_adicionar_dependente.setToolTipText("Incluir");
        jb_adicionar_dependente.setName("jb_adicionar_dependente"); // NOI18N
        jb_adicionar_dependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_adicionar_dependenteActionPerformed(evt);
            }
        });
        jPanel2.add(jb_adicionar_dependente, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 30, 30));

        jb_eliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/edit_remove.png"))); // NOI18N
        jb_eliminar1.setToolTipText("Excluir");
        jb_eliminar1.setName("jb_eliminar1"); // NOI18N
        jb_eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jb_eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 30, 30));

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        jtbl_copia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Barras", "Código Interno", "Localização", "Idioma", "Legenda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtbl_copia.setName("jtbl_copia"); // NOI18N
        jScrollPane5.setViewportView(jtbl_copia);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 650, 150));

        jLabel26.setText("Código Interno");
        jLabel26.setName("jLabel26"); // NOI18N
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jtf_codigo_interno.setName("jtf_codigo_interno"); // NOI18N
        jtf_codigo_interno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_codigo_internoActionPerformed(evt);
            }
        });
        jPanel2.add(jtf_codigo_interno, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 52, 140, -1));

        jLabel27.setText("Idioma");
        jLabel27.setName("jLabel27"); // NOI18N
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jcb_idioma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chinês", "Espanhol", "Francês", "Inglês", "Italiano", "Japonês", "Polonês", "Português" }));
        jcb_idioma.setName("jcb_idioma"); // NOI18N
        jPanel2.add(jcb_idioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jLabel28.setText("Legenda");
        jLabel28.setName("jLabel28"); // NOI18N
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        jcb_legenda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chinês", "Espanhol", "Francês", "Inglês", "Italiano", "Japonês", "Polonês", "Português", "Não Legendado" }));
        jcb_legenda.setName("jcb_legenda"); // NOI18N
        jPanel2.add(jcb_legenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel29.setText("Preço custo");
        jLabel29.setName("jLabel29"); // NOI18N
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jtf_preco_custo.setText("R$ 2,00");
        jtf_preco_custo.setName("jtf_preco_custo"); // NOI18N
        jtf_preco_custo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_preco_custoActionPerformed(evt);
            }
        });
        jPanel2.add(jtf_preco_custo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 110, -1));

        jtf_localizacao.setText("1010-1");
        jtf_localizacao.setName("jtf_localizacao"); // NOI18N
        jtf_localizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_localizacaoActionPerformed(evt);
            }
        });
        jPanel2.add(jtf_localizacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 240, -1));

        jLabel30.setText("Localização");
        jLabel30.setName("jLabel30"); // NOI18N
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel31.setText("Data Aquisição");
        jLabel31.setName("jLabel31"); // NOI18N
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 120, -1));

        jtf_data_aquisicao.setText("19/03/2000");
        jtf_data_aquisicao.setName("jtf_data_aquisicao"); // NOI18N
        jtf_data_aquisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_data_aquisicaoActionPerformed(evt);
            }
        });
        jPanel2.add(jtf_data_aquisicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 120, -1));

        jLabel32.setText("Código de Barras");
        jLabel32.setName("jLabel32"); // NOI18N
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jtf_codigo_barras.setName("jtf_codigo_barras"); // NOI18N
        jtf_codigo_barras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_codigo_barrasActionPerformed(evt);
            }
        });
        jPanel2.add(jtf_codigo_barras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 270, -1));

        jTabbedPane1.addTab("Cópias", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 720, 360));

        jb_salvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/gravar_registro.gif"))); // NOI18N
        jb_salvar1.setText("Salvar");
        jb_salvar1.setName("jb_salvar1"); // NOI18N
        jb_salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jb_salvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, 35));

        setSize(new java.awt.Dimension(806, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        retornaJanelaPai();

}//GEN-LAST:event_jb_cancelarActionPerformed
    private void retornaJanelaPai() {
        setVisible(false);

        if (janelapai != null) {
//            janelapai.listaProduto();
            janelapai.setEnabled(true);
            janelapai.setVisible(true);
//            janelapai.request();
        }
        if (janelapai2 != null) {
            janelapai2.listaProduto("");
            janelapai2.setEnabled(true);
            janelapai2.setVisible(true);
        }

    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jtf_descricao_objeto.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        retornaJanelaPai();
    }//GEN-LAST:event_formWindowClosed

    private void jtf_descricao_objetoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_descricao_objetoKeyPressed
        jtf_descricao_objeto.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                if (evt.getKeyCode() != KeyEvent.VK_HOME) {
                    String s = jtf_descricao_objeto.getText();
                    jtf_descricao_objeto.setText(s.toUpperCase());
                }
            }
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descricao_objetoKeyPressed
    private void jtf_descricao_objetoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_descricao_objetoFocusGained
        jtf_descricao_objeto.setInputVerifier(new InputVerifier() {

            public boolean verify(JComponent input) {
                if (jtf_descricao_objeto.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe o principio ativo do produto");
                    jtf_descricao_objeto.requestFocus();
                    return false;
                } else {
                    return true;
                }
            }
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descricao_objetoFocusGained

    private void jtf_titulo_originalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_titulo_originalFocusGained
//    jtf_concentração.setInputVerifier(new InputVerifier() {
//    public boolean verify(JComponent input) {
//                if(jtf_concentração.getText().equals("")) {
//                    JOptionPane.showMessageDialog(null, "Informe a concentação do produto");
//                    jtf_concentração.requestFocus();
//                    return false;
//                } else {
//                    return true;
//                }
//            }
//    });
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_titulo_originalFocusGained

    private void jtf_descricao_objetoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_descricao_objetoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descricao_objetoKeyReleased

private void jtf_titulo_originalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_titulo_originalActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jtf_titulo_originalActionPerformed

private void jtf_titulo_originalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_titulo_originalKeyPressed
    jtf_titulo_original.addKeyListener(new KeyAdapter() {
        public void keyReleased(KeyEvent evt) {
            if (evt.getKeyCode() != KeyEvent.VK_HOME) {
                String s = jtf_titulo_original.getText();
                jtf_titulo_original.setText(s.toUpperCase());
            }
        }
    });

    // TODO add your handling code here:
}//GEN-LAST:event_jtf_titulo_originalKeyPressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jtf_descricao_objetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_descricao_objetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descricao_objetoActionPerformed

    private void jtf_descricao_resumidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_descricao_resumidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descricao_resumidaActionPerformed

    private void jtf_descricao_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_descricao_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descricao_generoActionPerformed

    private void jb_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_generoActionPerformed
        ConsultaGeneroObjeto consultaGenero = new ConsultaGeneroObjeto();
        consultaGenero.setTelaCadastroObjeto(this);
        consultaGenero.janelapai = this;
        try {
            consultaGenero.listaTodasGeneros();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroObjeto.class.getName()).log(Level.SEVERE, null, ex);
        }
        consultaGenero.setVisible(true);
        //    setStatusTela(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_generoActionPerformed

    private void jtf_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_saldoActionPerformed

    private void jtf_disponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_disponivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_disponivelActionPerformed

    private void jtf_codigo_internoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_codigo_internoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_codigo_internoActionPerformed

    private void jb_eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_eliminar1ActionPerformed

    private void jb_adicionar_dependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_adicionar_dependenteActionPerformed
        if (jtf_codigo_objeto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Salvar primeiro o Objeto");
        } else {
            controller = new SiscomController();
            controller.processarRequisicao("cadastrarCopia");
        }
    }//GEN-LAST:event_jb_adicionar_dependenteActionPerformed

    private void jtf_preco_custoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_preco_custoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_preco_custoActionPerformed

    private void jtf_localizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_localizacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_localizacaoActionPerformed

    private void jtf_data_aquisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_data_aquisicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_data_aquisicaoActionPerformed

    private void jb_salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvar1ActionPerformed
        enviaDados();
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvar1ActionPerformed

    private void jtf_codigo_diariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_codigo_diariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_codigo_diariaActionPerformed

    private void jb_diariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_diariaActionPerformed
        ConsultaDiariaObjeto consulta = new ConsultaDiariaObjeto();
        consulta.setTelaCadastroObjeto(this);
        consulta.janelapai = this;
        try {
            consulta.listaTodasDiarias();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroObjeto.class.getName()).log(Level.SEVERE, null, ex);
        }
        consulta.setVisible(true);
        //    setStatusTela(false);
    }//GEN-LAST:event_jb_diariaActionPerformed

    private void jtf_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valorActionPerformed

    private void jtf_valor_promocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_valor_promocaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valor_promocaoActionPerformed

    private void jtf_codigo_barrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_codigo_barrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_codigo_barrasActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new CadastroObjeto().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CadastroObjeto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_adicionar_dependente;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_diaria;
    private javax.swing.JButton jb_eliminar1;
    private javax.swing.JButton jb_genero;
    private javax.swing.JButton jb_salvar1;
    public static javax.swing.JComboBox jcb_idioma;
    public static javax.swing.JComboBox jcb_legenda;
    public static javax.swing.JComboBox jcb_midia;
    public static javax.swing.JComboBox jcb_producao;
    public static javax.swing.JComboBox jcb_tipo;
    public static javax.swing.JComboBox jcb_tipo_midia;
    public static javax.swing.JTextArea jta_elenco;
    public static javax.swing.JTextArea jta_sinopse;
    public static javax.swing.JTable jtbl_copia;
    public static javax.swing.JTextField jtf_censura;
    public static javax.swing.JTextField jtf_codigo_barras;
    public static javax.swing.JTextField jtf_codigo_diaria;
    public static javax.swing.JTextField jtf_codigo_interno;
    public static javax.swing.JTextField jtf_codigo_objeto;
    public static javax.swing.JTextField jtf_data_aquisicao;
    private javax.swing.JTextField jtf_descricao_diaria;
    public static javax.swing.JTextField jtf_descricao_genero;
    public static javax.swing.JTextField jtf_descricao_objeto;
    public static javax.swing.JTextField jtf_descricao_resumida;
    public static javax.swing.JTextField jtf_disponivel;
    public static javax.swing.JTextField jtf_duracao;
    public static javax.swing.JTextField jtf_localizacao;
    public static javax.swing.JTextField jtf_preco_custo;
    public static javax.swing.JTextField jtf_saldo;
    public static javax.swing.JTextField jtf_titulo_original;
    public static javax.swing.JTextField jtf_valor;
    public static javax.swing.JTextField jtf_valor_promocao;
    private javax.swing.JTextArea tfa_similar;
    // End of variables declaration//GEN-END:variables
    Produto produto = new Produto();
    private TelaPrincipal_Interface telaPrincipal;

    public void setTelaPrincipal(TelaPrincipal_Interface telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
    }

    public void setTela(String permissao) {
        if (permissao.equals("usuario")) {
//            jb_novo.setEnabled(false);
//            jb_alterar1.setEnabled(false);
//            jb_excluir1.setEnabled(false);
        } else {
        }
    }

    InterfacePool pool;
    SiscomController controller;

    private void enviaDados() {
        if (verificarCampos()) {
            controller = new SiscomController();
            controller.processarRequisicao("cadastrarObjeto");
            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
//            retornaJanelaPai();
        }
    }

    public boolean verificarCampos() {
        String msgERRO = "Preencha os campos obrigatórios:\n";

        if (jtf_descricao_objeto.getText().trim().equals("")) {
            msgERRO = msgERRO + " *Descrição\n";
        }

        if (!msgERRO.equals("Preencha os campos obrigatórios:\n")) {
            JOptionPane.showMessageDialog(this, msgERRO);
            jtf_descricao_objeto.requestFocus();
            return false;
        } else {
            return true;
        }

    }

    public void setStatusTela(boolean status) {
        if (status) {
            this.setVisible(status);
        }
        this.setEnabled(status);
    }

    public void verificaCadastro() {
        ProdutoDAO prod = new ProdutoDAO();
        produtos = prod.listarProduto(jtf_descricao_objeto.getText().trim());
        validaCadastro(produtos);
    }

    public void validaCadastro(List<Produto> produto) {//verifica cadastro existente que retornou de uma lista

        if (produto.size() == 0) {
            //cadastraProduto();
        } else {
            JOptionPane.showMessageDialog(null, "Produto existente");
            jtf_descricao_objeto.requestFocus();
        }
    }

    Telefone telefone = new Telefone();
    Cliente cliente;

    public boolean verificar_campo_copia() {
        String msgERRO = "Preencha os campos obrigatórios:\n";

        if (jtf_localizacao.getText().equals("")) {
            msgERRO = msgERRO + " *Localização\n";
        }

        if (!msgERRO.equals("Preencha os campos obrigatórios:\n")) {
            JOptionPane.showMessageDialog(this, msgERRO);
            jtf_localizacao.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    public boolean verificaTabela() {

        boolean tabela = true;
        if (jtbl_copia.getRowCount() == 0) {
            return true;

        } else if (jtbl_copia.getRowCount() > 0) {
            int linhas = jtbl_copia.getRowCount();

            for (int i = 0; i < linhas; i++) {
                Cliente cliente = new Cliente();
                cliente.setTelefone(new Telefone((Integer) jtbl_copia.getValueAt(i, 0)));

                String telefone = null;
                telefone = jtf_localizacao.getText();

            }

            return tabela;
        }
        return tabela;
    }

    private void excluirDiaria() {
        removerDiaria(jtbl_copia);
    }

    public void removerDiaria(JTable tb) {
        DefaultTableModel row = (DefaultTableModel) jtbl_copia.getModel();
        if (tb.getSelectedRow() != -1) {
            int selectedOption = JOptionPane.showConfirmDialog(this, "Deseja excluir ?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (selectedOption == JOptionPane.YES_NO_OPTION) {
                row.removeRow(tb.getSelectedRow());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto");
        }
    }

    public void carregaDiaria(Diaria diaria) {
        this.diaria = diaria;
        jtf_codigo_diaria.setText(String.valueOf(diaria.getDias()));
        jtf_descricao_diaria.setText(diaria.getNome_diaria());
        String valor = null;
        String valor_promocao = null;
        String multa = null;

        valor = String.valueOf(diaria.getValor());
        valor_promocao = String.valueOf(diaria.getValor_promocao());
        multa = String.valueOf(diaria.getMultas());

        valor = setPrecoFormat(valor);
        valor_promocao = setPrecoFormat(valor_promocao);
        multa = setPrecoFormat(multa);

        jtf_valor.setText(valor);
        jtf_valor_promocao.setText(valor_promocao);
    }

    public void carregaGenero(Genero genero) {
        this.genero = genero;
        jtf_descricao_genero.setText(genero.getNome_genero());
    }

    public void setRequestDiaria() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setRequestGenero() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public String setPrecoFormat(String preco) {
        DecimalFormat dFormat = new DecimalFormat();
        dFormat.applyPattern("R$ #0.00");
        return dFormat.format(getPrecoFormato(preco));
    }

    public static Double getPrecoFormato(String preco) {
        Double precoFormatado = 0.0;
        try {
            preco = preco.replace("R", "");
            preco = preco.replace("$", "");
            preco = preco.replace(",", ".");
            preco = preco.replace(" ", "");
            precoFormatado = Double.parseDouble(preco.trim());

            //this.objFuncionario.setSalario(getSalarioFormat(jTSalario.getText())); pegar valor em double
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Valor Informado Incorreto!\nInforme um valor com o seguinte formato:\nEx: 100,00");
        }
        return precoFormatado;
    }

    public static Diaria getObjetoDiaria() {
        return diaria;
    }

    public static Genero getObjetoGenero() {
        return genero;
    }
}
