/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuDiaria.java
 *
 * Created on 02/06/2011, 00:56:52
 */
package br.com.locadora.view;

import br.com.locadora.conexao.InterfacePool;
import br.com.locadora.controller.SiscomController;
import br.com.locadora.util.ArquivoConfiguracao;
import br.com.locadora.util.AutoCompletion;
import br.com.locadora.util.Printer;
import br.com.locadora.util.TemaInterface;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ALENCAR
 */
public class ConfiguraImpressora extends javax.swing.JFrame {

    public String tipoCadastro;
    public TelaPrincipal janelapai;
    public EntradaCaixa janelapaiCaixaLocacao;
    public EntradaCaixaDevolucao janelapaiCaixaDevolucao;
    public InterfacePool pool;
    public SiscomController controller;

    /**
     * Creates new form DiariaGUI
     */
    public ConfiguraImpressora() {
        initComponents();
        TemaInterface.getInterface(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jcb_impressora_principal = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcb_impressora_alternativa = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Impressoras");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Aplicar");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jcb_impressora_principal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jcb_impressora_principal.setName("jcb_impressora_principal"); // NOI18N
        jcb_impressora_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_impressora_principalActionPerformed(evt);
            }
        });
        jcb_impressora_principal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcb_impressora_principalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcb_impressora_principalFocusLost(evt);
            }
        });
        getContentPane().add(jcb_impressora_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, -1));

        jLabel1.setText("Selecione impressora principal:");
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel2.setText("Selecione impressora alternativa:");
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jcb_impressora_alternativa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jcb_impressora_alternativa.setName("jcb_impressora_alternativa"); // NOI18N
        jcb_impressora_alternativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_impressora_alternativaActionPerformed(evt);
            }
        });
        jcb_impressora_alternativa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcb_impressora_alternativaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcb_impressora_alternativaFocusLost(evt);
            }
        });
        getContentPane().add(jcb_impressora_alternativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 210, -1));

        setSize(new java.awt.Dimension(293, 279));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        setVisible(false);
        janelapai.setStatusTela(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        mostraImpressoras();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        conf.writePropertie("impressora_principal", jcb_impressora_principal.getSelectedItem().toString());
        conf.writePropertie("impressora_alternativa", jcb_impressora_alternativa.getSelectedItem().toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcb_impressora_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_impressora_principalActionPerformed

    }//GEN-LAST:event_jcb_impressora_principalActionPerformed

    private void jcb_impressora_principalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcb_impressora_principalFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_impressora_principalFocusGained

    private void jcb_impressora_principalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcb_impressora_principalFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_impressora_principalFocusLost

    private void jcb_impressora_alternativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_impressora_alternativaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_impressora_alternativaActionPerformed

    private void jcb_impressora_alternativaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcb_impressora_alternativaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_impressora_alternativaFocusGained

    private void jcb_impressora_alternativaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcb_impressora_alternativaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_impressora_alternativaFocusLost
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConfiguraImpressora().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox jcb_impressora_alternativa;
    private javax.swing.JComboBox jcb_impressora_principal;
    // End of variables declaration//GEN-END:variables

    public void mostraImpressoras() {

        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        String impressora_principal = conf.readPropertie("impressora_principal");
        String impressora_alternativa = conf.readPropertie("impressora_alternativa");
        List<String> impressoras = Printer.retornaImpressoras();

        if (impressoras.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhuma impressora encontrada");

        } else {
            for (int i = 0; i < impressoras.size(); i++) {
                jcb_impressora_principal.addItem(impressoras.get(i));
                AutoCompletion auto = new AutoCompletion(jcb_impressora_principal);
            }

            for (int i = 0; i < impressoras.size(); i++) {
                jcb_impressora_alternativa.addItem(impressoras.get(i));
                AutoCompletion auto = new AutoCompletion(jcb_impressora_alternativa);
            }

            for (Integer x = 0; x < jcb_impressora_principal.getItemCount(); x++) {
                if (impressora_principal.equals(jcb_impressora_principal.getItemAt(x))) {
                    jcb_impressora_principal.setSelectedIndex(x);
                    break;
                }

            }
            for (Integer x = 0; x < jcb_impressora_alternativa.getItemCount(); x++) {
                if (impressora_alternativa.equals(jcb_impressora_alternativa.getItemAt(x))) {
                    jcb_impressora_alternativa.setSelectedIndex(x);
                    break;
                }

            }
        }
    }

}
