/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultarProdutoGUI.java
 *
 * Created on 02/06/2011, 03:08:41
 */
package br.com.locadora.view;

import br.com.locadora.conexao.InterfacePool;
import br.com.locadora.conexao.Pool;
import br.com.locadora.model.bean.Copia;
import br.com.locadora.model.dao.CopiaDAO;
import br.com.locadora.util.ItemDbGrid;
import br.com.locadora.util.TemaInterface;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALENCAR
 */
public class ConsultaCopiaLocacao extends javax.swing.JFrame {

    public AtendimentoLocacao janelapai;
    public List<Copia> copias;
    public Copia copia;

    public ConsultaCopiaLocacao() {
        initComponents();
        TemaInterface.getInterface(this);
        janelapai = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jtf_consulta = new javax.swing.JTextField();
        jb_buscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbl_copia = new javax.swing.JTable();
        jrb_titulo = new javax.swing.JRadioButton();
        jrb_ator = new javax.swing.JRadioButton();
        jrb_codigo_barras = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jb_cancelar = new javax.swing.JButton();
        jb_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Objeto/Cópias");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta Objeto"));
        jPanel1.setName("jPanel1"); // NOI18N

        jtf_consulta.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_consulta.setName("jtf_consulta"); // NOI18N
        jtf_consulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_consultaKeyPressed(evt);
            }
        });

        jb_buscar.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/pesquisar.png"))); // NOI18N
        jb_buscar.setName("jb_buscar"); // NOI18N
        jb_buscar.setPreferredSize(new java.awt.Dimension(28, 28));
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed1(evt);
            }
        });

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jtbl_copia.setUpdateSelectionOnSort(false);
        jtbl_copia.setVerifyInputWhenFocusTarget(false);
        jtbl_copia.setDefaultEditor(Object.class, null);
        jtbl_copia.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e){
                if(e.getClickCount() == 2){
                    botaoOK(jtbl_copia);

                }}});
                jtbl_copia.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
                jtbl_copia.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Código de Barras", "Título", "Idioma", "Legenda", "Mídia", "Tipo Mídia", "Livre", "Data Prevista"
                    }
                ) {
                    Class[] types = new Class [] {
                        java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
                    };
                    boolean[] canEdit = new boolean [] {
                        false, false, false, false, false, false, false, false
                    };

                    public Class getColumnClass(int columnIndex) {
                        return types [columnIndex];
                    }

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
                jtbl_copia.setName("jtbl_copia"); // NOI18N
                jtbl_copia.getTableHeader().setReorderingAllowed(false);
                jtbl_copia.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jtbl_copiaMouseClicked(evt);
                    }
                });
                jtbl_copia.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        jtbl_copiaKeyPressed(evt);
                    }
                });
                jScrollPane3.setViewportView(jtbl_copia);
                if (jtbl_copia.getColumnModel().getColumnCount() > 0) {
                    jtbl_copia.getColumnModel().getColumn(0).setPreferredWidth(100);
                    jtbl_copia.getColumnModel().getColumn(1).setPreferredWidth(150);
                    jtbl_copia.getColumnModel().getColumn(6).setPreferredWidth(40);
                }

                buttonGroup1.add(jrb_titulo);
                jrb_titulo.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
                jrb_titulo.setSelected(true);
                jrb_titulo.setText("Título");
                jrb_titulo.setName("jrb_titulo"); // NOI18N
                jrb_titulo.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jrb_tituloActionPerformed(evt);
                    }
                });

                buttonGroup1.add(jrb_ator);
                jrb_ator.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
                jrb_ator.setText("Elenco");
                jrb_ator.setName("jrb_ator"); // NOI18N
                jrb_ator.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jrb_atorActionPerformed(evt);
                    }
                });

                buttonGroup1.add(jrb_codigo_barras);
                jrb_codigo_barras.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
                jrb_codigo_barras.setText("Código de Barras");
                jrb_codigo_barras.setName("jrb_codigo_barras"); // NOI18N
                jrb_codigo_barras.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jrb_codigo_barrasActionPerformed(evt);
                    }
                });

                jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
                jLabel2.setText("Parâmetro");
                jLabel2.setName("jLabel2"); // NOI18N

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtf_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jb_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrb_titulo)
                                        .addGap(0, 0, 0)
                                        .addComponent(jrb_ator)
                                        .addGap(0, 0, 0)
                                        .addComponent(jrb_codigo_barras))
                                    .addComponent(jLabel2))
                                .addContainerGap())))
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrb_titulo)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jrb_ator)
                                .addComponent(jrb_codigo_barras)))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
                jPanel2.setName("jPanel2"); // NOI18N

                jb_cancelar.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
                jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/sair.png"))); // NOI18N
                jb_cancelar.setText("Sair");
                jb_cancelar.setName("jb_cancelar"); // NOI18N
                jb_cancelar.setPreferredSize(new java.awt.Dimension(100, 40));
                jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jb_cancelarActionPerformed(evt);
                    }
                });

                jb_ok.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
                jb_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/finalizar.png"))); // NOI18N
                jb_ok.setText("OK");
                jb_ok.setName("jb_ok"); // NOI18N
                jb_ok.setPreferredSize(new java.awt.Dimension(100, 40));
                jb_ok.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jb_okActionPerformed(evt);
                    }
                });
                jb_ok.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        jb_okKeyPressed(evt);
                    }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jb_ok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(320, 320, 320))
                );
                jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                );

                pack();
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        setVisible(false);
        if ((janelapai != null)) {
            janelapai.setEnabled(true);
            janelapai.setVisible(true);
            //telaCadastroObjeto.setStatusTela(false);
        }

}//GEN-LAST:event_jb_cancelarActionPerformed

    private void jb_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_okActionPerformed
        if (jtbl_copia.getSelectedRow() == 1) {
            botaoOK(jtbl_copia);
        }
}//GEN-LAST:event_jb_okActionPerformed
    public void botaoOK(JTable tb) {
        if (tb.getSelectedRow() != -1) {
            setVisible(false);
            Copia copiaLinha = tbCopiaLinhaSelecionada(jtbl_copia);
            if ((janelapai != null) && (copiaLinha != null)) {
                janelapai.setStatusTela(true);
                janelapai.carregarCopiaLocacao(copiaLinha);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Copia");
        }
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        setVisible(false);
        if ((janelapai != null)) {
            janelapai.setStatusTela(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jtf_consulta.requestFocus();

    }//GEN-LAST:event_formWindowOpened

    private void jb_buscarActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed1
        buscarDados();
    }//GEN-LAST:event_jb_buscarActionPerformed1

    private void jtbl_copiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_copiaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbl_copiaMouseClicked

    private void jrb_codigo_barrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_codigo_barrasActionPerformed
        jtf_consulta.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_codigo_barrasActionPerformed

    private void jrb_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_tituloActionPerformed
        jtf_consulta.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_tituloActionPerformed

    private void jtf_consultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_consultaKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscarDados();
        }
    }//GEN-LAST:event_jtf_consultaKeyPressed

    private void jtbl_copiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbl_copiaKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            botaoOK(jtbl_copia);
        }
        if (evt.getKeyCode() == KeyEvent.VK_F5) {
            jtf_consulta.requestFocus();
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jtbl_copiaKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            setVisible(false);
            if ((janelapai != null)) {
                janelapai.setEnabled(true);
                janelapai.setVisible(true);
                //telaCadastroObjeto.setStatusTela(false);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jrb_atorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_atorActionPerformed
        jtf_consulta.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_atorActionPerformed

    private void jb_okKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_okKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_okKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConsultaCopiaLocacao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_ok;
    private javax.swing.JRadioButton jrb_ator;
    private javax.swing.JRadioButton jrb_codigo_barras;
    private javax.swing.JRadioButton jrb_titulo;
    public static javax.swing.JTable jtbl_copia;
    private javax.swing.JTextField jtf_consulta;
    // End of variables declaration//GEN-END:variables

    public Copia tbCopiaLinhaSelecionada(JTable tb) {
        Copia copiaSelecionada = null;
        if (tb.getSelectedRow() != -1) {
            copiaSelecionada = new Copia();
            copiaSelecionada.setCodigo_copia(copias.get(tb.getSelectedRow()).getCodigo_copia());
            copiaSelecionada.setCodigo_barras(copias.get(tb.getSelectedRow()).getCodigo_barras());
            copiaSelecionada.setIdioma(copias.get(tb.getSelectedRow()).getIdioma());
            copiaSelecionada.setLegenda(copias.get(tb.getSelectedRow()).getLegenda());
            copiaSelecionada.setDiaria(copias.get(tb.getSelectedRow()).getDiaria());
            copiaSelecionada.setObjeto(copias.get(tb.getSelectedRow()).getObjeto());
        }
        return copiaSelecionada;
    }
    private InterfacePool pool;

    public void listaCopia_codigo(Integer codigo_copia) throws SQLException {
        pool = new Pool();
        CopiaDAO copiaDAO = new CopiaDAO(pool);
        copias = null;
        copias = copiaDAO.getCopia(codigo_copia);
        mostraCopia(copias);
    }

    public void listaCopia_titulo(String titulo) throws SQLException {
        pool = new Pool();
        CopiaDAO copiaDAO = new CopiaDAO(pool);
        copias = null;
        copias = copiaDAO.getCopia_titulo(titulo);
        mostraCopia(copias);
    }
    
    public void listaCopia_titulo_original(String titulo) throws SQLException {
        pool = new Pool();
        CopiaDAO copiaDAO = new CopiaDAO(pool);
        copias = null;
        copias = copiaDAO.getCopia_titulo(titulo);
        mostraCopia(copias);
    }

    public void listaCopia_ator(String ator) throws SQLException {
        pool = new Pool();
        CopiaDAO copiaDAO = new CopiaDAO(pool);
        copias = null;
        copias = copiaDAO.getCopia_ator(ator);
        mostraCopia(copias);
    }

    public void listaCopia_codigo_barras(String codigo_barras) {
        pool = new Pool();
        CopiaDAO copiaDAO = new CopiaDAO(pool);
        copias = null;
        copias = copiaDAO.getCopia_codigo_barras(codigo_barras);
        mostraCopia(copias);
    }
    
    public void mostraCopia(List<Copia> copias) {
        ((DefaultTableModel) jtbl_copia.getModel()).setRowCount(0);
        jtbl_copia.updateUI();

        if (copias.size() == 0) {
            JOptionPane.showMessageDialog(this, "Nenhuma copia encontrada");
            jtf_consulta.requestFocus();

        } else {
            for (int i = 0; i < copias.size(); i++) {
                System.out.println("Data Prevista adicionada na tabela: "+ copias.get(i).getData_prevista());
                
                SimpleDateFormat in = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
                String data_prevista = "";
                try {
                    if(copias.get(i).getData_prevista() != null){
                        data_prevista = out.format(in.parse(copias.get(i).getData_prevista().toString()));                        
                    }
                } catch (ParseException ex) {
//                    data_prevista = "";
                }
                
                DefaultTableModel row = (DefaultTableModel) jtbl_copia.getModel();
                ItemDbGrid hashDbGrid = new ItemDbGrid(copias.get(i), copias.get(i).getObjeto().getTitulo());
                row.addRow(new Object[]{ copias.get(i).getCodigo_barras(),
                    hashDbGrid, copias.get(i).getIdioma(), copias.get(i).getLegenda(), copias.get(i).getMidia(),
                    copias.get(i).getObjeto().getTipo_midia(), copias.get(i).getStatus(), data_prevista});

            }
            jtbl_copia.requestFocus();
            jtbl_copia.setSelectionMode(0);
        }
    }

    public String setPrecoFormat(String preco) {
        DecimalFormat dFormat = new DecimalFormat();
        dFormat.applyPattern("R$ #0.00");
        return dFormat.format(getPrecoFormato(preco));
    }

    public Double getPrecoFormato(String preco) {
        Double precoFormatado = 0.0;
        try {
            preco = preco.replace("R", "");
            preco = preco.replace("$", "");
            preco = preco.replace(",", ".");
            preco = preco.replace(" ", "");
            precoFormatado = Double.parseDouble(preco.trim());

            //this.objFuncionario.setSalario(getSalarioFormat(jTSalario.getText())); pegar valor em double
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Valor Informado Incorreto!\nInforme um valor com o seguinte formato:\nEx: 100,00");
        }

        return precoFormatado;
    }
    
    public void acionarAtalho(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            botaoOK(jtbl_copia);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            retornaJanelaPai();
        }
    }

    private void retornaJanelaPai() {
        setVisible(false);
        if(janelapai != null){
            janelapai.setStatusTela(true);
        }            
    }
    
    public void buscarDados(){
                try {
            if (jrb_titulo.isSelected() == true) {
                listaCopia_titulo(jtf_consulta.getText().trim());
            } else if (jrb_codigo_barras.isSelected() == true) {
                listaCopia_codigo_barras(jtf_consulta.getText().trim());
            } else {
                listaCopia_ator(jtf_consulta.getText().trim());
            }
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaCopiaLocacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
