/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultarProdutoGUI.java
 *
 * Created on 02/06/2011, 03:08:41
 */
package br.com.locadora.view;

import br.com.locadora.conexao.InterfacePool;
import br.com.locadora.conexao.Pool;
import br.com.locadora.model.bean.Objeto;
import br.com.locadora.model.dao.ObjetoDAO;
import br.com.locadora.util.ItemDbGrid;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALENCAR
 */
public class ConsultaObjetoLocacao extends javax.swing.JFrame {

    public Atendimento janelapai;
    public Atendimento_InterFace telaAtendimento;
    public List<Objeto> objetos;
    
    public ConsultaObjetoLocacao() {
        initComponents();

        try {
//            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            // UIManager.setLookAndFeel("com.sun.java.swing.plaf.smoothmetal.SmoothmetalLookAndAndFeel");
            //UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            //UIManager.setLookAndFeel(seta_look);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }

        janelapai = null;        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jb_cancelar = new javax.swing.JButton();
        jb_ok = new javax.swing.JButton();
        jb_novo1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jtf_consulta = new javax.swing.JTextField();
        jb_buscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbl_objeto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Consulta Diária");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/exit.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.setName("jb_cancelar"); // NOI18N
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 110, 40));

        jb_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/ok.png"))); // NOI18N
        jb_ok.setText("OK");
        jb_ok.setName("jb_ok"); // NOI18N
        jb_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_okActionPerformed(evt);
            }
        });
        getContentPane().add(jb_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 80, 40));

        jb_novo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/novo_registro.gif"))); // NOI18N
        jb_novo1.setText("Novo");
        jb_novo1.setName("jb_novo1"); // NOI18N
        jb_novo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jb_novo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 110, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta Objeto"));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtf_consulta.setName("jtf_consulta"); // NOI18N
        jPanel1.add(jtf_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 450, -1));

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/ok.png"))); // NOI18N
        jb_buscar.setName("jb_buscar"); // NOI18N
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed1(evt);
            }
        });
        jPanel1.add(jb_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jtbl_objeto.setUpdateSelectionOnSort(false);
        jtbl_objeto.setVerifyInputWhenFocusTarget(false);
        jtbl_objeto.setDefaultEditor(Object.class, null);
        jtbl_objeto.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e){
                if(e.getClickCount() == 2){
                    botaoOK(jtbl_objeto);

                }}});
                jtbl_objeto.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Código", "Nome", "Data Nascimento", "CPF", "Email", "Status"
                    }
                ) {
                    Class[] types = new Class [] {
                        java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                    };
                    boolean[] canEdit = new boolean [] {
                        false, false, false, false, false, false
                    };

                    public Class getColumnClass(int columnIndex) {
                        return types [columnIndex];
                    }

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
                jtbl_objeto.setName("jtbl_objeto"); // NOI18N
                jtbl_objeto.getTableHeader().setReorderingAllowed(false);
                jtbl_objeto.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jtbl_objetoMouseClicked(evt);
                    }
                });
                jScrollPane3.setViewportView(jtbl_objeto);

                jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 688, 210));

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 750, 300));

                setSize(new java.awt.Dimension(836, 438));
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        setVisible(false);
        if ((janelapai != null)) {
            janelapai.setEnabled(true);
            janelapai.setVisible(true);
            //telaCadastroObjeto.setStatusTela(false);
        }

}//GEN-LAST:event_jb_cancelarActionPerformed
    
    private void jb_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_okActionPerformed
        if (jtbl_objeto.getSelectedRow() == 1) {
            botaoOK(jtbl_objeto);
        }
}//GEN-LAST:event_jb_okActionPerformed
    public void botaoOK(JTable tb) {
        if (tb.getSelectedRow() != -1) {
            setVisible(false);
            Objeto objeto = tbObjetoLinhaSelecionada(jtbl_objeto);
            if ((janelapai != null) && (objeto != null)) {
                janelapai.setEnabled(true);
                janelapai.setVisible(true);
//                telaAtendimento.carregaObjeto(objeto);
//                telaAtendimento.setStatusTela(false);
            }

//        if ((janelapai3 != null) && (objeto != null)) {
//            janelapai3.setEnabled(true);
//            janelapai3.setVisible(true);
//            telaAjusteEstoque.carregaFornecedor(objeto);
//            //telaSaidaEstoque.statusTela(true);        
//        }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Objeto");
        }
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        setVisible(false);
        if ((janelapai != null)) {
            janelapai.setEnabled(true);
            janelapai.setVisible(true);
            //telaCadastroObjeto.setStatusTela(false);
        }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jb_novo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novo1ActionPerformed
//        CadastroFornecedor forn;
//
//        forn = new CadastroFornecedor();
//        forn.janelapai2 = this;
//        forn.setVisible(true);
//        this.setEnabled(false);

        // TODO add your handling code here:
}//GEN-LAST:event_jb_novo1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        jt_pesquisar.getColumnModel().getColumn( 3 ).setMaxWidth( 60 );
//        jt_pesquisar.getColumnModel().getColumn( 3 ).setMinWidth( 60 );
//        jt_pesquisar.getTableHeader().getColumnModel().getColumn( 3 ).setMaxWidth( 60 );
//        jt_pesquisar.getTableHeader().getColumnModel().getColumn( 3 ).setMinWidth( 60 );
    }//GEN-LAST:event_formWindowOpened

    private void jb_buscarActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed1
        try {
            listaObjeto(jtf_consulta.getText().trim());
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaObjetoLocacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_buscarActionPerformed1

    private void jtbl_objetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_objetoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbl_objetoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConsultaObjetoLocacao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_novo1;
    private javax.swing.JButton jb_ok;
    public static javax.swing.JTable jtbl_objeto;
    private javax.swing.JTextField jtf_consulta;
    // End of variables declaration//GEN-END:variables

    //Recebendo tela como parametro para atualização apos pesquisa
    public void setTelaAtendimento(Atendimento_InterFace telaAtendimento) {
        this.telaAtendimento = telaAtendimento;
    }

    
    public void setCadastro() {
        jb_novo1.setEnabled(false);
    }

    public Objeto tbObjetoLinhaSelecionada(JTable tb) {
        Objeto objeto = null;
        if (tb.getSelectedRow() != -1) {
            objeto = new Objeto();
            objeto.setCodigo_objeto(objetos.get(tb.getSelectedRow()).getCodigo_objeto());
            objeto.setDescricao_objeto(objetos.get(tb.getSelectedRow()).getDescricao_objeto());            
        }
        return objeto;
    }
    private InterfacePool pool;

    public void listaObjeto(String consulta) throws SQLException {
        pool = new Pool();
        ObjetoDAO objetoDAO = new ObjetoDAO(pool);
//        objetos = objetoDAO.getObjetos_nome("%" + jtf_consulta.getText().trim() + "%");
//        mostraObjeto(objetos);
    }

    public void listaTodasObjetos() throws SQLException {
        pool = new Pool();
        ObjetoDAO objetoDAO = new ObjetoDAO(pool);
//        objetos = objetoDAO.getTodasObjetos();
//        mostraObjeto(objetos);
    }

//    public void mostraObjeto(List<Objeto> objetos) {
//        ((DefaultTableModel) jtbl_objeto.getModel()).setRowCount(0);
//        jtbl_objeto.updateUI();
//
//        if (objetos.size() == 0) {
//            JOptionPane.showMessageDialog(this, "Nenhuma objeto encontrada");
//
//        } else {
//            for (int i = 0; i < objetos.size(); i++) {
//
//                Objeto objeto = new Objeto();
//                objeto.setCodigo_objeto(objetos.get(i).getCodigo_objeto());
//                objeto.setNome_objeto(objetos.get(i).getNome_objeto());
//                objeto.setCpf(objetos.get(i).getCpf());
//                objeto.setEmail(objetos.get(i).getEmail());
//                if(objetos.get(i).getStatus() == "A"){
//                    objeto.setStatus("Ativo");
//                }else{
//                    objeto.setStatus("Inativo");
//                }
//                objeto.setStatus(objetos.get(i).getStatus());
//
//                SimpleDateFormat in = new SimpleDateFormat("yyyy-MM-dd");
//                SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
//                
//                String data_nascimento = null;
//                try {
//                    data_nascimento = out.format(in.parse(objetos.get(i).getData_nascimento().toString()));
//                } catch (ParseException ex) {
//                    Logger.getLogger(ConsultaObjetoLocacao.class.getName()).log(Level.SEVERE, null, ex);
//                }
//                
//                DefaultTableModel row = (DefaultTableModel) jtbl_objeto.getModel();
//                ItemDbGrid hashDbGrid = new ItemDbGrid(objeto, objeto.getNome_objeto());
//                row.addRow(new Object[]{objeto.getCodigo_objeto(), hashDbGrid, data_nascimento, objeto.getCpf(), objeto.getEmail(), objeto.getStatus()});
//                
//            }
//            jtbl_objeto.setSelectionMode(1);
//        }
//    }

    public String setPrecoFormat(String preco) {
        DecimalFormat dFormat = new DecimalFormat();
        dFormat.applyPattern("R$ #0.00");
        return dFormat.format(getPrecoFormato(preco));
    }

    public Double getPrecoFormato(String preco) {
        Double precoFormatado = 0.0;
        try {
            preco = preco.replace("R", "");
            preco = preco.replace("$", "");
            preco = preco.replace(",", ".");
            preco = preco.replace(" ", "");
            precoFormatado = Double.parseDouble(preco.trim());

            //this.objFuncionario.setSalario(getSalarioFormat(jTSalario.getText())); pegar valor em double
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Valor Informado Incorreto!\nInforme um valor com o seguinte formato:\nEx: 100,00");
        }

        return precoFormatado;
    }

}
