/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultarProdutoGUI.java
 *
 * Created on 02/06/2011, 03:08:41
 */
package br.com.locadora.view;

import br.com.locadora.conexao.InterfacePool;
import br.com.locadora.conexao.Pool;
import br.com.locadora.model.bean.Cliente;
import br.com.locadora.model.bean.Dependente;
import br.com.locadora.model.dao.ClienteDAO;
import br.com.locadora.model.dao.DependenteDAO;
import br.com.locadora.util.ItemDbGrid;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALENCAR
 */
public class ConsultaClienteAtendimento extends javax.swing.JFrame {

    public AtendimentoLocacao janelapaiLocacao;
    public AtendimentoDevolucao janelapaiDevolucao;
    public AtendimentoLocacao_InterFace telaAtendimentoLocacao;
    public AtendimentoDevolucao_InterFace telaAtendimentoDevolucao;
    public List<Cliente> clientes;
    public List<Dependente> dependentes;

    public ConsultaClienteAtendimento() {
        initComponents();
        janelapaiLocacao = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jb_cancelar = new javax.swing.JButton();
        jb_ok = new javax.swing.JButton();
        jb_novo1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jtf_consulta = new javax.swing.JTextField();
        jb_buscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbl_cliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Consulta Cliente");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/exit.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.setName("jb_cancelar"); // NOI18N
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 110, 40));

        jb_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/ok.png"))); // NOI18N
        jb_ok.setText("OK");
        jb_ok.setName("jb_ok"); // NOI18N
        jb_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_okActionPerformed(evt);
            }
        });
        getContentPane().add(jb_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 80, 40));

        jb_novo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/novo_registro.gif"))); // NOI18N
        jb_novo1.setText("Novo");
        jb_novo1.setName("jb_novo1"); // NOI18N
        jb_novo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jb_novo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 110, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta Cliente/Dependente"));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtf_consulta.setName("jtf_consulta"); // NOI18N
        jtf_consulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_consultaKeyPressed(evt);
            }
        });
        jPanel1.add(jtf_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 640, -1));

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/ok.png"))); // NOI18N
        jb_buscar.setName("jb_buscar"); // NOI18N
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed1(evt);
            }
        });
        jPanel1.add(jb_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jtbl_cliente.setUpdateSelectionOnSort(false);
        jtbl_cliente.setVerifyInputWhenFocusTarget(false);
        jtbl_cliente.setDefaultEditor(Object.class, null);
        jtbl_cliente.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e){
                if(e.getClickCount() == 2){
                    botaoOK(jtbl_cliente);

                }}});
                jtbl_cliente.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Código Cliente", "Nome do Cliente/Dependente", "Situação", "Tipo do Cliente", "Código Dependente"
                    }
                ) {
                    Class[] types = new Class [] {
                        java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                    };
                    boolean[] canEdit = new boolean [] {
                        false, false, false, false, false
                    };

                    public Class getColumnClass(int columnIndex) {
                        return types [columnIndex];
                    }

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
                jtbl_cliente.setName("jtbl_cliente"); // NOI18N
                jtbl_cliente.getTableHeader().setReorderingAllowed(false);
                jtbl_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jtbl_clienteMouseClicked(evt);
                    }
                });
                jtbl_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        jtbl_clienteKeyPressed(evt);
                    }
                });
                jScrollPane3.setViewportView(jtbl_cliente);
                if (jtbl_cliente.getColumnModel().getColumnCount() > 0) {
                    jtbl_cliente.getColumnModel().getColumn(0).setResizable(false);
                    jtbl_cliente.getColumnModel().getColumn(0).setPreferredWidth(20);
                    jtbl_cliente.getColumnModel().getColumn(1).setPreferredWidth(150);
                    jtbl_cliente.getColumnModel().getColumn(3).setPreferredWidth(20);
                    jtbl_cliente.getColumnModel().getColumn(4).setPreferredWidth(20);
                }

                jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 710, 210));

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 280));

                setSize(new java.awt.Dimension(751, 367));
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        setVisible(false);
        if ((janelapaiLocacao != null)) {
            janelapaiLocacao.setEnabled(true);
            janelapaiLocacao.setVisible(true);
            //telaCadastroObjeto.setStatusTela(false);
        }

}//GEN-LAST:event_jb_cancelarActionPerformed

    private void jb_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_okActionPerformed
        JOptionPane.showMessageDialog(null, jtbl_cliente.getSelectedRow());
        if (jtbl_cliente.getSelectedRow() == 1) {
            botaoOK(jtbl_cliente);
        }
}//GEN-LAST:event_jb_okActionPerformed
    public void botaoOK(JTable tb) {
        Dependente dependente = tbClienteDependenteLinhaSelecionada(jtbl_cliente);
        if ((janelapaiLocacao != null) && (dependente != null)) {
            janelapaiLocacao.setEnabled(true);
            janelapaiLocacao.setVisible(true);
            telaAtendimentoLocacao.carregarClienteDependente(dependente);
            telaAtendimentoLocacao.setStatusTela(true);
        } else if ((janelapaiDevolucao != null) && (dependente != null)) {
            janelapaiDevolucao.setEnabled(true);
            janelapaiDevolucao.setVisible(true);
            telaAtendimentoDevolucao.carregarClienteDependente(dependente);
            telaAtendimentoDevolucao.setStatusTela(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Cliente");
        }

    }


    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        setVisible(false);
        if ((janelapaiLocacao != null)) {
            janelapaiLocacao.setEnabled(true);
            janelapaiLocacao.setVisible(true);
            //telaCadastroObjeto.setStatusTela(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jb_novo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novo1ActionPerformed
}//GEN-LAST:event_jb_novo1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        listaClienteDependente();
        jtbl_cliente.requestFocus();
        jtbl_cliente.setSelectionMode(1);

    }//GEN-LAST:event_formWindowOpened

    private void jb_buscarActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed1
        listaClienteDependente();
    }//GEN-LAST:event_jb_buscarActionPerformed1

    private void jtbl_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_clienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbl_clienteMouseClicked

    private void jtf_consultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_consultaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            listaClienteDependente();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_consultaKeyPressed

    private void jtbl_clienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbl_clienteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            botaoOK(jtbl_cliente);
        }
    }//GEN-LAST:event_jtbl_clienteKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            setVisible(false);
            if ((janelapaiLocacao != null)) {
                janelapaiLocacao.setEnabled(true);
                janelapaiLocacao.setVisible(true);
                //telaCadastroObjeto.setStatusTela(false);
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConsultaClienteAtendimento().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_novo1;
    private javax.swing.JButton jb_ok;
    public static javax.swing.JTable jtbl_cliente;
    public static javax.swing.JTextField jtf_consulta;
    // End of variables declaration//GEN-END:variables

    //Recebendo tela como parametro para atualização apos pesquisa
    public void setTelaAtendimento(AtendimentoLocacao_InterFace telaAtendimentoLocacao) {
        this.telaAtendimentoLocacao = telaAtendimentoLocacao;
    }
    
    public void setTelaAtendimento(AtendimentoDevolucao_InterFace telaAtendimentoDevolucao) {
        this.telaAtendimentoDevolucao = telaAtendimentoDevolucao;
    }

    public void setCadastro() {
        jb_novo1.setEnabled(false);
    }

    public Dependente tbClienteDependenteLinhaSelecionada(JTable tb) {
        Dependente dependente = null;

        if (tb.getSelectedRow() != -1) {
            dependente = new Dependente();

            dependente.setCodigo_dependente(dependentes.get(tb.getSelectedRow()).getCodigo_dependente());
            dependente.setNome_dependente(dependentes.get(tb.getSelectedRow()).getNome_dependente());
            dependente.setDebito(dependentes.get(tb.getSelectedRow()).getDebito());

            Cliente cliente = new Cliente();
            cliente.setCodigo_cliente(dependentes.get(tb.getSelectedRow()).getCliente().getCodigo_cliente());

            dependente.setCliente(cliente);
        }
        return dependente;
    }
    private InterfacePool pool;

    public void listaClienteDependente() {
        try {
            pool = new Pool();
            DependenteDAO dependenteDAO = new DependenteDAO(pool);
            dependentes = dependenteDAO.getClienteDependente("%" + jtf_consulta.getText().trim() + "%");
            mostraClienteDependente(dependentes);
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaClienteAtendimento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void listaTodasClientes() throws SQLException {
        pool = new Pool();
        ClienteDAO clienteDAO = new ClienteDAO(pool);
//        clientes = clienteDAO.getTodasClientes();
//        mostraClienteDependente(clientes);
    }

    public void mostraClienteDependente(List<Dependente> dependentes) {
        ((DefaultTableModel) jtbl_cliente.getModel()).setRowCount(0);
        jtbl_cliente.updateUI();

        if (dependentes.size() == 0) {
            JOptionPane.showMessageDialog(this, "Nenhuma cliente encontrada");

        } else {
            for (int i = 0; i < dependentes.size(); i++) {

                DefaultTableModel row = (DefaultTableModel) jtbl_cliente.getModel();
                ItemDbGrid hashDbGrid = new ItemDbGrid(dependentes.get(i), dependentes.get(i).getNome_dependente());
                row.addRow(new Object[]{dependentes.get(i).getCliente().getCodigo_cliente(), hashDbGrid, dependentes.get(i).getCliente().getStatus(),
                    dependentes.get(i).getTipo_dependente(), dependentes.get(i).getCodigo_dependente()});
            }
            jtbl_cliente.requestFocus();
            jtbl_cliente.setRowSelectionInterval(0, 0);
        }
    }

}
