/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultarProdutoGUI.java
 *
 * Created on 02/06/2011, 03:08:41
 */
package br.com.locadora.view;

import br.com.locadora.conexao.InterfacePool;
import br.com.locadora.conexao.Pool;
import br.com.locadora.model.bean.Copia;
import br.com.locadora.model.bean.FornecedorModel;
import br.com.locadora.model.dao.CopiaDAO;
import br.com.locadora.model.dao.FornecedorDAO;
import br.com.locadora.util.ItemDbGrid;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALENCAR
 */
public class ConsultaCopiaAtendimento extends javax.swing.JFrame {

    public Atendimento janelapai;
    public Atendimento_InterFace telaAtendimento;
    public List<Copia> copias;
    public Copia copia;

    public ConsultaCopiaAtendimento() {
        initComponents();

        try {
//            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            // UIManager.setLookAndFeel("com.sun.java.swing.plaf.smoothmetal.SmoothmetalLookAndAndFeel");
            //UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            //UIManager.setLookAndFeel(seta_look);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }

        janelapai = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jb_cancelar = new javax.swing.JButton();
        jb_ok = new javax.swing.JButton();
        jb_novo1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jtf_consulta = new javax.swing.JTextField();
        jb_buscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbl_copia = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Consulta Objeto");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/exit.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.setName("jb_cancelar"); // NOI18N
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 110, 40));

        jb_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/ok.png"))); // NOI18N
        jb_ok.setText("OK");
        jb_ok.setName("jb_ok"); // NOI18N
        jb_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_okActionPerformed(evt);
            }
        });
        getContentPane().add(jb_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 80, 40));

        jb_novo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/novo_registro.gif"))); // NOI18N
        jb_novo1.setText("Novo");
        jb_novo1.setName("jb_novo1"); // NOI18N
        jb_novo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jb_novo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 110, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta Objeto"));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtf_consulta.setName("jtf_consulta"); // NOI18N
        jPanel1.add(jtf_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 450, -1));

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/ok.png"))); // NOI18N
        jb_buscar.setName("jb_buscar"); // NOI18N
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed1(evt);
            }
        });
        jPanel1.add(jb_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jtbl_copia.setUpdateSelectionOnSort(false);
        jtbl_copia.setVerifyInputWhenFocusTarget(false);
        jtbl_copia.setDefaultEditor(Object.class, null);
        jtbl_copia.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e){
                if(e.getClickCount() == 2){
                    botaoOK(jtbl_copia);

                }}});
                jtbl_copia.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Código", "Código Interno", "Localização", "Descrição Objeto", "Idioma", "Legenda", "Tipo Mídia", "Status"
                    }
                ) {
                    Class[] types = new Class [] {
                        java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                    };
                    boolean[] canEdit = new boolean [] {
                        false, false, false, false, false, false, false, false
                    };

                    public Class getColumnClass(int columnIndex) {
                        return types [columnIndex];
                    }

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
                jtbl_copia.setName("jtbl_copia"); // NOI18N
                jtbl_copia.getTableHeader().setReorderingAllowed(false);
                jtbl_copia.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jtbl_copiaMouseClicked(evt);
                    }
                });
                jScrollPane3.setViewportView(jtbl_copia);
                if (jtbl_copia.getColumnModel().getColumnCount() > 0) {
                    jtbl_copia.getColumnModel().getColumn(0).setPreferredWidth(20);
                    jtbl_copia.getColumnModel().getColumn(3).setPreferredWidth(100);
                    jtbl_copia.getColumnModel().getColumn(7).setPreferredWidth(20);
                }

                jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 760, 210));

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 810, 300));

                setSize(new java.awt.Dimension(862, 438));
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        setVisible(false);
        if ((janelapai != null)) {
            janelapai.setEnabled(true);
            janelapai.setVisible(true);
            //telaCadastroObjeto.setStatusTela(false);
        }

}//GEN-LAST:event_jb_cancelarActionPerformed

    private void jb_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_okActionPerformed
        if (jtbl_copia.getSelectedRow() == 1) {
            botaoOK(jtbl_copia);
        }
}//GEN-LAST:event_jb_okActionPerformed
    public void botaoOK(JTable tb) {
        if (tb.getSelectedRow() != -1) {
            setVisible(false);
            Copia copiaLinha = tbCopiaLinhaSelecionada(jtbl_copia);
            if ((janelapai != null) && (copiaLinha != null)) {
                janelapai.setEnabled(true);
                janelapai.setVisible(true);
                telaAtendimento.carregaCopia(copiaLinha);
//                telaAtendimento.setStatusTela(false);
            }

//        if ((janelapai3 != null) && (copia != null)) {
//            janelapai3.setEnabled(true);
//            janelapai3.setVisible(true);
//            telaAjusteEstoque.carregaFornecedor(copia);
//            //telaSaidaEstoque.statusTela(true);        
//        }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Copia");
        }
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        setVisible(false);
        if ((janelapai != null)) {
            janelapai.setEnabled(true);
            janelapai.setVisible(true);
            //telaCadastroObjeto.setStatusTela(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jb_novo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novo1ActionPerformed
//        CadastroFornecedor forn;
//
//        forn = new CadastroFornecedor();
//        forn.janelapai2 = this;
//        forn.setVisible(true);
//        this.setEnabled(false);

        // TODO add your handling code here:
}//GEN-LAST:event_jb_novo1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        jt_pesquisar.getColumnModel().getColumn( 3 ).setMaxWidth( 60 );
//        jt_pesquisar.getColumnModel().getColumn( 3 ).setMinWidth( 60 );
//        jt_pesquisar.getTableHeader().getColumnModel().getColumn( 3 ).setMaxWidth( 60 );
//        jt_pesquisar.getTableHeader().getColumnModel().getColumn( 3 ).setMinWidth( 60 );
    }//GEN-LAST:event_formWindowOpened

    private void jb_buscarActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed1

        try {
            listaCopia_codigo(Integer.parseInt(jtf_consulta.getText().trim()));
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaCopiaAtendimento.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jb_buscarActionPerformed1

    private void jtbl_copiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_copiaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbl_copiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConsultaCopiaAtendimento().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_novo1;
    private javax.swing.JButton jb_ok;
    public static javax.swing.JTable jtbl_copia;
    private javax.swing.JTextField jtf_consulta;
    // End of variables declaration//GEN-END:variables

    //Recebendo tela como parametro para atualização apos pesquisa
    public void setTelaAtendimento(Atendimento_InterFace telaAtendimento) {
        this.telaAtendimento = telaAtendimento;
    }

    public void setCadastro() {
        jb_novo1.setEnabled(false);
    }

    public Copia tbCopiaLinhaSelecionada(JTable tb) {
        Copia copiaSelecionada = null;
        if (tb.getSelectedRow() != -1) {
            copiaSelecionada = new Copia();
            copiaSelecionada.setCodigo_copia(copias.get(tb.getSelectedRow()).getCodigo_copia());
            copiaSelecionada.setCodigo_interno(copias.get(tb.getSelectedRow()).getCodigo_interno());
            copiaSelecionada.setLocalizacao(copias.get(tb.getSelectedRow()).getLocalizacao());
            copiaSelecionada.setIdioma(copias.get(tb.getSelectedRow()).getIdioma());
            copiaSelecionada.setLegenda(copias.get(tb.getSelectedRow()).getLegenda());
            copiaSelecionada.setObjeto(copias.get(tb.getSelectedRow()).getObjeto());                
        }
        return copiaSelecionada;
    }
    private InterfacePool pool;

    public void listaCopia_codigo(Integer codigo_copia) throws SQLException {
        pool = new Pool();
        CopiaDAO copiaDAO = new CopiaDAO(pool);
        copias = null;
        copias = copiaDAO.getCopia(codigo_copia);
        mostraCopia(copias);
    }

    public void listaTodasCopias() throws SQLException {
        pool = new Pool();
        CopiaDAO copiaDAO = new CopiaDAO(pool);
//        copias = copiaDAO.getTodasCopias();
//        mostraCopia(copias);
    }

    public void mostraCopia(List<Copia> copias) {
        ((DefaultTableModel) jtbl_copia.getModel()).setRowCount(0);
        jtbl_copia.updateUI();

        if (copias.size() == 0) {
            JOptionPane.showMessageDialog(this, "Nenhuma copia encontrada");

        } else {
            for (int i = 0; i < copias.size(); i++) {
                Copia copia = new Copia();
                
                copia.setCodigo_copia(copias.get(i).getCodigo_copia());
                copia.setCodigo_interno(copias.get(i).getCodigo_interno());
                copia.setLocalizacao(copias.get(i).getLocalizacao());
                copia.setIdioma(copias.get(i).getIdioma());
                copia.setLegenda(copias.get(i).getLegenda());
                copia.setObjeto(copias.get(i).getObjeto());

                DefaultTableModel row = (DefaultTableModel) jtbl_copia.getModel();
                ItemDbGrid hashDbGrid = new ItemDbGrid(copia, copia.getObjeto().getDescricao_objeto());
                row.addRow(new Object[]{copia.getCodigo_copia(), copia.getCodigo_interno(),
                    copia.getLocalizacao(), hashDbGrid, copia.getIdioma(), copia.getLegenda(),
                    copia.getObjeto().getTipo_midia(), copia.getStatus()});

            }
        }
        jtbl_copia.setSelectionMode(1);
    }

    public String setPrecoFormat(String preco) {
        DecimalFormat dFormat = new DecimalFormat();
        dFormat.applyPattern("R$ #0.00");
        return dFormat.format(getPrecoFormato(preco));
    }

    public Double getPrecoFormato(String preco) {
        Double precoFormatado = 0.0;
        try {
            preco = preco.replace("R", "");
            preco = preco.replace("$", "");
            preco = preco.replace(",", ".");
            preco = preco.replace(" ", "");
            precoFormatado = Double.parseDouble(preco.trim());

            //this.objFuncionario.setSalario(getSalarioFormat(jTSalario.getText())); pegar valor em double
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Valor Informado Incorreto!\nInforme um valor com o seguinte formato:\nEx: 100,00");
        }

        return precoFormatado;
    }

}
