/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultarProdutoGUI.java
 *
 * Created on 02/06/2011, 03:08:41
 */
package br.com.locadora.view;

import br.com.locadora.conexao.InterfacePool;
import br.com.locadora.conexao.Pool;
import br.com.locadora.model.bean.Copia;
import br.com.locadora.model.dao.CopiaDAO;
import br.com.locadora.util.ItemDbGrid;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALENCAR
 */
public class ConsultaCopiaLocacao extends javax.swing.JFrame {

    public AtendimentoLocacao janelapai;   
    public List<Copia> copias;
    public Copia copia;

    public ConsultaCopiaLocacao() {
        initComponents();
        janelapai = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jb_cancelar = new javax.swing.JButton();
        jb_ok = new javax.swing.JButton();
        jb_novo1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jtf_consulta = new javax.swing.JTextField();
        jb_buscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbl_copia = new javax.swing.JTable();
        jrb_ator = new javax.swing.JRadioButton();
        jrb_codigo_barras = new javax.swing.JRadioButton();
        jrb_titulo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Objeto");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/exit.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.setName("jb_cancelar"); // NOI18N
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 110, 40));

        jb_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/ok.png"))); // NOI18N
        jb_ok.setText("OK");
        jb_ok.setName("jb_ok"); // NOI18N
        jb_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_okActionPerformed(evt);
            }
        });
        getContentPane().add(jb_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 80, 40));

        jb_novo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/novo_registro.gif"))); // NOI18N
        jb_novo1.setText("Novo");
        jb_novo1.setName("jb_novo1"); // NOI18N
        jb_novo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jb_novo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 110, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta Objeto"));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtf_consulta.setName("jtf_consulta"); // NOI18N
        jtf_consulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_consultaKeyPressed(evt);
            }
        });
        jPanel1.add(jtf_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 450, -1));

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/ok.png"))); // NOI18N
        jb_buscar.setName("jb_buscar"); // NOI18N
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed1(evt);
            }
        });
        jPanel1.add(jb_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jtbl_copia.setUpdateSelectionOnSort(false);
        jtbl_copia.setVerifyInputWhenFocusTarget(false);
        jtbl_copia.setDefaultEditor(Object.class, null);
        jtbl_copia.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e){
                if(e.getClickCount() == 2){
                    botaoOK(jtbl_copia);

                }}});
                jtbl_copia.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Código", "Código de Barras", "Descrição Objeto", "Idioma", "Legenda", "Tipo Mídia", "Livre", "Data Prevista", "Situação"
                    }
                ) {
                    Class[] types = new Class [] {
                        java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
                    };
                    boolean[] canEdit = new boolean [] {
                        false, false, false, false, false, false, false, true, true
                    };

                    public Class getColumnClass(int columnIndex) {
                        return types [columnIndex];
                    }

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
                jtbl_copia.setName("jtbl_copia"); // NOI18N
                jtbl_copia.getTableHeader().setReorderingAllowed(false);
                jtbl_copia.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jtbl_copiaMouseClicked(evt);
                    }
                });
                jtbl_copia.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        jtbl_copiaKeyPressed(evt);
                    }
                });
                jScrollPane3.setViewportView(jtbl_copia);
                if (jtbl_copia.getColumnModel().getColumnCount() > 0) {
                    jtbl_copia.getColumnModel().getColumn(0).setPreferredWidth(20);
                    jtbl_copia.getColumnModel().getColumn(1).setPreferredWidth(100);
                    jtbl_copia.getColumnModel().getColumn(2).setPreferredWidth(100);
                    jtbl_copia.getColumnModel().getColumn(6).setPreferredWidth(20);
                }

                jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 760, 210));

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 780, 280));

                buttonGroup1.add(jrb_ator);
                jrb_ator.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
                jrb_ator.setText("Ator");
                jrb_ator.setName("jrb_ator"); // NOI18N
                jrb_ator.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jrb_atorActionPerformed(evt);
                    }
                });
                getContentPane().add(jrb_ator, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

                buttonGroup1.add(jrb_codigo_barras);
                jrb_codigo_barras.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
                jrb_codigo_barras.setText("Código de Barras");
                jrb_codigo_barras.setName("jrb_codigo_barras"); // NOI18N
                jrb_codigo_barras.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jrb_codigo_barrasActionPerformed(evt);
                    }
                });
                getContentPane().add(jrb_codigo_barras, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

                buttonGroup1.add(jrb_titulo);
                jrb_titulo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
                jrb_titulo.setSelected(true);
                jrb_titulo.setText("Título");
                jrb_titulo.setName("jrb_titulo"); // NOI18N
                jrb_titulo.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jrb_tituloActionPerformed(evt);
                    }
                });
                getContentPane().add(jrb_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

                setSize(new java.awt.Dimension(800, 393));
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        setVisible(false);
        if ((janelapai != null)) {
            janelapai.setEnabled(true);
            janelapai.setVisible(true);
            //telaCadastroObjeto.setStatusTela(false);
        }

}//GEN-LAST:event_jb_cancelarActionPerformed

    private void jb_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_okActionPerformed
        if (jtbl_copia.getSelectedRow() == 1) {
            botaoOK(jtbl_copia);
        }
}//GEN-LAST:event_jb_okActionPerformed
    public void botaoOK(JTable tb) {
        if (tb.getSelectedRow() != -1) {
            setVisible(false);
            Copia copiaLinha = tbCopiaLinhaSelecionada(jtbl_copia);
            if ((janelapai != null) && (copiaLinha != null)) {
                janelapai.setStatusTela(true);
                janelapai.carregarCopiaLocacao(copiaLinha);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Copia");
        }
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        setVisible(false);
        if ((janelapai != null)) {
            janelapai.setStatusTela(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jb_novo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novo1ActionPerformed
}//GEN-LAST:event_jb_novo1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jtf_consulta.requestFocus();
                
    }//GEN-LAST:event_formWindowOpened

    private void jb_buscarActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed1
        try {
             if (jrb_titulo.isSelected() == true) {
                listaCopia_titulo(jtf_consulta.getText().trim());
            } else if (jrb_codigo_barras.isSelected() == true) {
                listaCopia_codigo_barras(jtf_consulta.getText().trim());
            } else {
                listaCopia_ator(jtf_consulta.getText().trim());
            }
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaCopiaLocacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_buscarActionPerformed1

    private void jtbl_copiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_copiaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbl_copiaMouseClicked

    private void jrb_codigo_barrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_codigo_barrasActionPerformed
        jtf_consulta.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_codigo_barrasActionPerformed

    private void jrb_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_tituloActionPerformed
        jtf_consulta.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_tituloActionPerformed

    private void jtf_consultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_consultaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                 if (jrb_titulo.isSelected() == true) {
                    listaCopia_titulo(jtf_consulta.getText().trim());
                } else if (jrb_codigo_barras.isSelected() == true) {
                    listaCopia_codigo_barras(jtf_consulta.getText().trim());
                } else {
                    listaCopia_ator(jtf_consulta.getText().trim());
                }
            } catch (SQLException ex) {
                Logger.getLogger(ConsultaCopiaLocacao.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
    }//GEN-LAST:event_jtf_consultaKeyPressed

    private void jtbl_copiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbl_copiaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            botaoOK(jtbl_copia);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbl_copiaKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            setVisible(false);
            if ((janelapai != null)) {
                janelapai.setEnabled(true);
                janelapai.setVisible(true);
                //telaCadastroObjeto.setStatusTela(false);
            }            
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jrb_atorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_atorActionPerformed
        jtf_consulta.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_atorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConsultaCopiaLocacao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_novo1;
    private javax.swing.JButton jb_ok;
    private javax.swing.JRadioButton jrb_ator;
    private javax.swing.JRadioButton jrb_codigo_barras;
    private javax.swing.JRadioButton jrb_titulo;
    public static javax.swing.JTable jtbl_copia;
    private javax.swing.JTextField jtf_consulta;
    // End of variables declaration//GEN-END:variables
    
    public void setCadastro() {
        jb_novo1.setEnabled(false);
    }

    public Copia tbCopiaLinhaSelecionada(JTable tb) {
        Copia copiaSelecionada = null;
        if (tb.getSelectedRow() != -1) {
            copiaSelecionada = new Copia();
            copiaSelecionada.setCodigo_copia(copias.get(tb.getSelectedRow()).getCodigo_copia());
            copiaSelecionada.setCodigo_barras(copias.get(tb.getSelectedRow()).getCodigo_barras());
            copiaSelecionada.setIdioma(copias.get(tb.getSelectedRow()).getIdioma());
            copiaSelecionada.setLegenda(copias.get(tb.getSelectedRow()).getLegenda());
            copiaSelecionada.setObjeto(copias.get(tb.getSelectedRow()).getObjeto());
        }
        return copiaSelecionada;
    }
    private InterfacePool pool;

    public void listaCopia_codigo(Integer codigo_copia) throws SQLException {
        pool = new Pool();
        CopiaDAO copiaDAO = new CopiaDAO(pool);
        copias = null;
        copias = copiaDAO.getCopia(codigo_copia);
        mostraCopia(copias);
    }

    public void listaCopia_titulo(String titulo) throws SQLException {
        pool = new Pool();
        CopiaDAO copiaDAO = new CopiaDAO(pool);
        copias = null;
        copias = copiaDAO.getCopia_titulo(titulo);
        mostraCopia(copias);
    }

    public void listaCopia_ator(String ator) throws SQLException {
        pool = new Pool();
        CopiaDAO copiaDAO = new CopiaDAO(pool);
        copias = null;
        copias = copiaDAO.getCopia_ator(ator);
        mostraCopia(copias);
    }

    public void listaCopia_codigo_barras(String codigo_barras) {
        pool = new Pool();
        CopiaDAO copiaDAO = new CopiaDAO(pool);
        copias = null;
        copias = copiaDAO.getCopia_codigo_barras(codigo_barras);
        mostraCopia(copias);
    }
    
    public void listaTodasCopias() throws SQLException {
        pool = new Pool();
        CopiaDAO copiaDAO = new CopiaDAO(pool);
//        copias = copiaDAO.getTodasCopias();
//        mostraCopia(copias);
    }

    public void mostraCopia(List<Copia> copias) {
        ((DefaultTableModel) jtbl_copia.getModel()).setRowCount(0);
        jtbl_copia.updateUI();

        if (copias.size() == 0) {
            JOptionPane.showMessageDialog(this, "Nenhuma copia encontrada");

        } else {
            for (int i = 0; i < copias.size(); i++) {
                Copia copia = new Copia();

                copia.setCodigo_copia(copias.get(i).getCodigo_copia());

                copia.setIdioma(copias.get(i).getIdioma());
                copia.setLegenda(copias.get(i).getLegenda());
                copia.setObjeto(copias.get(i).getObjeto());
                copia.setCodigo_barras(copias.get(i).getCodigo_barras());

                DefaultTableModel row = (DefaultTableModel) jtbl_copia.getModel();
                ItemDbGrid hashDbGrid = new ItemDbGrid(copia, copia.getObjeto().getDescricao_objeto());
                row.addRow(new Object[]{copia.getCodigo_copia(), copia.getCodigo_barras(),
                    hashDbGrid, copia.getIdioma(), copia.getLegenda(),
                    copia.getObjeto().getTipo_midia(), copia.getStatus()});

            }
        }
        jtbl_copia.requestFocus();
        jtbl_copia.setSelectionMode(1);
    }

    public String setPrecoFormat(String preco) {
        DecimalFormat dFormat = new DecimalFormat();
        dFormat.applyPattern("R$ #0.00");
        return dFormat.format(getPrecoFormato(preco));
    }

    public Double getPrecoFormato(String preco) {
        Double precoFormatado = 0.0;
        try {
            preco = preco.replace("R", "");
            preco = preco.replace("$", "");
            preco = preco.replace(",", ".");
            preco = preco.replace(" ", "");
            precoFormatado = Double.parseDouble(preco.trim());

            //this.objFuncionario.setSalario(getSalarioFormat(jTSalario.getText())); pegar valor em double
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Valor Informado Incorreto!\nInforme um valor com o seguinte formato:\nEx: 100,00");
        }

        return precoFormatado;
    }

}
