package br.com.locadora.view;

import br.com.locadora.conexao.InterfacePool;
import br.com.locadora.conexao.Pool;
import br.com.locadora.controller.SiscomController;
import br.com.locadora.model.bean.AcessoUsuario;
import br.com.locadora.model.bean.Copia;
import br.com.locadora.model.bean.Dependente;
import br.com.locadora.model.bean.ItemLocacao;
import br.com.locadora.model.bean.Lancamento;
import br.com.locadora.model.bean.Locacao;
import br.com.locadora.model.bean.TipoServico;
import br.com.locadora.model.bean.Usuario;
import br.com.locadora.model.dao.CopiaDAO;
import br.com.locadora.model.dao.DevolucaoDAO;
import br.com.locadora.model.dao.LocacaoDAO;
import br.com.locadora.model.dao.UsuarioDAO;
import br.com.locadora.util.ArquivoConfiguracao;
import br.com.locadora.util.Printer;
import br.com.locadora.util.LimitadorTexto;
import br.com.locadora.util.Moeda;
import br.com.locadora.util.TemaInterface;
import br.com.locadora.util.UnaccentedDocument;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALENCAR
 */
public final class EntradaCaixaDevolucao extends javax.swing.JFrame {

    public AtendimentoDevolucao janelapaiDevolucao;
    public InterfacePool pool;
    public SiscomController controller;
    public String action;
    public static List<ItemLocacao> itens;

    /**
     * Creates new form ProdutoCadastroGUI
     */
    public EntradaCaixaDevolucao() {
        initComponents();
        TemaInterface.getInterface(this);
        janelapaiDevolucao = null;
    }

    //public ProdutoConsultarGUI janelapaim;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tfa_similar = new javax.swing.JTextArea();
        jb_imprimir = new javax.swing.JButton();
        jb_salvar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jtf_login = new javax.swing.JTextField();
        jpf_senha = new javax.swing.JPasswordField();
        jb_logar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtf_total_relocacao = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtf_troco = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jtf_debito_atual = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_total_a_pagar = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jLabel6 = new javax.swing.JLabel();
        jtf_valor_pago = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jtf_desconto_entrega_antecipada = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_debito_total_anterior = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jLabel5 = new javax.swing.JLabel();
        jtf_desconto = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jb_cancelar1 = new javax.swing.JButton();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tfa_similar.setColumns(20);
        tfa_similar.setRows(5);
        tfa_similar.setName("tfa_similar"); // NOI18N
        jScrollPane1.setViewportView(tfa_similar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Caixa - Atendimento Devolução");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jb_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/printer.png"))); // NOI18N
        jb_imprimir.setText("Imprimir");
        jb_imprimir.setEnabled(false);
        jb_imprimir.setMaximumSize(new java.awt.Dimension(101, 33));
        jb_imprimir.setName("jb_imprimir"); // NOI18N
        jb_imprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_imprimirMouseClicked(evt);
            }
        });
        jb_imprimir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_imprimirKeyPressed(evt);
            }
        });

        jb_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/ok.png"))); // NOI18N
        jb_salvar.setText("Finalizar");
        jb_salvar.setEnabled(false);
        jb_salvar.setName("jb_salvar"); // NOI18N
        jb_salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salvarMouseClicked(evt);
            }
        });
        jb_salvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_salvarKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Verificar Permissão"));
        jPanel1.setName("jPanel1"); // NOI18N

        jtf_login.setEditable(false);
        jtf_login.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_login.setName("jtf_login"); // NOI18N
        jtf_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_loginActionPerformed(evt);
            }
        });
        jtf_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_loginKeyPressed(evt);
            }
        });

        jpf_senha.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jpf_senha.setName("jpf_senha"); // NOI18N
        jpf_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpf_senhaKeyPressed(evt);
            }
        });

        jb_logar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/http___iconesbr.oficinadanet.com_8533_16x16.png"))); // NOI18N
        jb_logar.setText("OK !");
        jb_logar.setName("jb_logar"); // NOI18N
        jb_logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_logarActionPerformed(evt);
            }
        });

        jLabel9.setText("Senha:");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel4.setText("Login:");
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_login, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jb_logar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(0, 0, 0)
                        .addComponent(jtf_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_logar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jpf_senha, jtf_login});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Caixa"));
        jPanel2.setName("jPanel2"); // NOI18N

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_total_relocacao.setEditable(false);
        jtf_total_relocacao.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jtf_total_relocacao.setForeground(new java.awt.Color(204, 0, 0));
        jtf_total_relocacao.setText("R$ 0,00");
        jtf_total_relocacao.setName("jtf_total_relocacao");
        jtf_total_relocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_total_relocacaoActionPerformed(evt);
            }
        });
        jtf_total_relocacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_total_relocacaoFocusGained(evt);
            }
        });
        jtf_total_relocacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_total_relocacaoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_total_relocacaoKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Total de Relocação:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Troco:");
        jLabel7.setName("jLabel7"); // NOI18N

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_troco.setEditable(false);
        jtf_troco.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jtf_troco.setText("R$ 0,00");
        jtf_troco.setName("jtf_troco"); // NOI18N
        jtf_troco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_trocoActionPerformed(evt);
            }
        });
        jtf_troco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_trocoFocusGained(evt);
            }
        });
        jtf_troco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_trocoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_trocoKeyReleased(evt);
            }
        });

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_debito_atual.setEditable(false);
        jtf_debito_atual.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jtf_debito_atual.setForeground(new java.awt.Color(204, 0, 0));
        jtf_debito_atual.setText("R$ 0,00");
        jtf_debito_atual.setName("jtf_debito_atual"); // NOI18N
        jtf_debito_atual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_debito_atualActionPerformed(evt);
            }
        });
        jtf_debito_atual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_debito_atualFocusGained(evt);
            }
        });
        jtf_debito_atual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_debito_atualKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_debito_atualKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Débito Atual:");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total Á Pagar:");
        jLabel3.setName("jLabel3"); // NOI18N

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_total_a_pagar.setEditable(false);
        jtf_total_a_pagar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jtf_total_a_pagar.setForeground(new java.awt.Color(204, 0, 0));
        jtf_total_a_pagar.setText("R$ 0,00");
        jtf_total_a_pagar.setName("jtf_total_a_pagar"); // NOI18N
        jtf_total_a_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_total_a_pagarActionPerformed(evt);
            }
        });
        jtf_total_a_pagar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_total_a_pagarFocusGained(evt);
            }
        });
        jtf_total_a_pagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_total_a_pagarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_total_a_pagarKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Valor Pago:");
        jLabel6.setName("jLabel6"); // NOI18N

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_valor_pago.setEditable(false);
        jtf_valor_pago.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jtf_valor_pago.setText("R$ 0,00");
        jtf_valor_pago.setEnabled(false);
        jtf_valor_pago.setName("jtf_valor_pago"); // NOI18N
        jtf_valor_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_valor_pagoActionPerformed(evt);
            }
        });
        jtf_valor_pago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_valor_pagoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_valor_pagoFocusLost(evt);
            }
        });
        jtf_valor_pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_valor_pagoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_valor_pagoKeyReleased(evt);
            }
        });

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_desconto_entrega_antecipada.setEditable(false);
        jtf_desconto_entrega_antecipada.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jtf_desconto_entrega_antecipada.setText("R$ 0,00");
        jtf_desconto_entrega_antecipada.setEnabled(false);
        jtf_desconto_entrega_antecipada.setName("jtf_desconto_entrega_antecipada"); // NOI18N
        jtf_desconto_entrega_antecipada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_desconto_entrega_antecipadaActionPerformed(evt);
            }
        });
        jtf_desconto_entrega_antecipada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_desconto_entrega_antecipadaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_desconto_entrega_antecipadaFocusLost(evt);
            }
        });
        jtf_desconto_entrega_antecipada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_desconto_entrega_antecipadaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_desconto_entrega_antecipadaKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Desconto Entrega Antecipada:");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Débito Total Anterior:");
        jLabel2.setName("jLabel2"); // NOI18N

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_debito_total_anterior.setEditable(false);
        jtf_debito_total_anterior.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jtf_debito_total_anterior.setForeground(new java.awt.Color(204, 0, 0));
        jtf_debito_total_anterior.setText("R$ 0,00");
        jtf_debito_total_anterior.setName("jtf_debito_total_anterior"); // NOI18N
        jtf_debito_total_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_debito_total_anteriorActionPerformed(evt);
            }
        });
        jtf_debito_total_anterior.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_debito_total_anteriorFocusGained(evt);
            }
        });
        jtf_debito_total_anterior.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_debito_total_anteriorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_debito_total_anteriorKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Valor Desconto:");
        jLabel5.setName("jLabel5"); // NOI18N

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_desconto.setEditable(false);
        jtf_desconto.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jtf_desconto.setText("R$ 0,00");
        jtf_desconto.setEnabled(false);
        jtf_desconto.setName("jtf_desconto"); // NOI18N
        jtf_desconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_descontoActionPerformed(evt);
            }
        });
        jtf_desconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_descontoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_descontoFocusLost(evt);
            }
        });
        jtf_desconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_descontoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_descontoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jtf_debito_atual, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jtf_total_relocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jtf_total_a_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtf_troco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_valor_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jtf_debito_total_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jtf_desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(10, 10, 10)
                                    .addComponent(jtf_desconto_entrega_antecipada, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_debito_total_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_total_relocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_desconto_entrega_antecipada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_desconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_total_a_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_valor_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_troco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_debito_atual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(10, 10, 10))
        );

        jb_cancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/exit.png"))); // NOI18N
        jb_cancelar1.setText("Sair");
        jb_cancelar1.setMaximumSize(new java.awt.Dimension(101, 33));
        jb_cancelar1.setName("jb_cancelar1"); // NOI18N
        jb_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelar1ActionPerformed(evt);
            }
        });
        jb_cancelar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_cancelar1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jb_salvar)
                        .addGap(10, 10, 10)
                        .addComponent(jb_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jb_cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jpf_senha.requestFocus();
        if (janelapaiDevolucao != null) {
            recalcularValores();
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        String nome_arquivo = "Imprimir/comprovanteLocacao_" + janelapaiDevolucao.dependente.getNome_dependente() + ".txt";
        File arquivo = new File(nome_arquivo);
        arquivo.deleteOnExit();
        arquivo.delete();

        retornaJanelaPai();
    }//GEN-LAST:event_formWindowClosed

    private void jtf_total_relocacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_total_relocacaoKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_relocacaoKeyPressed
    private void jtf_total_relocacaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_total_relocacaoFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_relocacaoFocusGained

    private void jtf_total_relocacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_total_relocacaoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_relocacaoKeyReleased

    private void jtf_total_relocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_total_relocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_relocacaoActionPerformed

    private void jtf_descontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_descontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descontoActionPerformed

    private void jtf_descontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_descontoFocusGained
        jtf_desconto.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descontoFocusGained

    private void jtf_descontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_descontoKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jb_salvar.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descontoKeyPressed

    private void jtf_descontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_descontoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descontoKeyReleased

    private void jtf_valor_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_valor_pagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valor_pagoActionPerformed

    private void jtf_valor_pagoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_valor_pagoFocusGained
        jtf_valor_pago.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valor_pagoFocusGained

    private void jtf_valor_pagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_valor_pagoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("Campo jtf_desconto == " + jtf_desconto.isEditable());
            jb_salvar.requestFocus();
        }
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valor_pagoKeyPressed

    private void jtf_valor_pagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_valor_pagoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valor_pagoKeyReleased

    private void jtf_trocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_trocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_trocoActionPerformed

    private void jtf_trocoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_trocoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_trocoFocusGained

    private void jtf_trocoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_trocoKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_trocoKeyPressed

    private void jtf_trocoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_trocoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_trocoKeyReleased

    private void jtf_debito_atualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_debito_atualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_debito_atualActionPerformed

    private void jtf_debito_atualFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_debito_atualFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_debito_atualFocusGained

    private void jtf_debito_atualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_debito_atualKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_debito_atualKeyPressed

    private void jtf_debito_atualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_debito_atualKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_debito_atualKeyReleased

    private void jtf_valor_pagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_valor_pagoFocusLost
        recalcularValores();        
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valor_pagoFocusLost

    private void jtf_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_loginKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_loginKeyPressed

    private void jpf_senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpf_senhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            entrar();
        }
        acionarAtalho(evt);
    }//GEN-LAST:event_jpf_senhaKeyPressed

    private void jb_logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_logarActionPerformed
        entrar();
    }//GEN-LAST:event_jb_logarActionPerformed

    private void jtf_descontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_descontoFocusLost
        recalcularValores();
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descontoFocusLost

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jb_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelar1ActionPerformed
        String nome_arquivo = "Imprimir/comprovanteLocacao_" + janelapaiDevolucao.dependente.getNome_dependente() + ".txt";
        File arquivo = new File(nome_arquivo);
        arquivo.deleteOnExit();
        arquivo.delete();

        retornaJanelaPai();
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_cancelar1ActionPerformed

    private void jtf_debito_total_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_debito_total_anteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_debito_total_anteriorActionPerformed

    private void jtf_debito_total_anteriorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_debito_total_anteriorFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_debito_total_anteriorFocusGained

    private void jtf_debito_total_anteriorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_debito_total_anteriorKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_debito_total_anteriorKeyPressed

    private void jtf_debito_total_anteriorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_debito_total_anteriorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_debito_total_anteriorKeyReleased

    private void jtf_total_a_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_total_a_pagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_a_pagarActionPerformed

    private void jtf_total_a_pagarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_total_a_pagarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_a_pagarFocusGained

    private void jtf_total_a_pagarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_total_a_pagarKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_a_pagarKeyPressed

    private void jtf_total_a_pagarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_total_a_pagarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_a_pagarKeyReleased

    private void jb_salvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_salvarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            finalizarCaixa();
        }
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarKeyPressed

    private void jb_imprimirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_imprimirKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            imprimir();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_imprimirKeyPressed

    private void jb_cancelar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_cancelar1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jb_cancelar1.doClick();
        }
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_cancelar1KeyPressed

    private void jtf_desconto_entrega_antecipadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_desconto_entrega_antecipadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_desconto_entrega_antecipadaActionPerformed

    private void jtf_desconto_entrega_antecipadaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_desconto_entrega_antecipadaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_desconto_entrega_antecipadaFocusGained

    private void jtf_desconto_entrega_antecipadaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_desconto_entrega_antecipadaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_desconto_entrega_antecipadaFocusLost

    private void jtf_desconto_entrega_antecipadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_desconto_entrega_antecipadaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_desconto_entrega_antecipadaKeyPressed

    private void jtf_desconto_entrega_antecipadaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_desconto_entrega_antecipadaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_desconto_entrega_antecipadaKeyReleased

    private void jb_salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salvarMouseClicked
        if (evt.getClickCount() == 1) {
            finalizarCaixa();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarMouseClicked

    private void jb_imprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_imprimirMouseClicked
        imprimir();
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_imprimirMouseClicked

    private void jtf_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_loginActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EntradaCaixaDevolucao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_cancelar1;
    private javax.swing.JButton jb_imprimir;
    private javax.swing.JButton jb_logar;
    private javax.swing.JButton jb_salvar;
    private javax.swing.JPasswordField jpf_senha;
    public static javax.swing.JTextField jtf_debito_atual;
    public static javax.swing.JTextField jtf_debito_total_anterior;
    public static javax.swing.JTextField jtf_desconto;
    public static javax.swing.JTextField jtf_desconto_entrega_antecipada;
    private javax.swing.JTextField jtf_login;
    public static javax.swing.JTextField jtf_total_a_pagar;
    public static javax.swing.JTextField jtf_total_relocacao;
    public static javax.swing.JTextField jtf_troco;
    public static javax.swing.JTextField jtf_valor_pago;
    private javax.swing.JTextArea tfa_similar;
    // End of variables declaration//GEN-END:variables

    public void setTela(String permissao) {
        if (permissao.equals("usuario")) {
//            jb_novo.setEnabled(false);
//            jb_alterar1.setEnabled(false);
//            jb_excluir1.setEnabled(false);
        } else {
        }
    }

    public void setStatusTela(boolean status) {
        if (status) {
            this.setVisible(status);
        }
        this.setEnabled(status);
    }

    private void entrar() {

        if (validaLogin()) {
            if (verificaLogin()) {
                jtf_login.setText(acesso.getUsuario().getLogin());
                jb_salvar.setEnabled(true);
                if (acesso.getEscrever() == 0) {
                    jtf_valor_pago.setEditable(true);
                    jtf_valor_pago.setEnabled(true);
                    jtf_desconto.setEditable(true);
                    jtf_desconto.setEnabled(true);
                    jtf_valor_pago.requestFocus();
                } else {
                    jtf_desconto.setText("R$ 0,00");
                    jtf_desconto.setEditable(false);
                    jtf_desconto.setEnabled(false);
                    jtf_valor_pago.setEditable(true);
                    jtf_valor_pago.setEnabled(true);
                    jtf_valor_pago.requestFocus();
                }
                ///Faz alguma coisa interessante
            } else {
                jpf_senha.requestFocus();
                jpf_senha.setText("");
                jtf_login.setText("");
                jtf_desconto.setText("R$ 0,00");
                jtf_valor_pago.setText("R$ 0,00");
                jtf_desconto.setEditable(false);
                jtf_desconto.setEnabled(false);
                jtf_valor_pago.setEditable(false);
                jtf_valor_pago.setEnabled(false);
                jb_salvar.setEnabled(false);
            }
        }
    }

    private boolean validaLogin() {
        String msgERRO = "Preencha os campos obrigatórios:\n";

        if (jpf_senha.getPassword().equals("")) {
            msgERRO = msgERRO + " *Senha\n";
        }

        if (!msgERRO.equals("Preencha os campos obrigatórios:\n")) {
            JOptionPane.showMessageDialog(this, msgERRO);
            return false;
        } else {
            return true;
        }

    }

    public List<Usuario> usuarios;
    public static AcessoUsuario acesso;

    public boolean verificaLogin() {
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        acesso = usuarioControl.verificarPermissao(jpf_senha.getText().trim(), "br.com.locadora.view.EntradaCaixaDevolucao");
        System.out.println("Usuário responsável Caixa: " + acesso.getUsuario().getNome_usuario());
        try {
            //verifica a senha
            char[] senha = jpf_senha.getPassword();
            char[] senhaDoBanco = acesso.getUsuario().getSenha().toCharArray();

            // verifica o tamanho da senha
            if (senha.length != senhaDoBanco.length) {
                JOptionPane.showMessageDialog(null, "Senha incorreta");
                jtf_login.setText("");
                return false; // se for diferente, retorna falso
            } else {
                for (int i = 0; i < senha.length; i++) {
                    if (senha[i] != senhaDoBanco[i]) {
                        JOptionPane.showMessageDialog(null, "Senha incorreta");
                        jtf_login.setText("");
                        return false; // se for diferente, retorna falso
                    }
                }
            }

            return true;

        } catch (Exception e) {
            System.out.println("Senha incorreta na Entrada de Caixa Devolucao");
            return false;
        }
    }

    public void finalizarCaixa() {
        ArquivoConfiguracao conf = new ArquivoConfiguracao();

        //Envia a gravação da locação e envia o lancamento de caixa
        if (!conf.readPropertie("caixa").equals("")) {
            if (jb_logar.isEnabled() == true) {
                if (validaLogin()) {
                    if (verificaLogin()) {
                        if (janelapaiDevolucao != null) {

                            calculaRelocacao();
                            cadastrarDevolucao();
                                                        
                            jpf_senha.setEnabled(false);
                            jb_logar.setEnabled(false);
                            jtf_valor_pago.setEnabled(false);
                            jtf_desconto.setEnabled(false);
                            jb_salvar.setEnabled(false);
                            jb_imprimir.setEnabled(true);
                            jb_imprimir.requestFocus();

                            DefaultTableModel tb_devolucao = (DefaultTableModel) janelapaiDevolucao.jtbl_devolucao.getModel();
                            int rows = tb_devolucao.getRowCount();
                            for (int i = rows - 1; i >= 0; i--) {
                                tb_devolucao.removeRow(i);
                            }
                            janelapaiDevolucao.jtf_codigo_cliente.setText("");
                            janelapaiDevolucao.jtf_nome_cliente.setText("");

                            janelapaiDevolucao.jtf_total_a_pagar.setText("R$ 0,00");
                            janelapaiDevolucao.jtf_debito_total_anterior.setText("R$ 0,00");
                            janelapaiDevolucao.jtf_total_desconto_entrega_antecipada.setText("R$ 0,00");

                        }
                    }
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Caixa padrão não definido. Favor verificar");
        }
    }

    public void calculaRelocacao() {
        pool = new Pool();
        LocacaoDAO locaDAO = new LocacaoDAO(pool);
        List<ItemLocacao> itensRelocacao = AtendimentoDevolucao.itensDevolucao;
        List<ItemLocacao> itensGravarRelocao = new ArrayList<ItemLocacao>();
        for (int i = 0; i < itensRelocacao.size(); i++) {
            if (itensRelocacao.get(i).getDias_multa() > 0) {
                itensGravarRelocao.add(itensRelocacao.get(i));
            }
        }

        locaDAO.salvarRelocacao(itensGravarRelocao);

    }

    public void acionarAtalho(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            finalizarCaixa();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            String nome_arquivo = "Imprimir/comprovanteLocacao_" + janelapaiDevolucao.dependente.getNome_dependente() + ".txt";
            File arquivo = new File(nome_arquivo);
            arquivo.deleteOnExit();
            arquivo.delete();

            retornaJanelaPai();
        }
    }

    private void imprimir() {
        try {
            Usuario usuario = acesso.getUsuario();
            Printer imprimir = new Printer();
            imprimir.comprovanteDevolucao(itens, AtendimentoDevolucao.dependente, usuario);
            String nome_arquivo = "Imprimir/comprovanteDevolucao_" + AtendimentoDevolucao.dependente.getNome_dependente() + ".txt";
            if (imprimir.imprimirArquivo(nome_arquivo)) {
                //Desabilita para não haver mais alteração

                jtf_valor_pago.setEditable(false);
                jtf_desconto.setEditable(false);
                //Fechar janela após impressão

                retornaJanelaPai();

                File arquivo = new File(nome_arquivo);
                arquivo.deleteOnExit();
                arquivo.delete();
            }

        } catch (PrintException ex) {
            JOptionPane.showMessageDialog(null, "Problema encontrado com impressora padrão.");
        }
    }

    public void retornaJanelaPai() {
        this.setVisible(false);
        if (janelapaiDevolucao != null) {
            janelapaiDevolucao.setStatusTela(true);
            janelapaiDevolucao.jtf_codigo_barras_objeto.requestFocus();
        }
    }

    public void recalcularValores() {
        Moeda moeda = new Moeda();
        Double debito_total_anterior = moeda.getPrecoFormato(janelapaiDevolucao.jtf_debito_total_anterior.getText());
        Double total_relocacao = moeda.getPrecoFormato(janelapaiDevolucao.jtf_valor_total_relocacao.getText());
        Double desconto_entrega_antecipada = moeda.getPrecoFormato(janelapaiDevolucao.jtf_total_desconto_entrega_antecipada.getText());
        Double descontos = moeda.getPrecoFormato(jtf_desconto.getText());
        Double valor_total_a_pagar = (debito_total_anterior + total_relocacao) - (desconto_entrega_antecipada + descontos);
        Double valor_pago = moeda.getPrecoFormato(jtf_valor_pago.getText());
        Double troco = valor_pago - valor_total_a_pagar;
        
        System.out.println("Total a pagar: "+ valor_total_a_pagar);
        System.out.println("Valor pago: "+ valor_pago);
        System.out.println("Troco: "+ troco);

        jtf_debito_total_anterior.setText(moeda.setPrecoFormat(debito_total_anterior.toString()));
        jtf_total_relocacao.setText(moeda.setPrecoFormat(total_relocacao.toString()));
        jtf_desconto_entrega_antecipada.setText(moeda.setPrecoFormat(desconto_entrega_antecipada.toString()));
        jtf_desconto.setText(moeda.setPrecoFormat(descontos.toString()));
        jtf_total_a_pagar.setText(moeda.setPrecoFormat(valor_total_a_pagar.toString()));
        jtf_valor_pago.setText(moeda.setPrecoFormat(valor_pago.toString()));

        if (troco > 0) {
            jtf_troco.setText(moeda.setPrecoFormat(troco.toString()));
            jtf_debito_atual.setText("R$ 0,00");
            jtf_debito_atual.setForeground(Color.black);
        } else if (troco < 0) {
            jtf_troco.setText("R$ 0,00");
            troco = troco * (-1);
            jtf_debito_atual.setText(moeda.setPrecoFormat(troco.toString()));
            jtf_debito_atual.setForeground(Color.red);
        } else {
            jtf_troco.setText("R$ 0,00");
            jtf_debito_atual.setText("R$ 0,00");
            jtf_debito_atual.setForeground(Color.black);
        }

    }
    
    public void cadastrarDevolucao() {

        try {            
            pool = new Pool();
            DevolucaoDAO devolucaoDAO = new DevolucaoDAO(pool);
            Dependente dependente = new Dependente();            
            
            dependente.setCodigo_dependente(janelapaiDevolucao.dependente.getCodigo_dependente());
            
            Locacao locacao = new Locacao();  
            
            locacao.setDependente(dependente);
            
            Usuario usuario = new Usuario();
            usuario.setCodigo_usuario(acesso.getUsuario().getCodigo_usuario());
            
            locacao.setUsuario(usuario);
            
            Double valor_pago;
            Double valor_desconto;
            Double multa;
            Double troco;
            Double desconto_entrega_antecipada;
            Moeda moeda = new Moeda();
            
            valor_pago = moeda.getPrecoFormato(jtf_valor_pago.getText());
            valor_desconto = moeda.getPrecoFormato(jtf_desconto.getText()); 
            multa = moeda.getPrecoFormato(jtf_total_relocacao.getText());
            desconto_entrega_antecipada = moeda.getPrecoFormato(jtf_desconto_entrega_antecipada.getText());
                    
            troco = moeda.getPrecoFormato(jtf_troco.getText());
            
            valor_pago = valor_pago - troco;
            
            ArquivoConfiguracao conf = new ArquivoConfiguracao();
            Lancamento lancamento = new Lancamento();
            lancamento.setCaixa(Integer.parseInt(conf.readPropertie("caixa")));
            lancamento.setUsuario(usuario);
            lancamento.setDependente(dependente);
            TipoServico tipoServico = new TipoServico();
            
            lancamento.setLocacao(locacao);
            
            if(valor_pago > 0 ){
                tipoServico.setCodigo_tipo_servico(7);
                lancamento.setValor(valor_pago);
            
                lancamento.setTipoServico(tipoServico);
                pool = new Pool();
                devolucaoDAO = new DevolucaoDAO(pool);
                devolucaoDAO.salvarLancamento(lancamento);            
            }     
            
            if(desconto_entrega_antecipada > 0 ){
                tipoServico.setCodigo_tipo_servico(9);
                lancamento.setValor(desconto_entrega_antecipada);
            
                lancamento.setTipoServico(tipoServico);
                pool = new Pool();
                devolucaoDAO = new DevolucaoDAO(pool);
                devolucaoDAO.salvarLancamento(lancamento);            
            }   
            
            if(valor_desconto > 0 ){
                tipoServico.setCodigo_tipo_servico(8);
                lancamento.setValor(valor_desconto);
                
                lancamento.setTipoServico(tipoServico);
                pool = new Pool();
                devolucaoDAO = new DevolucaoDAO(pool);
                devolucaoDAO.salvarLancamento(lancamento);
            }
            
            if(multa > 0 ){
                tipoServico.setCodigo_tipo_servico(2);
                lancamento.setValor(multa);
                
                lancamento.setTipoServico(tipoServico);
                pool = new Pool();
                devolucaoDAO = new DevolucaoDAO(pool);
                devolucaoDAO.salvarLancamento(lancamento);
            }
            
            List<ItemLocacao> itens = new ArrayList();
            ItemLocacao itemDevolve;
            Copia copia;
            for (int i = 0; i < AtendimentoDevolucao.jtbl_devolucao.getRowCount(); i++) {

                itemDevolve = new ItemLocacao();
                copia = new Copia();
                copia.setCodigo_copia(AtendimentoDevolucao.itensDevolucao.get(i).getCopia().getCodigo_copia());
                copia.setStatus("0");
                itemDevolve.setCopia(copia);
                itemDevolve.setCodigo_item_locacao(AtendimentoDevolucao.itensDevolucao.get(i).getCodigo_item_locacao());                
                
                Date data = new Date();          
                data.setDate(data.getDate());                         
                
                
                AtendimentoDevolucao.itensDevolucao.get(i).setData_devolucao(data);                        
                System.out.println("Data Prevista: "+ AtendimentoDevolucao.itensDevolucao.get(i).getData_prevista());
                itens.add(itemDevolve);
                
                pool = new Pool();
                CopiaDAO copiaDAO = new CopiaDAO(pool);
                copiaDAO.alterarStatusFilme(itemDevolve.getCopia());
                pool = new Pool();
                LocacaoDAO locacaoDAO = new LocacaoDAO(pool);
                locacaoDAO.salvarDevolucao(itens);

            }
                EntradaCaixaDevolucao.itens = AtendimentoDevolucao.itensDevolucao;
        } catch (NumberFormatException e) {
            System.out.println("Valor inválido: " + e.getMessage());

            e.printStackTrace();
        } catch (SQLException ex) {
            Logger.getLogger(EntradaCaixaDevolucao.class.getName()).log(Level.SEVERE, null, ex);
        }         
    }
}
