/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cad_Fornecedor.java
 *
 * Created on 06/04/2011, 16:41:51
 */
package br.com.locadora.view;

import br.com.locadora.model.dao.FornecedorDAO;
import br.com.locadora.model.bean.FornecedorModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alencar
 */
public class MenuFornecedor extends javax.swing.JFrame {

    public TelaPrincipal janelapai;

    /** Creates new form Cad_Fornecedor */
    public MenuFornecedor() {
        initComponents();
        listarFornecedor();
    }

    public void setTela(String permissao) {
//        if (permissao.equals("usuario")) {
//            jb_novo.setEnabled(false);
//            jb_alterar.setEnabled(false);
//            jb_excluir.setEnabled(false);
//        } else {
//        }
    }
    List<FornecedorModel> fornecedores;
    DefaultTableModel tmFornecedor = new DefaultTableModel(null, new String[]{"CÓDIGO", "RAZÃO SOCIAL", "NOME FANTASIA", "ENDEREÇO",
                "CNPJ", "TELEFONE", "FAX", "VENDEDOR", "TELEFONE VENDEDOR"});
    ListSelectionModel lsmFornecedor;
    String tipoCadastro;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_pesquisar = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jl_pesquisar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jrb_codigo = new javax.swing.JRadioButton();
        jrb_descricao = new javax.swing.JRadioButton();
        jrb_detalhamento = new javax.swing.JRadioButton();
        jtf_pesquisar = new javax.swing.JTextField();
        jb_novo = new javax.swing.JButton();
        jb_alterar = new javax.swing.JButton();
        jb_excluir = new javax.swing.JButton();
        jb_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de Fornecedores");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jt_pesquisar.setModel(tmFornecedor);
        jt_pesquisar.setName("jt_pesquisar"); // NOI18N
        jt_pesquisar.getTableHeader().setReorderingAllowed(false);
        jt_pesquisar.setModel(tmFornecedor);
        jt_pesquisar.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmFornecedor = jt_pesquisar.getSelectionModel();
        lsmFornecedor.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e){
                if (! e.getValueIsAdjusting()){
                    tbFornecedorLinhaSelecionada(jt_pesquisar);
                }
            }
        });
        jScrollPane1.setViewportView(jt_pesquisar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 202, 970, 220));

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 670, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultas"));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_pesquisar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jl_pesquisar.setText("Parâmetro");
        jl_pesquisar.setName("jl_pesquisar"); // NOI18N
        jPanel3.add(jl_pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/pesquisar.png"))); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        buttonGroup1.add(jrb_codigo);
        jrb_codigo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jrb_codigo.setText("Código");
        jrb_codigo.setName("jrb_codigo"); // NOI18N
        jPanel3.add(jrb_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        buttonGroup1.add(jrb_descricao);
        jrb_descricao.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jrb_descricao.setSelected(true);
        jrb_descricao.setText("Descrição");
        jrb_descricao.setName("jrb_descricao"); // NOI18N
        jPanel3.add(jrb_descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        buttonGroup1.add(jrb_detalhamento);
        jrb_detalhamento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jrb_detalhamento.setText("Específica");
        jrb_detalhamento.setName("jrb_detalhamento"); // NOI18N
        jPanel3.add(jrb_detalhamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jtf_pesquisar.setName("jtf_pesquisar"); // NOI18N
        jPanel3.add(jtf_pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 970, 130));

        jb_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/novo_registro.gif"))); // NOI18N
        jb_novo.setText("Novo");
        jb_novo.setName("jb_novo"); // NOI18N
        jb_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novoActionPerformed(evt);
            }
        });
        getContentPane().add(jb_novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, 35));

        jb_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/alterar_registro.gif"))); // NOI18N
        jb_alterar.setText("Alterar");
        jb_alterar.setName("jb_alterar"); // NOI18N
        jb_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_alterarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, 35));

        jb_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/delete.gif"))); // NOI18N
        jb_excluir.setText("Excluir");
        jb_excluir.setName("jb_excluir"); // NOI18N
        jb_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_excluirActionPerformed(evt);
            }
        });
        getContentPane().add(jb_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, 35));

        jb_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/exit.png"))); // NOI18N
        jb_sair.setText("Sair");
        jb_sair.setName("jb_sair"); // NOI18N
        jb_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_sairActionPerformed(evt);
            }
        });
        getContentPane().add(jb_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, 35));

        setSize(new java.awt.Dimension(1023, 482));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jtf_pesquisar.requestFocus();

        jt_pesquisar.getColumnModel().getColumn(0).setMaxWidth(70);
        jt_pesquisar.getColumnModel().getColumn(0).setMinWidth(70);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(70);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(0).setMinWidth(70);

        jt_pesquisar.getColumnModel().getColumn(1).setMaxWidth(230);
        jt_pesquisar.getColumnModel().getColumn(1).setMinWidth(230);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(230);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(1).setMinWidth(230);

        jt_pesquisar.getColumnModel().getColumn(2).setMaxWidth(200);
        jt_pesquisar.getColumnModel().getColumn(2).setMinWidth(200);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(200);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(2).setMinWidth(200);

        jt_pesquisar.getColumnModel().getColumn(3).setMaxWidth(150);
        jt_pesquisar.getColumnModel().getColumn(3).setMinWidth(150);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(150);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(3).setMinWidth(150);

        jt_pesquisar.getColumnModel().getColumn(4).setMaxWidth(120);
        jt_pesquisar.getColumnModel().getColumn(4).setMinWidth(120);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(120);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(4).setMinWidth(120);


        jt_pesquisar.getColumnModel().getColumn(5).setMaxWidth(100);
        jt_pesquisar.getColumnModel().getColumn(5).setMinWidth(100);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(5).setMaxWidth(100);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(5).setMinWidth(100);

        jt_pesquisar.getColumnModel().getColumn(6).setMaxWidth(100);
        jt_pesquisar.getColumnModel().getColumn(6).setMinWidth(100);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(6).setMaxWidth(100);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(6).setMinWidth(100);

        jt_pesquisar.getColumnModel().getColumn(7).setMaxWidth(100);
        jt_pesquisar.getColumnModel().getColumn(7).setMinWidth(100);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(7).setMaxWidth(100);
        jt_pesquisar.getTableHeader().getColumnModel().getColumn(7).setMinWidth(100);

    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jrb_codigo.isSelected() == true) {
            listarFornecedorCodigo();
        } else if (jrb_descricao.isSelected() == true) {
            listarFornecedorDescricao();
        } else if (jrb_detalhamento.isSelected() == true) {
            listarFornecedor();
        } else {
            listarFornecedor();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novoActionPerformed
        CadastroFornecedor forn = new CadastroFornecedor();
        forn.setVisible(true);
        forn.janelapai = this;
        this.setEnabled(false);
}//GEN-LAST:event_jb_novoActionPerformed

    private void jb_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_alterarActionPerformed
        FornecedorModel forn = tbFornecedorLinhaSelecionada(jt_pesquisar);
        if (forn != null) {
            AtualizaFornecedor fornecedorAltera = new AtualizaFornecedor(forn);
            fornecedorAltera.janelapai = this;
            fornecedorAltera.setVisible(true);
            this.setEnabled(false);
        } else {

            JOptionPane.showMessageDialog(null, "Selecione um fornecedor");
            jtf_pesquisar.requestFocus();
        }
        // TODO add your handling code here:
}//GEN-LAST:event_jb_alterarActionPerformed

    private void jb_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_sairActionPerformed
        this.setVisible(false);
        telaPrincipal.setStatusTela(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jb_sairActionPerformed

    private void jb_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_excluirActionPerformed
        excluiFornecedor();
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_excluirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.setVisible(false);
        telaPrincipal.setStatusTela(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MenuFornecedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_alterar;
    private javax.swing.JButton jb_excluir;
    private javax.swing.JButton jb_novo;
    private javax.swing.JButton jb_sair;
    private javax.swing.JLabel jl_pesquisar;
    private javax.swing.JRadioButton jrb_codigo;
    private javax.swing.JRadioButton jrb_descricao;
    private javax.swing.JRadioButton jrb_detalhamento;
    private javax.swing.JTable jt_pesquisar;
    private javax.swing.JTextField jtf_pesquisar;
    // End of variables declaration//GEN-END:variables
    private TelaPrincipal_Interface telaPrincipal;
    //Recebendo tela como parametro para atualização apos pesquisa

    public void setTelaPrincipal(TelaPrincipal_Interface telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
    }

    public void request() {
        jtf_pesquisar.requestFocus();
    }

    private void alteraDestino() {
    }

    public void listarFornecedor() {
        FornecedorDAO forn = new FornecedorDAO();
        fornecedores = forn.listarForncedor("%" + jtf_pesquisar.getText().trim() + "%");
        mostraForncedor(fornecedores);
    }

    private void listarFornecedorCodigo() {
        FornecedorDAO forn = new FornecedorDAO();
        fornecedores = forn.listarForncedorCodigo(jtf_pesquisar.getText().trim());
        mostraForncedor(fornecedores);
    }

    private void listarFornecedorDescricao() {
        FornecedorDAO forn = new FornecedorDAO();
        fornecedores = forn.listarForncedorDescricao(jtf_pesquisar.getText().trim() + "%");
        mostraForncedor(fornecedores);
    }

    public void mostraForncedor(List<FornecedorModel> fornecedor) {
        while (tmFornecedor.getRowCount() > 0) {
            tmFornecedor.removeRow(0);
        }

        if (fornecedor.size() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum fornecedor encontrado");

        } else {


            String[] campos = new String[]{null, null};
            for (int i = 0; i < fornecedor.size(); i++) {

                tmFornecedor.addRow(campos);

                jt_pesquisar.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);//comando para criar a barra de rolagem

                tmFornecedor.setValueAt(fornecedor.get(i).getCod_fornecedor(), i, 0);
                tmFornecedor.setValueAt(fornecedor.get(i).getRazao_social(), i, 1);
                tmFornecedor.setValueAt(fornecedor.get(i).getNome_fantasia(), i, 2);
                tmFornecedor.setValueAt(fornecedor.get(i).getEndereço(), i, 3);
                tmFornecedor.setValueAt(fornecedor.get(i).getCNPJ(), i, 4);
                tmFornecedor.setValueAt(fornecedor.get(i).getTelefone(), i, 5);
                tmFornecedor.setValueAt(fornecedor.get(i).getFax(), i, 6);
                tmFornecedor.setValueAt(fornecedor.get(i).getNome_vendedor(), i, 7);
                tmFornecedor.setValueAt(fornecedor.get(i).getTel_vendedor(), i, 8);

            }
        }

    }

    public FornecedorModel tbFornecedorLinhaSelecionada(JTable tb) {
        FornecedorModel forn = null;
        if (tb.getSelectedRow() != -1) {
            forn = new FornecedorModel();
            forn.setCod_fornecedor(fornecedores.get(tb.getSelectedRow()).getCod_fornecedor());
            forn.setRazao_social(fornecedores.get(tb.getSelectedRow()).getRazao_social());
            forn.setNome_fantasia(fornecedores.get(tb.getSelectedRow()).getNome_fantasia());
            forn.setEndereço(fornecedores.get(tb.getSelectedRow()).getEndereço());
            forn.setCNPJ(fornecedores.get(tb.getSelectedRow()).getCNPJ());
            forn.setTelefone(fornecedores.get(tb.getSelectedRow()).getTelefone());
            forn.setFax(fornecedores.get(tb.getSelectedRow()).getFax());
            forn.setCidade(fornecedores.get(tb.getSelectedRow()).getCidade());
            forn.setCEP(fornecedores.get(tb.getSelectedRow()).getCEP());
            forn.setEstado(fornecedores.get(tb.getSelectedRow()).getEstado());
            forn.setInsc_municipal(fornecedores.get(tb.getSelectedRow()).getInsc_municipal());
            forn.setInsc_estadual(fornecedores.get(tb.getSelectedRow()).getInsc_estadual());
            forn.setNome_vendedor(fornecedores.get(tb.getSelectedRow()).getNome_vendedor());
            forn.setTel_vendedor(fornecedores.get(tb.getSelectedRow()).getTel_vendedor());


        }
        return forn;
    }

    private void excluiFornecedor() {
        removeFornecedor(jt_pesquisar);

    }
    FornecedorModel fornecedor = new FornecedorModel();

    public FornecedorModel removeFornecedor(JTable tb) {
        if (tb.getSelectedRow() != -1) {
            int selectedOption = JOptionPane.showConfirmDialog(this, "Deseja excluir ?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (selectedOption == JOptionPane.YES_NO_OPTION) {
                FornecedorDAO fornecedorControl = new FornecedorDAO();
                fornecedor.setCod_fornecedor(fornecedores.get(tb.getSelectedRow()).getCod_fornecedor());
                if (fornecedorControl.excluiFornecedor(fornecedor)) {
                    tmFornecedor.removeRow(tb.getSelectedRow());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um destino");
        }
        return fornecedor;
    }
}
