package br.com.locadora.view;

import br.com.locadora.model.dao.ProdutoDAO;
import br.com.locadora.model.bean.Produto;
import br.com.locadora.model.bean.Usuario;
//import br.com.locadora.relatorios.Relatorios;
import br.com.locadora.util.Backup;
import br.com.locadora.util.Data;
import br.com.locadora.util.Restaurar;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

public class TelaPrincipal extends javax.swing.JFrame implements TelaPrincipal_Interface {

    IniciaLogin janelaPai;
    IniciaLogin janelaLogin;
    public Usuario usuario;
    public String usuarioNome;
    public Integer codUsuario;
    public String login;
    public String permissao;

    public TelaPrincipal() {
        initComponents();
        Data mostraData = new Data();
        mostraData.le_data();
        jlabel_data.setText("Data: " + mostraData.dia + "/" + mostraData.mes + "/" + mostraData.ano);
        mostraData.le_hora();
        jlabel_hora.setText("Hora: " + mostraData.hora);
        lookandField();
//        timer1.start();
//        vencidos();
        estoqueMinimo();
    }


    String seta_look;

    public void lookandField() {
        try {
//            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            // UIManager.setLookAndFeel("com.sun.java.swing.plaf.smoothmetal.SmoothmetalLookAndAndFeel");
            //UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            //UIManager.setLookAndFeel(seta_look);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        label_data = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jlabel_data = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlabel_hora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlabel_usuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMB_Cadastro = new javax.swing.JMenuBar();
        menu_cadastros = new javax.swing.JMenu();
        jmi_cliente = new javax.swing.JMenuItem();
        jmi_produto = new javax.swing.JMenuItem();
        jmi_fornecedor = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuitem_sair = new javax.swing.JMenuItem();
        menu_movimentos = new javax.swing.JMenu();
        jmi_entrada = new javax.swing.JMenuItem();
        menu_relatórios = new javax.swing.JMenu();
        menu_relatórios1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jmi_backup = new javax.swing.JMenuItem();
        jmi_recover = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_relatórios2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        jFrame1.setName("jFrame1"); // NOI18N

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText("File");
        jMenu1.setName("jMenu1"); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setName("jMenu2"); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenuBar2.setName("jMenuBar2"); // NOI18N

        jMenu3.setText("File");
        jMenu3.setName("jMenu3"); // NOI18N
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenu4.setName("jMenu4"); // NOI18N
        jMenuBar2.add(jMenu4);

        jMenuBar3.setName("jMenuBar3"); // NOI18N

        jMenu5.setText("File");
        jMenu5.setName("jMenu5"); // NOI18N
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenu6.setName("jMenu6"); // NOI18N
        jMenuBar3.add(jMenu6);

        jMenuBar4.setName("jMenuBar4"); // NOI18N

        jMenu7.setText("File");
        jMenu7.setName("jMenu7"); // NOI18N
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenu8.setName("jMenu8"); // NOI18N
        jMenuBar4.add(jMenu8);

        jMenuBar5.setName("jMenuBar5"); // NOI18N

        jMenu9.setText("File");
        jMenu9.setName("jMenu9"); // NOI18N
        jMenuBar5.add(jMenu9);

        jMenu10.setText("Edit");
        jMenu10.setName("jMenu10"); // NOI18N
        jMenuBar5.add(jMenu10);

        jMenuBar6.setName("jMenuBar6"); // NOI18N

        jMenu11.setText("File");
        jMenu11.setName("jMenu11"); // NOI18N
        jMenuBar6.add(jMenu11);

        jMenu12.setText("Edit");
        jMenu12.setName("jMenu12"); // NOI18N
        jMenuBar6.add(jMenu12);

        jMenuBar7.setName("jMenuBar7"); // NOI18N

        jMenu13.setText("File");
        jMenu13.setName("jMenu13"); // NOI18N
        jMenuBar7.add(jMenu13);

        jMenu14.setText("Edit");
        jMenu14.setName("jMenu14"); // NOI18N
        jMenuBar7.add(jMenu14);

        jMenuItem2.setText("jMenuItem2");
        jMenuItem2.setName("jMenuItem2"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Siscom Locadora");
        setExtendedState(MAXIMIZED_BOTH);
        setFocusable(false);
        setIconImages(null);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_data.setName("label_data"); // NOI18N
        getContentPane().add(label_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(1243, 632, -1, -1));

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        jlabel_data.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlabel_data.setText("Data:");
        jlabel_data.setName("jlabel_data"); // NOI18N
        jToolBar1.add(jlabel_data);

        jLabel2.setText("                               ");
        jLabel2.setName("jLabel2"); // NOI18N
        jToolBar1.add(jLabel2);

        jlabel_hora.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlabel_hora.setText("Hora:");
        jlabel_hora.setName("jlabel_hora"); // NOI18N
        jToolBar1.add(jlabel_hora);

        jLabel1.setText("                               ");
        jLabel1.setName("jLabel1"); // NOI18N
        jToolBar1.add(jLabel1);

        jlabel_usuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlabel_usuario.setText("Usuário: ");
        jlabel_usuario.setName("jlabel_usuario"); // NOI18N
        jToolBar1.add(jlabel_usuario);

        jLabel4.setText("                                                                                                                                                                ");
        jLabel4.setName("jLabel4"); // NOI18N
        jToolBar1.add(jLabel4);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Desenvolvido por Alencar Santos Buriti Júnior                                             ");
        jLabel3.setName("jLabel3"); // NOI18N
        jToolBar1.add(jLabel3);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1340, 25));

        jMB_Cadastro.setName("jMB_Cadastro"); // NOI18N

        menu_cadastros.setMnemonic('C');
        menu_cadastros.setText("Cadastro");
        menu_cadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastrosActionPerformed(evt);
            }
        });

        jmi_cliente.setMnemonic('P');
        jmi_cliente.setText("Cliente");
        jmi_cliente.setName("jmi_cliente"); // NOI18N
        jmi_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_clienteActionPerformed(evt);
            }
        });
        menu_cadastros.add(jmi_cliente);

        jmi_produto.setMnemonic('P');
        jmi_produto.setText("Produto");
        jmi_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_produtoActionPerformed(evt);
            }
        });
        menu_cadastros.add(jmi_produto);

        jmi_fornecedor.setMnemonic('F');
        jmi_fornecedor.setText("Fornecedor");
        jmi_fornecedor.setName("jmi_fornecedor"); // NOI18N
        jmi_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_fornecedorActionPerformed(evt);
            }
        });
        jmi_fornecedor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jmi_fornecedorAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        menu_cadastros.add(jmi_fornecedor);

        jSeparator4.setName("jSeparator4"); // NOI18N
        menu_cadastros.add(jSeparator4);

        jMenu15.setText("Locadora");
        jMenu15.setName("jMenu15"); // NOI18N

        jMenuItem4.setText("Objeto");
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem4);

        jMenuItem5.setText("Gênero");
        jMenuItem5.setName("jMenuItem5"); // NOI18N
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem5);

        jMenuItem11.setText("Diária");
        jMenuItem11.setName("jMenuItem11"); // NOI18N
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem11);

        jMenuItem3.setText("Gerar Código de Barras");
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenu15.add(jMenuItem3);

        jMenuItem12.setText("Idioma");
        jMenuItem12.setName("jMenuItem12"); // NOI18N
        jMenu15.add(jMenuItem12);

        jMenuItem13.setText("Legenda");
        jMenuItem13.setName("jMenuItem13"); // NOI18N
        jMenu15.add(jMenuItem13);

        jMenuItem14.setText("Mídia");
        jMenuItem14.setName("jMenuItem14"); // NOI18N
        jMenu15.add(jMenuItem14);

        jMenuItem15.setText("Tipo de Objeto");
        jMenuItem15.setName("jMenuItem15"); // NOI18N
        jMenu15.add(jMenuItem15);

        menu_cadastros.add(jMenu15);

        jSeparator2.setName("jSeparator2"); // NOI18N
        menu_cadastros.add(jSeparator2);

        menuitem_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/exit.png"))); // NOI18N
        menuitem_sair.setText("Sair");
        menuitem_sair.setName("menuitem_sair"); // NOI18N
        menuitem_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_sairActionPerformed(evt);
            }
        });
        menu_cadastros.add(menuitem_sair);

        jMB_Cadastro.add(menu_cadastros);

        menu_movimentos.setMnemonic('M');
        menu_movimentos.setText("Movimento");
        menu_movimentos.setName("menu_movimentos"); // NOI18N

        jmi_entrada.setText("Atendimento");
        jmi_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_entradaActionPerformed1(evt);
            }
        });
        menu_movimentos.add(jmi_entrada);

        jMB_Cadastro.add(menu_movimentos);

        menu_relatórios.setMnemonic('R');
        menu_relatórios.setText("Relatório");
        menu_relatórios.setName("menu_relatórios"); // NOI18N
        menu_relatórios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relatóriosActionPerformed(evt);
            }
        });
        jMB_Cadastro.add(menu_relatórios);

        menu_relatórios1.setMnemonic('R');
        menu_relatórios1.setText("Utilitários");
        menu_relatórios1.setName("menu_relatórios1"); // NOI18N
        menu_relatórios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relatórios1ActionPerformed(evt);
            }
        });

        jMenuItem9.setText("Calculadora ");
        jMenuItem9.setName("jMenuItem9"); // NOI18N
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed1(evt);
            }
        });
        menu_relatórios1.add(jMenuItem9);

        jmi_backup.setText("Backup");
        jmi_backup.setName("jmi_backup"); // NOI18N
        jmi_backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_backupActionPerformed(evt);
            }
        });
        menu_relatórios1.add(jmi_backup);

        jmi_recover.setText("Restaurar Backup");
        jmi_recover.setName("jmi_recover"); // NOI18N
        jmi_recover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_recoverActionPerformed(evt);
            }
        });
        menu_relatórios1.add(jmi_recover);

        jSeparator3.setName("jSeparator3"); // NOI18N
        menu_relatórios1.add(jSeparator3);

        jMenuItem1.setText("Trocar de usuário");
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_relatórios1.add(jMenuItem1);

        jSeparator1.setName("jSeparator1"); // NOI18N
        menu_relatórios1.add(jSeparator1);

        jMB_Cadastro.add(menu_relatórios1);

        menu_relatórios2.setMnemonic('R');
        menu_relatórios2.setText("Ajuda");
        menu_relatórios2.setName("menu_relatórios2"); // NOI18N
        menu_relatórios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relatórios2ActionPerformed(evt);
            }
        });

        jMenuItem10.setText("Help!");
        jMenuItem10.setName("jMenuItem10"); // NOI18N
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menu_relatórios2.add(jMenuItem10);

        jMB_Cadastro.add(menu_relatórios2);

        setJMenuBar(jMB_Cadastro);

        setSize(new java.awt.Dimension(1233, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuitem_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_entradaActionPerformed
        Atendimento atendimento;
        try {
            atendimento = new Atendimento();
            atendimento.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_menuitem_entradaActionPerformed
    boolean saida = false;
    
    private void jmi_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_produtoActionPerformed
        MenuProduto produtoGUI = new MenuProduto();
        produtoGUI.setTelaPrincipal(this);
        produtoGUI.setTela(permissao);
        produtoGUI.setVisible(true);
        setStatusTela(false);
    }//GEN-LAST:event_jmi_produtoActionPerformed

        boolean entrada = false;
        Atendimento atendimento;
    private void jmi_entradaActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_entradaActionPerformed1
        if(entrada == false){
            try {
                atendimento = new Atendimento();
            } catch (SQLException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            atendimento.setVisible(true);
            atendimento.setTelaPrincipal(this);
            atendimento.setJanelaPai(this); 
            entrada = true;
        } else {
            atendimento.setVisible(true);
        }

        //    setStatusTela(false);

    }//GEN-LAST:event_jmi_entradaActionPerformed1

    private void menu_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sairActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_sairActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        MenuGenero menuGenero = new MenuGenero();
        menuGenero.setTelaPrincipal(this);
        menuGenero.setVisible(true);
        setStatusTela(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menu_cadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastrosActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_menu_cadastrosActionPerformed

    private void menuitem_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_sairActionPerformed
        System.exit(0);
        // TODO add your handling code here:
}//GEN-LAST:event_menuitem_sairActionPerformed

    private void jmi_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_fornecedorActionPerformed
        MenuFornecedor fornecedorGUI = new MenuFornecedor();
        fornecedorGUI.setTelaPrincipal(this);
        fornecedorGUI.setVisible(true);
//        setStatusTela(false);
    }//GEN-LAST:event_jmi_fornecedorActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jmi_fornecedorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jmi_fornecedorAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_fornecedorAncestorAdded

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        Data mostraData = new Data();
        mostraData.le_hora();
        jlabel_hora.setText("Hora: " + mostraData.hora);

    }//GEN-LAST:event_timer1OnTime

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void menu_relatóriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relatóriosActionPerformed
//        RelatórioVencidosGUI relatorioVencidos = new RelatórioVencidosGUI();
//        relatorioVencidos.setTelaPrincipal(this);
//        relatorioVencidos.janelapai = this;
//        relatorioVencidos.setVisible(true);
//        setStatusTela(false);
        // TODO add your handling code here:
}//GEN-LAST:event_menu_relatóriosActionPerformed

    private void menu_relatórios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relatórios1ActionPerformed
        System.exit(0);
        IniciaLogin login = new IniciaLogin();
        login.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_relatórios1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try {
            Runtime.getRuntime().exec("calc");
        } catch (IOException exc) {
            exc.printStackTrace();
        }        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void menu_relatórios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relatórios2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_relatórios2ActionPerformed
    boolean ajuste = false;

        boolean armazemGUI = false;
    private void jMenuItem9ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed1
        try {
            Runtime.getRuntime().exec("calc");
        } catch (IOException exc) {
            exc.printStackTrace();
        }          // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem9ActionPerformed1

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        setVisible(false);
        IniciaLogin login = new IniciaLogin();
        login.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

private void jmi_backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_backupActionPerformed
    Backup backup = new Backup();
    backup.setVisible(true);
}//GEN-LAST:event_jmi_backupActionPerformed

private void jmi_recoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_recoverActionPerformed
    Restaurar recover = new Restaurar();
    recover.setVisible(true);
}//GEN-LAST:event_jmi_recoverActionPerformed

    private void jmi_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_clienteActionPerformed
        MenuCliente cliente_principal;
        cliente_principal = new MenuCliente();
        cliente_principal.setTelaPrincipal(this);
        cliente_principal.setVisible(true);
//        setStatusTela(false);
    }//GEN-LAST:event_jmi_clienteActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        MenuDiaria menuDiaria = new MenuDiaria();
        menuDiaria.setTelaPrincipal(this);
        menuDiaria.setVisible(true);
//        setStatusTela(false);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        MenuObjeto menuObjeto = new MenuObjeto();
        menuObjeto.setTelaPrincipal(this);
        menuObjeto.setVisible(true);
        setStatusTela(false);        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipal().setVisible(true);

            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMB_Cadastro;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jlabel_data;
    private javax.swing.JLabel jlabel_hora;
    private javax.swing.JLabel jlabel_usuario;
    private javax.swing.JMenuItem jmi_backup;
    private javax.swing.JMenuItem jmi_cliente;
    private javax.swing.JMenuItem jmi_entrada;
    private javax.swing.JMenuItem jmi_fornecedor;
    private javax.swing.JMenuItem jmi_produto;
    private javax.swing.JMenuItem jmi_recover;
    private javax.swing.JLabel label_data;
    private javax.swing.JMenu menu_cadastros;
    private javax.swing.JMenu menu_movimentos;
    private javax.swing.JMenu menu_relatórios;
    private javax.swing.JMenu menu_relatórios1;
    private javax.swing.JMenu menu_relatórios2;
    private javax.swing.JMenuItem menuitem_sair;
    // End of variables declaration//GEN-END:variables

    public void setDesabilitaTela() {
        this.setVisible(false);
        this.setEnabled(false);
    }

    public void setHabilitaTela(boolean status) {
    }

    public void setStatusTela(boolean status) {
        if (status) {
            this.setVisible(status);
        }
        this.setEnabled(status);
    }

    public void carregaUsuario(Usuario usuario) {
        this.usuario = usuario;
        jlabel_usuario.setText("Usuário: " + usuario.getNome_usuario());
    }
    List<Produto> produtos;

//    public void vencidos() {
//        ProdutoDAO controlProduto = new ProdutoDAO();
//        produtos = controlProduto.listarProdutoVencidos();
//        mostrarProdutosVencidos(produtos);
//    }
//
//    public void mostrarProdutosVencidos(List<ProdutoModel> produtos) {
//        DefaultTableModel tableModel = (DefaultTableModel) jt_ideal.getModel();
//        tableModel.setNumRows(0);
//        
//        for (int i = 0; i < produtos.size(); i++) {
//            try {
//                SimpleDateFormat in = new SimpleDateFormat("yyyy-MM-dd");
//                SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
//
//
//                String vencimento = out.format(in.parse(produtos.get(i).getData().toString()));
//
//
//                Produto produto = new Produto();
//                produto.setCod_produto(produtos.get(i).getCod_produto());
//                produto.setNome_produto(produtos.get(i).getNome_produto());
//                produto.setConcentraçao(produtos.get(i).getConcentraçao());
//                produto.setEstoque(produtos.get(i).getEstoque());
//                produto.setData(produtos.get(i).getData());
//                DefaultTableModel row = (DefaultTableModel) jt_ideal.getModel();
//                ItemDbGrid hashDbGrid = new ItemDbGrid(produto, produto.getNome_produto());
//                row.addRow(new Object[]{hashDbGrid, produto.getConcentraçao(), vencimento, produto.getEstoque()});
//                //Integer total = String.valueOf(i)+1;
//                jl_quantidade.setText("Total: " + (i + 1));
//            } catch (ParseException ex) {
//                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
//    }

    public void estoqueMinimo() {
        ProdutoDAO controlProduto = new ProdutoDAO();
        produtos = controlProduto.listarMinimo();
//        mostrarProdutosMinimo(produtos);
    }

//    public void mostrarProdutosMinimo(List<ProdutoModel> produtos) {
//        DefaultTableModel tableModel = (DefaultTableModel) jt_minimo.getModel();
//        tableModel.setNumRows(0);
//
////        ((DefaultTableModel) jt_minimo.getModel()).setRowCount(0);
////        jt_minimo.updateUI();
//
//        for (int i = 0; i < produtos.size(); i++) {
//
////            SimpleDateFormat in = new SimpleDateFormat("yyyy-MM-dd");
////            SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
//
//
//            //String vencimento = out.format(in.parse(produtos.get(i).getData().toString()));
//            Produto produto = new Produto();
//            produto.setCod_produto(produtos.get(i).getCod_produto());
//            produto.setNome_produto(produtos.get(i).getNome_produto());
//            produto.setConcentraçao(produtos.get(i).getConcentraçao());
//            produto.setEstoque_minimo(produtos.get(i).getEstoque_minimo());
//            produto.setEstoque(produtos.get(i).getEstoque());
//
//            DefaultTableModel row = (DefaultTableModel) jt_minimo.getModel();
//            ItemDbGrid hashDbGrid = new ItemDbGrid(produto, produto.getNome_produto());
//
//            row.addRow(new Object[]{hashDbGrid, produto.getConcentraçao(), produto.getEstoque_minimo(), produto.getEstoque()});
//            jl_minimo.setText("Total: " + (i + 1));
//        }
//    }

//    public void permissao() {
//
//        jmi_usuarios.setEnabled(false);
//        jb_usuario.setEnabled(false);
//        jb_ajuste.setEnabled(false);
//        jb_entrada.setEnabled(false);
//        jb_saida.setEnabled(false);
//        jb_usuario.setEnabled(false);
//        jButton10.setEnabled(false);
//        jButton12.setEnabled(false);
//        jButton14.setEnabled(false);
//        jmi_backup.setEnabled(false);
//        jmi_recover.setEnabled(false);
//        jmi_entrada.setEnabled(false);
//        jmi_saida.setEnabled(false);
//        jmi_ajuste.setEnabled(false);
//        jmi_destino.setEnabled(false);
//        jmi_fornecedor.setEnabled(false);
//        jmi_grupo.setEnabled(false);
//        jmi_unidade.setEnabled(false);
//    }
    
        public void setJanelaPai(IniciaLogin janelaPai) {
        jlabel_usuario.setText("Usuário: " + janelaPai.usuarioNome);
        this.janelaPai = janelaPai;
        usuarioNome = janelaPai.usuarioNome;
        codUsuario = janelaPai.codUsuário;
        login = janelaPai.login;
        permissao = janelaPai.permissao;
    }

    public void setUsuario() {
        usuario.setCod_usuario(codUsuario);
        usuario.setNome_usuário(usuarioNome);
        usuario.setPermissao(permissao);
        usuario.setLogin(login);
        JOptionPane.showMessageDialog(null, usuario.getCod_usuario() + usuario.getNome_usuario() + usuario.getPermissao());
    }
}
